// =============================================================================
// alu.sv - the ALU
// =============================================================================
//
// GENERATED by tools/gen-alu.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run `npm run rtl`.
//
// Two sixteen-bit inputs and one sixteen-bit output, as README.md says, and a
// four-bit microcode field for the operation.  Every operation, and the
// instructions whose semantics call for it:
//
//    0  add    lhs + rhs
//            add
//    1  rsb    rhs - lhs
//            rsb
//    2  iseq   lhs == rhs, as 0 or 1
//            iseq
//    3  isset  (lhs & rhs) != 0, as 0 or 1
//            isset
//    4  xor    lhs ^ rhs
//            xor
//    5  or     lhs | rhs
//            or
//    6  and    lhs & rhs
//            and
//    7  rhs    rhs
//            ld8 (the bytes, assembled by the capture), ld (the bytes,
//            assembled by the capture), mov, push (the stepped pointer), pop
//            (the words, then the pointer), stm (the stepped pointer), ldm
//            (the words, then the pointer), call (the return address), brk
//            (the shadows, through the flop), rti (the shadows, through the
//            flop)
//    8  shl    lhs << rhs[3:0]
//            shl
//    9  lsr    lhs >> rhs[3:0]
//            lsr
//   10  movhi  rhs[7:0] over lhs[7:0]
//            movhi
//   11  asr    lhs >>> rhs[3:0]
//            asr
//   12  unary  rtl/unary.sv's fast operations on lhs
//            sxt8, bitrev, clmul
//   13  slow   rtl/unary.sv's slow operations, registered a cycle earlier
//            clz, popcount
//
//   14, 15 are free.  Not yet: .
//
// BRANCHES ARE DECIDED BESIDE THE ALU, NOT IN IT.  rtl/compare.sv takes the
// same two operands and answers one bit that never enters this block's result,
// so nothing here waits for flags.  What stays is what writes a register: iseq
// is the NOR of lhs ^ rhs and isset the OR of lhs & rhs, neither of which needs
// the carry chain, so the only carry left in the ALU is add and rsb's own.
//
// THE SLOW PAIR IS REGISTERED.  clz and popcount are the two deep operations,
// so rtl/unary.sv puts a register behind them: operation 13 reads the result
// computed from the previous cycle's lhs, and the microcode gives those
// instructions the cycle to compute it in - rtl/ucode.sv's SLOW step.  lhs and
// rhs do not change between the two cycles, because the instruction and its
// selects are already in flops.  So no path through them is longer than one
// operand select, a unary pair, and a register.  This is the one clocked input.
//
// THE CODES FOLLOW THE CIRCUIT.  Code bit 0 is the adder's subtract, so add and
// rsb differ in one wire.  The shifts put their direction in bit 0 and
// arithmetic in bit 1, so asr is 11 and 10 is free.
//
// MEASURED on an iCE40 UP5K, yosys 0.52 -nobram + nextpnr-ice40 0.7, logic
// cells and the median of five placement seeds.  ALONE is registered operands
// into the units and a flop behind each; the DATAPATH is placement A of
// rtl/insn.sv - the instruction and microcode registered, rtl/lhs.sv and
// rtl/rhs.sv reading an 8x16 register file, rtl/cond.sv, the units, flops:
//
//                                              alone             datapath
//     one ALU with the comparison inside       500   37.9 MHz    1061   23.4 MHz
//     THIS FILE alone                          515   45.0        1035   26.5
//     rtl/compare.sv alone                     167   47.1         672   26.0
//     THIS FILE and rtl/compare.sv together    540   45.3        1055   25.2
//
// SEPARATING THEM IS WORTH A FIFTH OF THE ALU'S CLOCK on its own, and a twelfth
// behind the register file, for a second subtractor.  The comparison had set
// the combined ALU's speed: its critical path ran from the subtract, through
// the carry chain, N and V and the condition, to the negate.  Now the ALU's
// path ends at its result mux, and the compare unit has headroom beside it.
//
// BEHIND THE REGISTER FILE THE TWO PATHS ARE LEVEL, at about 26 MHz each, and
// what sets that is in front of both: a bare add in the same place measured
// 38.0.  Reading a register through rtl/lhs.sv and rtl/rhs.sv is the next thing
// to shorten, and rtl/insn.sv's placement C - register addresses from `view`
// - is the measured way to do it.
//
// Two shapes were measured and not taken, with the comparison still inside:
// splitting the result mux by speed into an inner mux over xor, or, and, rhs
// and test and an eight-input outer one was no faster and twenty cells bigger,
// because the width of the mux was never what set the clock; and signed lt as
// (signs differ ? rhs[15] : ~C) instead of N ^ V was correct but inside the
// seeds' noise.
// =============================================================================

module alu (
    input  logic        clk,     // for rtl/unary.sv's slow pair only
    input  logic [15:0] lhs,     // register file port A: rtl/lhs.sv
    input  logic [15:0] rhs,     // rtl/rhs.sv
    input  logic [3:0]  op,      // microcode: which operation
    output logic [15:0] y
);

    wire        sub  = op[0];
    wire [15:0] sum  = rhs + (lhs ^ {16{sub}}) + {15'd0, sub};
    wire [15:0] xorv = lhs ^ rhs;
    wire [15:0] andv = lhs & rhs;
    wire [15:0] hiv  = {rhs[7:0], lhs[7:0]};
    wire [3:0]  amt  = rhs[3:0];
    wire [15:0] unf, uns;
    unary u (.clk(clk), .a(lhs), .sel(rhs[2:1]), .fast(unf), .slow(uns));   // two bits of the imm3 value

    always_comb case (op)
        4'd0, 4'd1: y = sum;
        4'd2:       y = {15'd0, ~|xorv};
        4'd3:       y = {15'd0, |andv};
        4'd4:       y = xorv;
        4'd5:       y = lhs | rhs;
        4'd6:       y = andv;
        4'd7:       y = rhs;
        4'd8:       y = lhs << amt;
        4'd9:       y = lhs >> amt;
        4'd10:      y = hiv;
        4'd11:      y = $signed(lhs) >>> amt;
        4'd12:      y = unf;
        4'd13:      y = uns;
        default:    y = 16'hxxxx;
    endcase

endmodule
