// =============================================================================
// compare.sv - the branch decision
// =============================================================================
//
// GENERATED by tools/gen-compare.js from isa/fructus.toml.  Do not edit; edit
// the spec or the generator and run `npm run rtl`.
//
// The same two operands as rtl/alu.sv, a condition from rtl/cond.sv, and one
// bit out.  Two modes:
//
//   subtract   the condition on the flags of rhs - lhs
//              br, the cond3 field; br, the condimm5 table
//   mask       eq or ne on lhs & rhs being zero
//              brclr, eq; brset, ne
//
// The mode is rtl/cond.sv's `mask`, which is its source field's bit 1: the
// fixed eq and ne sources serve exactly the two mask branches.  So choosing the
// mode costs the microcode nothing.
//
// IT IS NOT THE ALU, and that is the point.  Nothing here reaches a register;
// `taken` goes to the branch logic and nowhere else, so the carry chain, the
// flags and the condition logic lengthen no path but their own.  iseq and isset,
// which answer a bit into a register, are ALU operations - and need no carry.
//
// THE CONDITION LOGIC is laid out on cond3's order - lt lo le ls eq ne vs vc:
//
//     lt  N ^ V        le  lt | Z        eq  Z        vs  V
//     lo  ~C           ls  lo | Z        ne  ~Z       vc  ~V
//
// so bit 0 of the first four picks unsigned and bit 1 adds Z, and in the last
// four bit 1 picks V over Z and bit 0 inverts.  `neg` inverts once more, for
// the packed branch's mirrored entries; see rtl/cond.sv.
//
// Z DOES NOT WAIT FOR THE CARRY CHAIN.  rhs - lhs is zero exactly when the two
// are equal, so the subtract mode's Z is the NOR of lhs ^ rhs, beside the adder
// rather than after it; the mask mode's is the NOR of lhs & rhs.
//
// MEASURED - see rtl/alu.sv, which has the numbers for both units.
// =============================================================================

module compare (
    input  logic [15:0] lhs,     // register file port A: rtl/lhs.sv
    input  logic [15:0] rhs,     // rtl/rhs.sv
    input  logic [2:0]  cond,    // rtl/cond.sv: a cond3 index
    input  logic        neg,     // rtl/cond.sv: invert the answer
    input  logic        mask,    // rtl/cond.sv: test lhs & rhs rather than subtract
    output logic        taken    // -> the branch logic
);

    // --- rhs - lhs, for its flags only ---------------------------------------
    wire [16:0] s = {1'b0, rhs} + {1'b0, ~lhs} + 17'd1;
    wire c = s[16];                                   // no borrow: rhs >= lhs
    wire n = s[15];
    wire v = (rhs[15] ^ lhs[15]) & (rhs[15] ^ s[15]);
    wire z = mask ? ~|(lhs & rhs) : ~|(lhs ^ rhs);

    // --- the condition -------------------------------------------------------
    wire ord  = cond[0] ? ~c : n ^ v;
    wire base = cond[2] ? (cond[1] ? v : z) : (ord | (cond[1] & z));
    assign taken = base ^ (cond[2] & cond[0]) ^ neg;

endmodule
