// =============================================================================
// cond.sv - the condition a comparison tests
// =============================================================================
//
// GENERATED by tools/gen-cond.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run `npm run rtl`.
//
// A cond3 index, a negate bit and a mode for rtl/compare.sv, from ONE two-bit
// microcode field:
//
//     0  the cond3 field, insn[10:8]      br cond, ra, rb
//     1  the condimm5 table, insn[15:11]  br cond, ra, #imm
//     2  eq                               brclr
//     3  ne                               brset
//
// The fixed eq and ne serve exactly the two mask branches, so bit 1 of the
// field is also the compare unit's mode - `mask`, test lhs & rhs rather than
// subtract - and the mode costs no microcode bit.
//
// THE COMPARE UNIT TESTS THE FLAGS OF rhs - lhs.  For the two-register branch
// that is R[a] - R[b], because port B carries a, so the cond3 field goes
// through as it stands.  For the packed branch it is imm - R[a], so every table
// entry has to be turned round, and TURNING IT ROUND IS NOT ENOUGH ON ITS OWN.
//
// `R[a] >= k` mirrors to `k <= R[a]`, which is le - fine.  But `R[a] < k`
// mirrors to `k > R[a]`, and cond3 has no gt: it spells gt by exchanging the
// two registers, and a register cannot be exchanged with a constant.  So the
// compare unit takes a NEGATE bit as well, and `k > R[a]` is
// `not (k <= R[a])`.  It is one XOR on a one-bit result.  (isa/fructus.toml
// says cond3's operand-order bit covers this; for the packed form it does not.)
//
// Every entry, as the programmer writes it and as the compare unit tests it -
// each checked against tools/sim.js for all 65536 values of R[a]:
//
//      0  eq #0            eq
//      1  ne #0            ne
//      2  lt #0        not le
//      3  ge #0            le
//      4  eq #1            eq
//      5  ne #1            ne
//      6  lt #1        not le
//      7  ge #1            le
//      8  eq #-1           eq
//      9  ne #-1           ne
//     10  lt #-1       not le
//     11  ge #-1           le
//     12  eq #2            eq
//     13  ne #2            ne
//     14  lt #2        not le
//     15  ge #2            le
//     16  lt #4        not le
//     17  ge #8            le
//     18  ge #32767        le
//     19  ge #32766        le
//     20  lt #-32767   not le
//     21  lt #-32766   not le
//     22  lo #2        not ls
//     23  hs #2            ls
//     24  hs #3            ls
//     25  lo #4        not ls
//     26  hs #4            ls
//     27  lo #6        not ls
//     28  lo #8        not ls
//     29  hs #8            ls
//     30  lo #256      not ls
//     31  hs #256          ls
//
// The whole table needs only eq, ne, not le, le, not ls, ls.
// =============================================================================

module cond (
    input  logic [23:0] insn,    // the instruction, byte 0 low, as rtl/cpu.sv's decode has it
    input  logic [1:0]  src,     // microcode: where the condition comes from
    output logic [2:0]  code,    // -> compare's cond: a cond3 index.  Not
                                 // `cond`: a port named after its module is
                                 // an error to verilator
    output logic        neg,     // -> compare: invert the answer
    output logic        mask     // -> compare: the mask branches' mode
);

    wire [4:0] k = insn[15:11];
    logic [3:0] tab;             // {neg, cond}
    always_comb case (k)
        5'd0: tab = 4'b0_100;    // eq #0
        5'd1: tab = 4'b0_101;    // ne #0
        5'd2: tab = 4'b1_010;    // lt #0
        5'd3: tab = 4'b0_010;    // ge #0
        5'd4: tab = 4'b0_100;    // eq #1
        5'd5: tab = 4'b0_101;    // ne #1
        5'd6: tab = 4'b1_010;    // lt #1
        5'd7: tab = 4'b0_010;    // ge #1
        5'd8: tab = 4'b0_100;    // eq #-1
        5'd9: tab = 4'b0_101;    // ne #-1
        5'd10: tab = 4'b1_010;    // lt #-1
        5'd11: tab = 4'b0_010;    // ge #-1
        5'd12: tab = 4'b0_100;    // eq #2
        5'd13: tab = 4'b0_101;    // ne #2
        5'd14: tab = 4'b1_010;    // lt #2
        5'd15: tab = 4'b0_010;    // ge #2
        5'd16: tab = 4'b1_010;    // lt #4
        5'd17: tab = 4'b0_010;    // ge #8
        5'd18: tab = 4'b0_010;    // ge #32767
        5'd19: tab = 4'b0_010;    // ge #32766
        5'd20: tab = 4'b1_010;    // lt #-32767
        5'd21: tab = 4'b1_010;    // lt #-32766
        5'd22: tab = 4'b1_011;    // lo #2
        5'd23: tab = 4'b0_011;    // hs #2
        5'd24: tab = 4'b0_011;    // hs #3
        5'd25: tab = 4'b1_011;    // lo #4
        5'd26: tab = 4'b0_011;    // hs #4
        5'd27: tab = 4'b1_011;    // lo #6
        5'd28: tab = 4'b1_011;    // lo #8
        5'd29: tab = 4'b0_011;    // hs #8
        5'd30: tab = 4'b1_011;    // lo #256
        5'd31: tab = 4'b0_011;    // hs #256
    endcase

    wire [3:0] field = {1'b0, insn[10:8]};
    wire [3:0] fixed = {1'b0, 3'd4 | {2'b00, src[0]}};     // eq, ne

    assign {neg, code} = src[1] ? fixed : (src[0] ? tab : field);
    assign mask        = src[1];

endmodule
