// =============================================================================
// cpu.sv - the processor, as far as it goes
// =============================================================================
//
// GENERATED by tools/gen-cpu.js.  Do not edit; edit the generator and run
// `npm run rtl`.
//
// What runs: whatever rtl/ucode.sv implements - today every instruction whose
// effect is one ALU result written to one register, and halt and nop.  No
// memory writes, no branches, no pc loads yet, so the pc only counts.
//
// MEMORY IS OUTSIDE, as a synchronous read: `mem_addr` is sampled at the clock
// edge and the byte at that address is on `mem_rdata` for the following cycle.
// That is the UP5K's SPRAM and the 6502-like bus the cost model describes: one
// cycle per byte.
//
// THE pc IS THE ADDRESS OF THE BYTE ON THE BUS.  A step that consumes that byte
// - a fetch or a dispatch - presents pc + 1 at the edge that ends it, so the
// following byte arrives for the next step; one that consumes nothing presents
// pc again.  Reset presents 0, so the first word after it finds address 0's
// byte on the bus and dispatches it.
//
// `result` IS THE ALU'S OUTPUT, and it is a port only so that something outside
// can see the datapath: with no stores yet, the register file feeds only the
// ALU and the ALU only the register file, and a synthesis tool is entitled to
// remove a loop nothing observes.
//
// THE REGISTER FILE IS FLOPS AND MUXES, never block RAM: its two reads are
// asynchronous, which the part's block RAM is not.  The attribute says so,
// because the ROM beside it is block RAM and synthesis is left free to infer.
//
// THE OPERANDS ARE READ A CYCLE BEFORE THEY ARE USED, which is where the clock
// comes from.  rtl/lhs.sv, rtl/rhs.sv and rtl/immgen.sv read `view` - the
// instruction with this cycle's byte already in place - so an instruction's
// last fetch cycle also selects, reads and latches both ALU inputs.  The
// execute cycle is then flops -> ALU -> result mux -> register file, with the
// register read out of it entirely.
//
// NO FORWARDING IS NEEDED, and that is a property of the sequencing rather than
// luck.  Every instruction has a cycle between its dispatch and its execute -
// a fetch for the multi-byte forms, an entry word that fetches nothing for the
// one-byte ones - and the previous write lands at the edge that begins it.
// So a read never shares a cycle with the write it must see.  An instruction
// that executed in its dispatch cycle would need a bypass from the ALU result
// into these flops, which measured 5 MHz slower than the extra cycle costs.
//
// MEASURED on an iCE40 UP5K, yosys 0.52 + nextpnr-ice40 0.7, behind a real
// SB_SPRAM256KA holding the program, logic cells and the median of eight
// placement seeds:
//
//                                                    LUT4   block RAMs   MHz
//     rtl/predecode.sv's table left to infer            858        3      20.9
//     microcode ROM in block RAM, predecode in LUTs     922        1      21.9
//     microcode ROM in LUTs as well                     956        0      22.0
//     clz and popcount registered                       947        2      23.7
//     the mask columns swapped, immask5 reordered       938        2      23.3
//     the operands read a cycle early, as now           866        2      34.3
//
// READING THE OPERANDS EARLY IS THE LARGEST STEP MEASURED SO FAR: 23.3 to 34.3
// MHz, medians of eight placement seeds, and 72 cells smaller.  The critical
// path went from ten cells to seven - instruction register, select, register
// read, ALU, write - and is now operand flop, ALU, result mux, write, with 9.5
// ns of logic against 20.5 of routing.  The register file's read muxes no
// longer feed the ALU at all, which is where the cells went too.
//
// THE ALTERNATIVE WAS A FORWARDING PATH, and it was measured rather than
// argued: letting a one-byte form execute in its dispatch cycle needs the ALU
// result muxed into these flops, which came out at 27.2 MHz against 34.3, for
// 52 more cells.  Charging those forms a second cycle instead costs 6 to 11 per
// cent of executed instructions one cycle each - measured over every
// gcc.c-torture binary - and buys the other 89 to 94 per cent a third more
// clock.  Whole programs run about 1.44 times faster at every optimisation
// level.
//
// PREDECODE MUST BE KEPT OUT OF BLOCK RAM, and was not at first: a table feeding
// flops that load together is a synchronous ROM, synthesis inferred one, and
// the selects then came out of a block RAM's slow clock-to-out at a fixed place
// on the die - a twentieth of the clock.  rtl/predecode.sv now says so with an
// attribute.
//
// THE SLOW UNARY PAIR HAD BEEN SETTING THE CLOCK.  Registering clz and
// popcount's result, and giving those two instructions an extra cycle through
// rtl/ucode.sv's SLOW step, took the processor from 21.9 to 23.7 MHz - against
// 23.8 with the unary block removed altogether, so nearly all of that gain,
// keeping every operation, for 25 LUTs.  The ROM now spans two block RAMs, since
// SLOW is a new word and the contents stopped collapsing into one.
//
// THE MICROCODE ROM IS STILL NOT ON THE CRITICAL PATH.  In LUTs it was 34 more
// cells and the same clock.  The critical path starts at rtl/insn.sv's fields or
// predecode's rhs source and runs through the operand selects and the ALU to
// the result, and routing is two thirds of it: 29 ns of wire against 13 of
// logic.
// =============================================================================

module cpu (
    input  logic        clk,
    input  logic        rst,
    output logic [15:0] mem_addr,    // -> memory: sampled at the clock edge
    input  logic [7:0]  mem_rdata,   // <- the byte at the address sampled last edge
    output logic        halted,
    output logic        trapped,
    output logic [15:0] result       // the ALU's output, observable until stores give the
                                     // datapath an output of its own
);

    // --- sequencing -----------------------------------------------------------
    // `defer` is the one thing the microcode cannot know for itself: a taken
    // branch's target is not on the bus yet, so the step that loads the pc must
    // not dispatch, and the ROM follows its `next` into a waiting step instead.
    wire fetch, dispatch, wen;
    wire [1:0] pcload;
    wire defer;
    ucode u (.clk(clk), .rst(rst), .bus(mem_rdata), .defer(defer), .fetch(fetch),
             .dispatch(dispatch), .wen(wen), .pcload(pcload),
             .halt(halted), .trap(trapped));

    logic [15:0] pc;
    wire [15:0] pc_next = pc + 16'd1;

    // --- the instruction ------------------------------------------------------
    wire [23:0] q, view;
    insn i (.clk(clk), .bus(mem_rdata), .fetch(fetch), .dispatch(dispatch), .q(q), .view(view));

    wire [3:0] alu_op, lhs_src, rhs_src, dest_src;
    wire [1:0] cond_src;
    wire [1:0] pc_src;
    predecode p (.clk(clk), .bus(mem_rdata), .dispatch(dispatch), .alu_op(alu_op),
                 .lhs_src(lhs_src), .rhs_src(rhs_src), .dest_src(dest_src),
                 .cond_src(cond_src), .pc_src(pc_src));

    // --- the pc's adder, and what it is adding this cycle -----------------------
    // One adder prepares the relative branch target: pc + the displacement byte
    // + 1, with the carry in standing for that + 1 rather than a second adder
    // chained behind the first.
    //
    // IT IS IDLE DURING EVERY CALL - an absolute call's target is the
    // instruction's own bytes and a register call's is the operand flop - so a
    // call borrows it, with the addend forced to 1.
    //
    // THAT IS TRUE ONLY BECAUSE THERE IS NO RELATIVE CALL.  A callr would want
    // this adder for its target and the same adder for its return address in
    // the same cycle, and one of the two would need an adder of its own.  The
    // wide relative transfers were taken out because a linker and no ASLR made
    // them pointless; this is the second thing that bought.  tools/gen-predecode.js
    // refuses a row that asks for both, so a relative call cannot come back
    // without that refusal being dealt with first.
    //
    // The sum is then pc + 2,
    // which is the address after a two- or three-byte call and so is what lr
    // must hold.  rtl/rhs.sv takes it as a right-hand side under code 2,
    // and the pass-through carries it to the register file, so the write port
    // needs no mux of its own.  The mux it used to need was worth 3.3 MHz.
    wire [15:0] off    = {{8{mem_rdata[7]}}, mem_rdata};
    wire        retadr = (rhs_src == 4'd2);
    wire [15:0] addend = retadr ? 16'd1 : off;
    wire [15:0] pcsum  = pc + addend + 16'd1;

    // --- the datapath, with the operands read a cycle early ---------------------
    (* ram_style = "logic" *)
    logic [15:0] R [0:7];

    wire [2:0]  an, bn, wn;
    wire [15:0] bval, y;
    lhs  l (.insn(view), .src(lhs_src), .regnum(an));
    rhs  r (.insn(view), .src(rhs_src), .regval(R[bn]), .pcsum(pcsum),
            .regnum(bn), .value(bval));

    // Both ALU inputs, as of the last edge.  The cycle that fills them is the
    // instruction's last fetch - or, for a one-byte form with no byte to fetch,
    // the entry cycle rtl/ucode.sv gives it instead - so what the ALU reads is
    // a cycle old and the register file has already taken the previous
    // instruction's write.
    logic [15:0] aq, bq;
    always_ff @(posedge clk) begin
        aq <= R[an];
        bq <= bval;
    end

    alu  a (.clk(clk), .lhs(aq), .rhs(bq), .op(alu_op), .y(y));
    dest d (.insn(q), .src(dest_src), .regnum(wn));

    // --- the condition, decided a cycle before it is used ----------------------
    wire [2:0] ccode; wire cneg, cmask, taken;
    cond    cu (.insn(q), .src(cond_src), .code(ccode), .neg(cneg), .mask(cmask));
    compare cp (.lhs(aq), .rhs(bq), .cond(ccode), .neg(cneg), .mask(cmask), .taken(taken));
    logic taken_q;
    always_ff @(posedge clk) taken_q <= taken;

    // --- the branch target, in the cycle its last byte arrives -----------------
    // The adder above prepared it: a displacement is always the instruction's
    // LAST byte, so the sum is relatched at every fetch and the one that
    // matters is the last.  A call's cycles latch pc + 2 here instead, and no
    // call ever reads it - its target is the instruction's bytes or the
    // operand flop.
    logic [15:0] tgt;
    always_ff @(posedge clk) tgt <= pcsum;

    // --- which address the next cycle reads ------------------------------------
    // Every candidate settled at an earlier edge or is wiring, so this is a mux
    // and nothing else: the incrementer, the target adder's flop, the
    // instruction's own bytes, and the right-hand operand.  `pcload` says
    // whether this step loads the pc and whether the verdict decides it.
    wire [15:0] wide = view[23:8];          // a wide target, as its last byte lands
    wire taking = pcload[0] | (pcload[1] & taken_q);
    assign defer = taking;
    wire [15:0] seq = (fetch | dispatch) ? pc_next : pc;
    always_comb begin
        if (rst)          mem_addr = 16'd0;
        else if (!taking) mem_addr = seq;
        else case (pc_src)
            2'd2:         mem_addr = wide;         // the wide target, as it arrives
            2'd3:         mem_addr = aq;           // a register: ret, jmp ra, call ra
            default:      mem_addr = tgt;          // the relative target
        endcase
    end
    always_ff @(posedge clk) pc <= mem_addr;

    // --- the register file's write ---------------------------------------------
    // Straight out of the ALU, with nothing in front of it.  A call's return
    // address is an ALU result like any other: rtl/rhs.sv hands it the pc
    // adder's sum and rtl/alu.sv's pass-through carries it here.  The mux that
    // used to sit here was worth 3.3 MHz - 29.67 against 32.95, medians of
    // eight seeds - because it was at the end of the path every instruction
    // takes, not just the calls that needed it.
    always_ff @(posedge clk) if (wen) R[wn] <= y;
    assign result = y;

endmodule
