// =============================================================================
// cpu.sv - the processor, as far as it goes
// =============================================================================
//
// GENERATED by tools/gen-cpu.js.  Do not edit; edit the generator and run
// `npm run rtl`.
//
// What runs: whatever rtl/ucode.sv implements - today every instruction whose
// effect is one ALU result written to one register, and halt and nop.  No
// memory writes, no branches, no pc loads yet, so the pc only counts.
//
// MEMORY IS OUTSIDE, as a synchronous read: `mem_addr` is sampled at the clock
// edge and the byte at that address is on `mem_rdata` for the following cycle.
// That is the UP5K's SPRAM and the 6502-like bus the cost model describes: one
// cycle per byte.
//
// THE pc IS THE ADDRESS OF THE BYTE ON THE BUS.  A step that consumes that byte
// - a fetch or a dispatch - presents pc + 1 at the edge that ends it, so the
// following byte arrives for the next step; one that consumes nothing presents
// pc again.  Reset presents 0, so the first word after it finds address 0's
// byte on the bus and dispatches it.
//
// `result` IS THE ALU'S OUTPUT, and it is a port only so that something outside
// can see the datapath: with no stores yet, the register file feeds only the
// ALU and the ALU only the register file, and a synthesis tool is entitled to
// remove a loop nothing observes.
//
// THE REGISTER FILE IS FLOPS AND MUXES, never block RAM: its two reads are
// asynchronous, which the part's block RAM is not.  The attribute says so,
// because the ROM beside it is block RAM and synthesis is left free to infer.
//
// MEASURED on an iCE40 UP5K, yosys 0.52 + nextpnr-ice40 0.7, behind a real
// SB_SPRAM256KA holding the program, logic cells and the median of eight
// placement seeds:
//
//                                                    LUT4   block RAMs   MHz
//     rtl/predecode.sv's table left to infer            858        3      20.9
//     microcode ROM in block RAM, predecode in LUTs     922        1      21.9
//     microcode ROM in LUTs as well                     956        0      22.0
//
// PREDECODE MUST BE KEPT OUT OF BLOCK RAM, and was not at first: a table feeding
// flops that load together is a synchronous ROM, synthesis inferred one, and
// the selects then came out of a block RAM's slow clock-to-out at a fixed place
// on the die - a twentieth of the clock.  rtl/predecode.sv now says so with an
// attribute.
//
// THE MICROCODE ROM IS NOT ON THE CRITICAL PATH YET.  In LUTs it is 34 more
// cells and the same clock, because the ALU instructions share so few distinct
// words that the ROM collapses to almost nothing as logic.  Block RAM will
// matter when the routines stop sharing.  The critical path starts at
// predecode's rhs source or rtl/insn.sv's fields and runs through the operand
// selects and the ALU to the result, and routing is two thirds of it: 30 to 33
// ns of wire against 14 of logic.
// =============================================================================

module cpu (
    input  logic        clk,
    input  logic        rst,
    output logic [15:0] mem_addr,    // -> memory: sampled at the clock edge
    input  logic [7:0]  mem_rdata,   // <- the byte at the address sampled last edge
    output logic        halted,
    output logic        trapped,
    output logic [15:0] result       // the ALU's output, observable until stores give the
                                     // datapath an output of its own
);

    // --- sequencing -----------------------------------------------------------
    wire fetch, dispatch, wen;
    ucode u (.clk(clk), .rst(rst), .bus(mem_rdata), .fetch(fetch), .dispatch(dispatch),
             .wen(wen), .halt(halted), .trap(trapped));

    logic [15:0] pc;
    assign mem_addr = rst ? 16'd0 : ((fetch | dispatch) ? pc + 16'd1 : pc);
    always_ff @(posedge clk) pc <= mem_addr;

    // --- the instruction ------------------------------------------------------
    wire [23:0] q, view;
    insn i (.clk(clk), .bus(mem_rdata), .fetch(fetch), .dispatch(dispatch), .q(q), .view(view));

    wire [3:0] alu_op, lhs_src, rhs_src, dest_src;
    wire [1:0] cond_src;
    predecode p (.clk(clk), .bus(mem_rdata), .dispatch(dispatch), .alu_op(alu_op),
                 .lhs_src(lhs_src), .rhs_src(rhs_src), .dest_src(dest_src), .cond_src(cond_src));

    // --- the datapath ---------------------------------------------------------
    (* ram_style = "logic" *)
    logic [15:0] R [0:7];

    wire [2:0]  an, bn, wn;
    wire [15:0] bval, y;
    lhs  l (.insn(q), .src(lhs_src), .regnum(an));
    rhs  r (.insn(q), .src(rhs_src), .regval(R[bn]), .regnum(bn), .value(bval));
    alu  a (.lhs(R[an]), .rhs(bval), .op(alu_op), .y(y));
    dest d (.insn(q), .src(dest_src), .regnum(wn));

    always_ff @(posedge clk) if (wen) R[wn] <= y;
    assign result = y;

endmodule
