// =============================================================================
// dest.sv - which register the write this cycle goes to
// =============================================================================
//
// GENERATED by tools/gen-dest.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run `npm run rtl`.
//
// The register file's write address, from ONE four-bit microcode field:
//
//    0..7   the register src[2:0], named by the microcode
//    8..11  a register number carried by the instruction, as below
//   12..15  reserved: they decode as 8..11, by src[1:0]
//
// Whether the file is written at all is a separate microcode line, which goes
// to the file and not through here.
//
// FOUND BY DECODING, every multi-byte form's written registers:
//
//    8  rd field      insn[10:8]
//             ld ld8 mov/reg_imm5 mov/reg_immbit5 mov/reg_immask5 bitrev sxt8
//             clz popcount add rsb xor or and shl asr lsr iseq isset pop (a)
//             ldm (a)
//    9  ra field      insn[13:11]
//             pop (b) ldm (b)
//   10  opcode field  insn[2:0]
//             mov/reg_imm16
//   11  port B field  {insn[15:14], insn[0]}
//             ldm (c) pop (c)
//
// ONE FIELD DOES NEARLY ALL OF IT.  Every ALU operation, load, mov and unary
// operation writes the rd field; the other three exist for two instructions.
// `mov rd, #imm16` spends opcode bits on its register because its two bytes are
// all immediate, and a three-register `pop` writes its second and third
// registers from where the ra and port-B fields sit.
//
// CODES 8 AND 9 MEAN WHAT THEY MEAN IN rtl/lhs.sv, so a step that reads a
// register from the instruction and writes it back names the same code twice.
//
// AND BIT 0 OF CODES 10 AND 11 IS THE SAME WIRE.  The opcode field is insn[2:0]
// and the port-B field is {insn[15:14], insn[0]}, so their low bits are both
// insn[0].  Four fields cost three inputs at bit 0, not four.
//
// THE REGISTERS THE MICROCODE NAMES are the one-byte forms' pinned destinations
// and the two registers the stack and calls write:
//
//     r0        ld/implicit, ld8/implicit, add/inc_r0, add/dec_r0,
//               add/inc2_r0, or/mov_r0_r1, mov/r0_zero, xor/r0_not,
//               add/r0_r0_r1
//     r1        add/r1_r1_r0, or/mov_r1_r0, stm
//     r2        ldm
//     sp (r6)   push, pop
//     lr (r7)   call
//
// MEASURED on an iCE40 UP5K, yosys 0.52 -nobram + nextpnr-ice40 0.7: an 8x16
// register file written at this block's address, logic cells and the median of
// five placement seeds, against the same file addressed by three microcode bits
// alone:
//
//                              write -> file        add -> write -> file
//     microcode bits only      291   76.4 MHz       307   66.1 MHz
//     THIS FILE                319   52.1           337   45.9
//
// THE WRITE ADDRESS IS A REAL PATH, and this block lengthens it by a third of
// the clock.  Both critical paths end at a global buffer on a register's clock
// enable: the address is decoded into eight enables, each fanning out to sixteen
// flops, and nextpnr puts those nets on globals.  The field mux adds two LUT
// levels in front of that decode - the critical path goes from two cells to
// four.
//
// IT IS NOT THE SLOWEST PATH YET.  Reading a register through rtl/lhs.sv or
// rtl/rhs.sv and adding measured 37 to 45 MHz, below both numbers here.  But it
// is the next one, and the cure is the one rtl/insn.sv already measured for
// port addresses: the instruction's fields do not move, so this block's output
// can be registered a cycle before the write, at the price of the microcode
// naming the destination one step early.
// =============================================================================

module dest (
    input  logic [23:0] insn,    // the instruction, byte 0 low: rtl/insn.sv
    input  logic [3:0]  src,     // microcode: where the written register comes from
    output logic [2:0]  regnum   // -> register file write address
);

    // src[1:0] picks the field: 8 rd, 9 ra, 10 the opcode's register, 11 port B's.
    wire [2:0] field = src[1] ? (src[0] ? {insn[15:14], insn[0]} : insn[2:0])
                              : (src[0] ? insn[13:11]            : insn[10:8]);

    assign regnum = src[3] ? field : src[2:0];

endmodule
