// =============================================================================
// immgen.sv - the immediate right-hand side
// =============================================================================
//
// GENERATED by tools/gen-immgen.js from isa/fructus.toml.  Do not edit; edit
// the spec and regenerate with `npm run rtl`.
//
// One combinational block serving 58 opcodes: every ALU and shift group, mov,
// the load and store displacements, and brclear/brset.  Its inputs are the
// instruction register and one microcode line, cimm.  NOTHING ELSE - no width
// bit, no shift bit, no opcode decode.  Five properties of the encoding make
// that possible.
//
// 1. THE COLUMN IS THE MODE.  Every instruction with an immediate puts it in
//    the same column of the opcode map, so opcode[2:0] alone says which of the
//    five immediate modes to produce:
//
//      +0  imm5      signed -16..15, and the tied load displacement
//      +1  immbit5   32 single-bit masks
//      +2  imm3      the small-constant table  (+3 is its second opcode)
//      +4  imm10     signed, spanning two bytes
//      +5  immask5   32 field and stripe masks
//      +6, +7              the three-operand forms: NO IMMEDIATE, x
//
//    and `cimm` selects a sixth mode at +0, for the packed branch alone.
//
// 2. +6 AND +7 ARE DELIBERATELY UNDEFINED.  Everything there takes its
//    right-hand side from a register, and rtl/rhs.sv gets that register's
//    number straight off the instruction bytes rather than from here - so this
//    block computing it too would be a second copy of the same three wires,
//    free to drift from the first.
//
//    Driving x rather than a tidy zero is the point: an x reaching the ALU says
//    the microcode asked for an immediate from an instruction that has none,
//    which is a bug, and it should be loud in simulation rather than quietly
//    plausible.  0x88..0x8f make that concrete - they are `mov rd, #imm16`,
//    where opcode[2:0] is the DESTINATION REGISTER and not a mode selector at
//    all, so this block's output there is meaningless for a third reason again.
//    rtl/rhs.sv gives that instruction its value directly, as code 4.
//
// 3. opcode[0] IS sel[0].  The imm3 index is {byte1[7:6], opcode[0]} - the spec
//    spells this `imm3[0]`, so the pair of opcodes at +2 and +3 ARE the low
//    index bit.  It is already an input; the index costs no logic.
//
// 4. THE TWO 5-BIT TABLES SHARE THEIR COMPLEMENT HALF.  For both immbit5 and
//    immask5 the upper sixteen entries are exact bitwise complements of the
//    lower sixteen - asserted by the generator, not assumed - and sel[2] is
//    what distinguishes the two (+1 against +5).  So the sixteen-entry halves
//    are chosen first and the complement XOR is applied once, not twice.
//
// 5. imm3 AND shift3 ARE ONE TABLE.  They differ at index 0 alone, -1 against
//    15, and the shifter masks its right-hand side to four bits, so -1 IS 15 to
//    a shift.  shift3 is an assembler vocabulary - it exists to reject
//    `shl rd, ra, #-1` - and the datapath never needs to know about it.
//
// EVERY FIELD IS AT ONE POSITION FOR THE WHOLE INSTRUCTION.  rtl/insn.sv puts
// each byte at its place - byte 0 low - so what this block reads is:
//
//     sel                                 insn[2:0]
//     imm5, immbit5, immask5, condimm5    insn[15:11]
//     imm3 index                          {insn[15:14], insn[0]}
//     imm10                               insn[23:14]
//
// all of them slices, and none of them moving when a later byte arrives.
//
// THAT USED TO BE A CONTRACT ON THE MICROCODE.  This block once read a shifting
// immreg holding the newest two bytes, where byte 1 moved up as byte 2 came in.
// Any five-bit field had to be consumed before the third byte was fetched -
// brclear's mask test ahead of its displacement - and imm10's two halves sat at
// opposite ends of the register, though they are adjacent in the stream.
// Neither is true now: a mask can be read in any cycle of its instruction, and
// imm10 is the one slice invariant 4b in tools/check.js says it is.
//
// NEITHER br FORM RIDES THIS BLOCK.  The two-register branches are at +6 and
// +7, where there is no immediate; and the packed form at +0 reads five bits
// through condimm5, which fuses a condition with a constant rather than being a
// plain immediate.  The branch unit decodes that one for itself.
//
// WHY cimm IS A MICROCODE BIT AND NOT DECODED HERE.  immgen could work it out
// for itself - the packed branch is 0xa0 and 0xa8, so `(op & 0xf7) == 0xa0` -
// and that was the first design.  It is a seven-input function of the opcode
// REGISTER, so it lands two LUT levels in front of the mode mux, and measured
// in one harness against the other it costs a level and a quarter of the clock:
// 115 SB_LUT4 at four levels and 71 MHz, against 109 at three levels and 91.
// A registered microcode line arrives at level zero and the mux absorbs it.
//
// MEASURED on an iCE40 UP5K, yosys 0.52 + nextpnr-ice40 0.7: 111 SB_LUT4 for
// the block alone, and 87 MHz placed in a registered harness (three seeds:
// 86.9 / 86.7 / 73.0).
//
// MOVING TO THE 24-BIT REGISTER CHANGED NOTHING HERE, as a change of wiring
// should not.  One harness, -nobram, medians of five seeds: 132 SB_LUT4 and
// 85.1 MHz reading a shifting immreg, 130 and 83.4 reading insn.sv - the same
// two LUT levels, and a gap well inside what the seeds wander by.
//
// The byte 1 re-layout cost six LUT4 here, the one place it cost anything.
// Measured against the same tools, the old layout was 105 SB_LUT4 and
// 87.3 / 88.4 / 80.2 MHz: the same clock within placement noise, six fewer
// cells.
//
// The six have a specific cause.  Before, `i5` and `i10` shared their low
// five bits, so five bits of the mode mux below were free.  Now `i5[4:0]` is
// insn[15:11] and `i10[4:0]` is insn[18:14], which do not coincide, so those
// five bits need real muxing - one level wide rather than deep, which is why
// the clock holds.
//
// What it buys is in software: a decoder extracting a signed imm10 from a
// 16-bit load went from four instructions to one, and an imm5 from two to one,
// because every immediate is now a contiguous top-aligned slice of the
// instruction stream.  See invariants 4b and 4c in tools/check.js.
// =============================================================================

module immgen (
    input  logic [23:0] insn,   // the instruction, byte 0 low: rtl/insn.sv
    input  logic        cimm,   // microcode: read +0's five bits as condimm5
    output logic [15:0] imm
);

    wire [2:0] sel = insn[2:0];                     // the column

    // --- the two modes that are pure wiring ---------------------------------
    wire [15:0] i5  = {{11{insn[15]}}, insn[15:11]};   // +0  imm5, and off5
    // imm10 is byte 1's top two bits and all of byte 2: one slice.
    wire [15:0] i10 = {{6{insn[23]}}, insn[23:14]};    // +4  imm10

    // --- +2 / +3: imm3, which is also shift3 --------------------------------
    wire [2:0] k3 = {insn[15:14], insn[0]};
    logic [3:0] lo3;
    always_comb case (k3)
        3'd0: lo3 = 4'hf;
        3'd1: lo3 = 4'h0;
        3'd2: lo3 = 4'h1;
        3'd3: lo3 = 4'h2;
        3'd4: lo3 = 4'h3;
        3'd5: lo3 = 4'h4;
        3'd6: lo3 = 4'h6;
        3'd7: lo3 = 4'h8;
    endcase
    // Index 0 is the only entry whose top twelve bits are set: -1 for the ALU,
    // and 15 to a shifter, which masks.  One gate, not a second table.
    wire neg = (k3 == 3'd0);
    wire [15:0] i3v = {{12{neg}}, lo3};

    // --- +1 / +5: immbit5 and immask5, sharing one complement layer ---------
    wire [4:0] n5 = insn[15:11];
    wire [3:0] n4 = n5[3:0];
    logic [15:0] tbit, tmask;
    always_comb case (n4)
        4'd0: tbit = 16'h0001;
        4'd1: tbit = 16'h0002;
        4'd2: tbit = 16'h0004;
        4'd3: tbit = 16'h0008;
        4'd4: tbit = 16'h0010;
        4'd5: tbit = 16'h0020;
        4'd6: tbit = 16'h0040;
        4'd7: tbit = 16'h0080;
        4'd8: tbit = 16'h0100;
        4'd9: tbit = 16'h0200;
        4'd10: tbit = 16'h0400;
        4'd11: tbit = 16'h0800;
        4'd12: tbit = 16'h1000;
        4'd13: tbit = 16'h2000;
        4'd14: tbit = 16'h4000;
        4'd15: tbit = 16'h8000;
    endcase
    always_comb case (n4)
        4'd0: tmask = 16'hc000;
        4'd1: tmask = 16'h3000;
        4'd2: tmask = 16'h0c00;
        4'd3: tmask = 16'h0300;
        4'd4: tmask = 16'h00c0;
        4'd5: tmask = 16'h0030;
        4'd6: tmask = 16'h000c;
        4'd7: tmask = 16'h0003;
        4'd8: tmask = 16'hf000;
        4'd9: tmask = 16'h0f00;
        4'd10: tmask = 16'h00f0;
        4'd11: tmask = 16'h000f;
        4'd12: tmask = 16'hff00;
        4'd13: tmask = 16'hf0f0;
        4'd14: tmask = 16'hcccc;
        4'd15: tmask = 16'haaaa;
    endcase
    wire [15:0] tsel = (sel[2] ? tmask : tbit) ^ {16{insn[15]}};

    // --- +0 again, for the packed branch ------------------------------------
    // `br cond, ra, #imm5` puts a condimm5 index in the same five bits that
    // every other +0 form reads as a signed integer, so this is a whole table
    // rather than a reinterpretation of one.  It is 32 entries indexed directly,
    // and it is two LUT levels - the same depth as the mask tables beside it -
    // so it joins the mode mux rather than sitting in front of it.
    logic [15:0] ccon;
    always_comb case (n5)
        5'd0: ccon = 16'h0000;
        5'd1: ccon = 16'h0000;
        5'd2: ccon = 16'h0000;
        5'd3: ccon = 16'h0000;
        5'd4: ccon = 16'h0001;
        5'd5: ccon = 16'h0001;
        5'd6: ccon = 16'h0001;
        5'd7: ccon = 16'h0001;
        5'd8: ccon = 16'hffff;
        5'd9: ccon = 16'hffff;
        5'd10: ccon = 16'hffff;
        5'd11: ccon = 16'hffff;
        5'd12: ccon = 16'h0002;
        5'd13: ccon = 16'h0002;
        5'd14: ccon = 16'h0002;
        5'd15: ccon = 16'h0002;
        5'd16: ccon = 16'h0004;
        5'd17: ccon = 16'h0008;
        5'd18: ccon = 16'h7fff;
        5'd19: ccon = 16'h7ffe;
        5'd20: ccon = 16'h8001;
        5'd21: ccon = 16'h8002;
        5'd22: ccon = 16'h0002;
        5'd23: ccon = 16'h0002;
        5'd24: ccon = 16'h0003;
        5'd25: ccon = 16'h0004;
        5'd26: ccon = 16'h0004;
        5'd27: ccon = 16'h0006;
        5'd28: ccon = 16'h0008;
        5'd29: ccon = 16'h0008;
        5'd30: ccon = 16'h0100;
        5'd31: ccon = 16'h0100;
    endcase

    // --- the mode mux -------------------------------------------------------
    // +6 and +7 have no immediate; x rather than 0 both lets the mapper treat
    // them as don't-cares and makes a microcode misuse visible in simulation.
    //
    // cimm is ignored anywhere but +0.  Asserting it elsewhere is a microcode
    // bug, and folding it away rather than driving x there keeps the mux at one
    // level: the selector is four bits but only one of them ever splits a case.
    always_comb case ({cimm, sel})
        4'b1_000:             imm = ccon;
        4'b0_000:             imm = i5;
        4'b0_001, 4'b0_101,
        4'b1_001, 4'b1_101:   imm = tsel;
        4'b0_010, 4'b0_011,
        4'b1_010, 4'b1_011:   imm = i3v;
        4'b0_100, 4'b1_100:   imm = i10;
        default:              imm = 16'hxxxx;
    endcase

endmodule
