// =============================================================================
// insn.sv - the instruction register
// =============================================================================
//
// GENERATED by tools/gen-insn.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run `npm run rtl`.
//
// 3 bytes in 24 flops, each byte at its place in the instruction:
//
//     q[7:0]    byte 0, the opcode
//     q[15:8]   byte 1
//     q[23:16]  byte 2
//
// which is the little-endian stream register invariant 4b in tools/check.js is
// written for, so every operand field is one slice at one position:
//
//     sel, the column          q[2:0]
//     rd field / ra field      q[10:8] / q[13:11]
//     port B, imm3 index       {q[15:14], q[0]}
//     five-bit fields          q[15:11]
//     imm10                    q[23:14]
//     off8                     q[23:16]
//     imm16                    q[23:8]
//
// IT REPLACES AN OPCODE REGISTER AND A SHIFTING immreg, which held the same
// 24 bits but placed them relative to the NEWEST byte.  Byte 1 moved up when
// byte 2 arrived, so every consumer had to know which cycle it was in: immgen
// carried a rule that five-bit fields be read before the third fetch, imm10's
// halves sat at opposite ends of immreg, and rtl/lhs.sv needed a microcode line
// and a latch to hold its register choice across the shift.  Here a field is
// where it is from the cycle its byte arrives until the next dispatch.
//
// TWO MICROCODE LINES LOAD IT.  `dispatch` says the byte on the bus is an
// opcode: it goes to byte 0 and the counter restarts behind it.  `fetch` says
// it is the next byte of this instruction: it goes where the counter points.
// A fetch after byte 2 writes nothing, which is a microcode bug rather than
// a case.  Nothing is reset - the first step after reset dispatches - and the
// bytes past the end of a short instruction are left over from an earlier one,
// which nothing reads: immgen drives x for the columns that have no immediate.
//
// `view` IS THE REGISTER WITH THIS CYCLE'S BYTE ALREADY IN IT, for microcode
// that acts on a byte in the cycle it arrives rather than the one after.  Only
// bytes 1 and up are bypassed.  While an opcode is on the bus the running step
// belongs to the PREVIOUS instruction, which must still see its own byte 0; the
// new opcode reaches the microcode ROM's address directly, not through here.
//
// A FUTURE ICACHE REPLACES THIS FILE, not its consumers.  A cache line that
// delivers all 3 bytes at once is `view` with no counter and no bypass, and
// rtl/immgen.sv, rtl/rhs.sv and rtl/lhs.sv take a 24-bit instruction either way.
//
// WHERE THE WORK SITS IS THE DECISION, and `view` is what makes it one.
// MEASURED with a real SB_SPRAM256KA driving the bus into this register, lhs and
// rhs (with immgen) addressing an 8x16 register file, and the two values meeting
// in a 16-bit add, registered.  iCE40 UP5K, yosys 0.52 -nobram, nextpnr-ice40
// 0.7, logic cells and the median of five seeds:
//
//   A  execute the cycle after the last byte; lhs and rhs read q     625  38.1 MHz
//   B  execute in the cycle it arrives; they read view               603  30.1
//   C  register both port addresses from view, read the file from
//      those flops next cycle, rhs's value side from q               624  40.4
//
// B IS A FIFTH SLOWER, and the critical path says why: it starts at the SPRAM's
// DATAOUT, so the memory's clock-to-out now sits in front of the field muxes,
// the register file's read and the add.  A bypass into the combinational
// datapath costs the whole of that.
//
// C IS THE FASTEST, and not by much - the add dominates once the address comes
// from a flop.  What it spends is timing in the microcode rather than cells:
// the step that selects the registers must be valid in the cycle byte 1 is on
// the bus, a cycle before the step that uses them.  The bypass is cheap there
// because it feeds three flops, not the file.
// =============================================================================

module insn (
    input  logic        clk,
    input  logic [7:0]  bus,       // the byte on the data bus this cycle
    input  logic        fetch,     // microcode: it is the next byte of this instruction
    input  logic        dispatch,  // microcode: it is the opcode of the next one
    output logic [23:0] q,         // the instruction as stored
    output logic [23:0] view       // the same, with this cycle's byte already in place
);

    logic [1:0] n;                         // where the next fetched byte goes
    wire  [1:0] at   = dispatch ? 2'd0 : n;
    wire        load = fetch | dispatch;

    always_ff @(posedge clk)
        if (load) begin
            case (at)
            2'd0: q[7:0] <= bus;
            2'd1: q[15:8] <= bus;
            2'd2: q[23:16] <= bus;
            default: ;
            endcase
            n <= at + 2'd1;
        end

    assign view[7:0] = q[7:0];
    assign view[15:8] = (load & at == 2'd1) ? bus : q[15:8];
    assign view[23:16] = (load & at == 2'd2) ? bus : q[23:16];

endmodule
