// =============================================================================
// isa.svh - the facts about the instruction set that rtl/ writes by hand
// =============================================================================
//
// GENERATED by tools/gen-isa.js from isa/fructus.toml.  Do not edit.
//
// brk is opcode 0x00, and sp and lr are r6 and r7: rtl/cpu.sv relies on
// both, and tools/gen-isa.js checks them.
// =============================================================================

`ifndef FRUCTUS_ISA_SVH
`define FRUCTUS_ISA_SVH

// [cpu.vectors] brk: where brk and the interrupt line go.
`define FRUCTUS_VECTOR_BRK 16'hfff8

// The registers the exception routines and the block moves name.
`define FRUCTUS_REG_SP 3'd6
`define FRUCTUS_REG_LR 3'd7
`define FRUCTUS_REG_SPLR 2'd3   // sp and lr but for bit 0, which is 1 for lr

// The fast unary operations, by usel - the right-hand immediate's bits 2:1.
`define FRUCTUS_UNARY_FAST(usel, bitrev, clmul, sxt8) (~usel[0] ? clmul : usel[1] ? sxt8 : bitrev)

// The slow pair, clz and popcount: popcount when this is 1.
`define FRUCTUS_UNARY_POP(usel) (usel[1])

`endif
