// =============================================================================
// lhs.sv - which register the ALU's left-hand side reads this cycle
// =============================================================================
//
// GENERATED by tools/gen-lhs.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run `npm run rtl`.
//
// The address for register file port A, from ONE four-bit microcode field:
//
//    0..7   the register src[2:0], named by the microcode
//    8      byte1[2:0], the rd field
//    9      byte1[5:3], the ra field
//   10..15  reserved: they decode as 8 and 9 alternately, by src[0]
//
// EVERY REGISTER OPERAND IN THE ISA IS IN ONE OF THREE PLACES: byte1[2:0],
// byte1[5:3], or {byte1[7:6], opcode[0]}.  The third is port B's, and
// rtl/rhs.sv takes it; the other two are this block's.  The only exceptions are
// the one-byte forms, whose operands are all pinned, and `mov rd, #imm16`, whose
// register is in the opcode and is never read.
//
// FOUND BY DECODING, every multi-byte form whose left-hand side is a register
// from the instruction:
//
//   rd field  insn[10:8]
//             ld ld8 add rsb xor or and shl asr lsr iseq isset br brclear br8
//             brset call
//   ra field  insn[13:11]
//             st st8 ld ld8 bitrev sxt8 clz popcount add rsb xor or and shl
//             asr lsr iseq br br8
//
// THE COLUMN NEARLY DECIDES IT - +0, +1 and +5 are rd, the rest ra - and the
// exceptions, computed rather than remembered, are:
//
//     0xac  call/reg, column +4, rd field - a pc transfer, not an ALU operation
//
// So the choice is a microcode bit rather than a decode of opcode[2:0].  That
// is also the cheaper place for it on its own merits: a registered microcode
// line arrives at LUT level zero, which is the lesson rtl/immgen.sv's cimm
// measurement already paid for.
//
// THE REGISTERS THE MICROCODE NAMES are the one-byte forms' pinned left-hand
// sides and the stack pointer:
//
//     r0        ld/implicit, ld8/implicit, add/inc_r0, add/dec_r0,
//               add/inc2_r0, or/mov_r1_r0, xor/r0_not, add/r0_r0_r1
//     r1        add/r1_r1_r0, or/mov_r0_r1
//     sp (r6)   push, push8, pop, pop8
//
// `ret` and `jmp r5` are not here: they take their target on port B, through
// rhs.sv's lr and r5 codes.  Port A could carry them just as well - nothing
// below cares - which would put every pc-from-register transfer on one port.
//
// NOTHING IS HELD.  rtl/insn.sv puts byte 1 at insn[15:8] from the cycle it
// arrives until the next dispatch, so the fields do not move when byte 2 is
// fetched, and the imm10 forms read ra in the same cycle as their immediate.
//
// This file once sat on a shifting immreg, where byte 1 moved up as byte 2 came
// in, and it needed a microcode line and a transparent latch - a flop and a
// bypass - to keep its choice across the shift.  MEASURED, that version against
// this one, on an iCE40 UP5K, yosys 0.52 -nobram + nextpnr-ice40 0.7, beside a
// real 8x16 register file whose other port is idle; logic cells and the median
// of five placement seeds:
//
//                                     file read -> flop    read + add -> flop
//     latch on immreg                     362   58.5 MHz        341   39.8 MHz
//     THIS FILE, on insn.sv               316   64.0            332   44.8
//
// So the fixed register gives back what holding the choice cost: 46 cells and
// a tenth of the clock on the read, an eighth through the add.
//
// An address straight out of a flop is faster still, and with insn.sv it needs
// no new mechanism: register this block's output from insn.sv's `view`, which
// shows byte 1 in the cycle it is on the bus.  rtl/insn.sv's header measures
// that placement against the others.
//
// Two traps in measuring this, both of which produced plausible numbers first.
// A parity of the outputs let yosys push the XOR through the read mux and read
// one parity bit per register; and a file read followed by a flop is exactly a
// synchronous block RAM, which yosys inferred - the part cannot do that here,
// see docs/fpga-toolchain.md.  So the harness shifts its result out bit by bit
// and synthesises with -nobram.
// =============================================================================

module lhs (
    input  logic [23:0] insn,    // the instruction, byte 0 low: rtl/insn.sv
    input  logic [3:0]  src,     // microcode: where the left-hand register comes from
    output logic [2:0]  regnum   // -> register file port A address
);

    // src[0] picks the field and src[2:0] is the register, so the field choice
    // costs no decode: codes 8 and 9 differ in exactly the bit that selects.
    assign regnum = src[3] ? (src[0] ? insn[13:11] : insn[10:8]) : src[2:0];

endmodule
