// =============================================================================
// lhs.sv - which register the ALU's left-hand side reads this cycle
// =============================================================================
//
// GENERATED by tools/gen-lhs.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run `npm run rtl`.
//
// The address for register file port A, from ONE four-bit microcode field:
//
//    0..7   the register src[2:0], named by the microcode
//    8      byte1[2:0], the rd field
//    9      byte1[5:3], the ra field
//   10..15  reserved: they decode as 8 and 9 alternately, by src[0]
//
// and ONE microcode line, `latch`, that says whether that choice is made now or
// the previous one kept.
//
// EVERY REGISTER OPERAND IN THE ISA IS IN ONE OF THREE PLACES: byte1[2:0],
// byte1[5:3], or {byte1[7:6], opcode[0]}.  The third is port B's, and
// rtl/rhs.sv takes it; the other two are this block's.  The only exceptions are
// the one-byte forms, whose operands are all pinned, and `mov rd, #imm16`, whose
// register is in the opcode and is never read.
//
// FOUND BY DECODING, every multi-byte form whose left-hand side is a register
// from the instruction:
//
//   rd field  ir[2:0]
//             ld ld8 add rsb xor or and shl asr lsr iseq isset br brclear br8
//             brset call
//   ra field  ir[5:3]
//             st st8 ld ld8 sxt8 clz popcount zxt8 bitrev add rsb xor or and
//             shl asr lsr iseq br br8
//
// THE COLUMN NEARLY DECIDES IT - +0, +1 and +5 are rd, the rest ra - and the
// exceptions, computed rather than remembered, are:
//
//     0xac  call/reg, column +4, rd field - a pc transfer, not an ALU operation
//
// So the choice is a microcode bit rather than a decode of opcode[2:0].  That
// is also the cheaper place for it on its own merits: a registered microcode
// line arrives at LUT level zero, which is the lesson rtl/immgen.sv's cimm
// measurement already paid for.
//
// THE REGISTERS THE MICROCODE NAMES are the one-byte forms' pinned left-hand
// sides and the stack pointer:
//
//     r0        ld/implicit, ld8/implicit, add/inc_r0, add/dec_r0,
//               add/inc2_r0, or/mov_r1_r0, xor/r0_not, add/r0_r0_r1
//     r1        add/r1_r1_r0, or/mov_r0_r1
//     sp (r6)   push, push8, pop, pop8
//
// `ret` and `jmp r5` are not here: they take their target on port B, through
// rhs.sv's lr and r5 codes.  Port A could carry them just as well - nothing
// below cares - which would put every pc-from-register transfer on one port.
//
// WHY THE LATCH.  immreg is a shift register, so fetching a third byte moves
// byte 1 up into the high half, and the fields are no longer at ir[5:3] and
// ir[2:0].  The imm10 forms need their register in the SAME cycle as the
// immediate, which is after that shift.  So the microcode opens the latch in
// the step where byte 1 is still low, and closes it for the step after byte 2
// arrives; the register NUMBER is held, and the file delivers the register's
// current value in whichever cycle reads it.  Nothing writes that register
// between the two cycles, so the number and the value are equivalent - for
// three flops rather than sixteen.
//
// IT IS TRANSPARENT WHILE OPEN, which is what makes it a latch rather than a
// register.  A two-byte instruction reads port A in the same cycle it chooses
// the register, so a plain clock-enabled flop would deliver the choice a cycle
// late.  On an iCE40 it is built as a flop and a bypass mux, not a latch
// primitive: level-sensitive storage is something nextpnr cannot time.
//
// `held` has no reset, deliberately.  The microcode opens the latch in the
// first step of every instruction that reads port A, so the flops are never
// read before they are written; an x in simulation says a step forgot to.
//
// MEASURED on an iCE40 UP5K, yosys 0.52 -nobram + nextpnr-ice40 0.7, beside a
// real 8x16 register file whose other port is idle, so port A is the only
// logic path.  Logic cells, and the median of three placement seeds:
//
//                                         file read -> flop    read + add -> flop
//     no latch: broken for imm10              295   64.6 MHz        329   43.4 MHz
//     flop + bypass - THIS FILE               349   57.6            348   38.7
//     "hold" as a src code, no latch line     351   57.9            349   40.6
//     no latch, a third field ir[13:11]       356   59.3            352   39.1
//     flop only, no bypass                    295   76.3            335   49.1
//
// THE THREE THAT WORK COST THE SAME, within the few MHz the seeds wander by:
// 55 to 60 cells on the read and about 20 through the add, and a tenth of the
// clock either way, over the broken baseline.  Holding
// the choice is no dearer than reaching for byte 1 where the shift left it,
// and it does not have to be taught to each consumer of a register field.
//
// THE LAST ROW IS THE ONE WORTH HAVING: an address straight out of a flop, a
// third faster than the bypass on the read and a quarter faster through the
// add.  It is not a drop-in - it presents the choice one cycle after the latch
// opens - so it needs the choice made in the cycle byte 1 is ON THE BUS rather
// than in immreg: the fields read off the incoming byte, the microcode's
// selection valid a cycle earlier.  Whether the microcode can be there in time
// is a question about the ROM, not about this block.
//
// Two traps in measuring this, both of which produced plausible numbers first.
// A parity of the outputs let yosys push the XOR through the read mux and read
// one parity bit per register; and a file read followed by a flop is exactly a
// synchronous block RAM, which yosys inferred - the part cannot do that here,
// see docs/fpga-toolchain.md.  So the harness shifts its result out bit by bit
// and synthesises with -nobram.
// =============================================================================

module lhs (
    input  logic        clk,
    input  logic [15:0] ir,      // immreg: the last two instruction bytes
    input  logic [3:0]  src,     // microcode: where the left-hand register comes from
    input  logic        latch,   // microcode: choose now, or keep the last choice
    output logic [2:0]  regnum   // -> register file port A address
);

    // src[0] picks the field and src[2:0] is the register, so the field choice
    // costs no decode: codes 8 and 9 differ in exactly the bit that selects.
    wire [2:0] pick = src[3] ? (src[0] ? ir[5:3] : ir[2:0]) : src[2:0];

    logic [2:0] held;
    always_ff @(posedge clk) if (latch) held <= pick;

    assign regnum = latch ? pick : held;

endmodule
