// =============================================================================
// predecode.sv - control that belongs to the whole instruction
// =============================================================================
//
// GENERATED by tools/gen-predecode.js from isa/fructus.toml.  Do not edit; edit
// the spec or tools/control.js and run `npm run rtl`.
//
// A table over the first byte, loaded into flops in the dispatch cycle - the
// same cycle, and the same `dispatch` line, that puts the opcode into
// rtl/insn.sv.  From the next cycle until the next dispatch its outputs come
// straight out of flops:
//
//     alu_op     rtl/alu.sv's operation
//     lhs_src    rtl/lhs.sv's source
//     rhs_src    rtl/rhs.sv's source
//     dest_src   rtl/dest.sv's source: the FIRST register the instruction writes
//     cond_src   rtl/cond.sv's source
//     pc_src     where rtl/cpu.sv's next address comes from
//
// 141 opcodes, one row each.  An x is a value no step of that instruction reads -
// a branch has no ALU operation, a store no destination - left to the mapper as
// a don't-care.  Rows with an x, per field: alu 26, lhs 17, rhs 4, dest 26, cond 134, pc 0.
//
// THE MICROCODE ROM KEEPS WHAT CHANGES FROM STEP TO STEP: write enables,
// fetch and dispatch, the pc, memory reads and writes, the next address.  What
// is here is what an instruction wants throughout, and a value only has to be
// harmless in a step that does not use it - the ALU operation can sit on the
// ALU through a fetch, because nothing is written.
//
// A STEP THAT NEEDS SOMETHING ELSE SAYS SO.  pop's second and third registers,
// the store after push's decrement: those steps take their select from the
// microcode word instead, which is the consumer's two-way choice and not this
// block's business.
//
// WHY DECODE AT DISPATCH AND NOT FROM THE OPCODE REGISTER.  Each output is an
// eight-input function, so reading it off rtl/insn.sv's opcode byte during the
// instruction would put two LUT levels in front of everything it selects - the
// cimm measurement in rtl/immgen.sv priced exactly that at a level and a
// quarter of the clock.  Decoding the byte while it is on the bus puts those
// levels in the dispatch cycle, where they lead only to flops.
//
// IT IS STILL A TABLE, which is what isa/fructus.toml requires: nothing may
// decode an ALU operation by extracting bits from fixed positions, and nothing
// here does.  One opcode, one row, from the spec.
//
// MEASURED on an iCE40 UP5K, yosys 0.52 -nobram + nextpnr-ice40 0.7, logic
// cells and the median of eight placement seeds, with a real SB_SPRAM256KA on
// the bus:
//
//                                                  cells   critical path  MHz
//     SPRAM -> this table -> flops, alone            136   3 cells       71.8
//     the execute step, selects from this block     1127  11 cells       22.6
//     the execute step, selects from plain flops    1044  12 cells       22.2
//
// The execute step is rtl/insn.sv, rtl/lhs.sv, rtl/rhs.sv with immgen, rtl/cond.sv,
// an 8x16 register file, rtl/alu.sv, rtl/compare.sv and rtl/dest.sv, with the
// ALU's result written back.
//
// THE DISPATCH PATH IS NOT A CONSTRAINT: the table sits behind the memory's
// clock-to-out and still runs at three times the execute step's rate.  AND THE
// SELECTS COST THE STEP NOTHING against the idealised flops every earlier
// harness gave it - the critical path starts at the instruction register's
// fields, not at a select.  So the assumption those harnesses made about
// control arriving at level zero holds with a real table behind it, for 83
// cells.
// =============================================================================

module predecode (
    input  logic        clk,
    input  logic [7:0]  bus,       // the byte on the data bus this cycle
    input  logic        dispatch,  // microcode: it is an opcode - rtl/insn.sv's line too
    output logic [3:0]  alu_op,    // -> rtl/alu.sv
    output logic [3:0]  lhs_src,   // -> rtl/lhs.sv
    output logic [3:0]  rhs_src,   // -> rtl/rhs.sv
    output logic [3:0]  dest_src,  // -> rtl/dest.sv
    output logic [1:0]  cond_src,  // -> rtl/cond.sv
    output logic [1:0]  pc_src     // -> rtl/cpu.sv's address mux
);

    // A table feeding flops that load together is exactly a synchronous ROM,
    // and synthesis will put it in block RAM - with the slow clock-to-out and
    // fixed placement this block exists to avoid.  The attribute keeps it in
    // LUTs, and it has to sit on the case statement itself: yosys ignores it on
    // the always block, on t, and on the flops, and (* keep *) on t does not
    // stop the inference either.  Inside begin/end is where iverilog accepts it.
    logic [19:0] t;             // {alu, lhs, rhs, dest, cond}
    always_comb begin
        (* rom_style = "logic" *)
        case (bus)
        8'h00: t = 20'bxxxx_xxxx_xxxx_xxxx_xx_00;    // halt
        8'h03: t = 20'b0111_0000_1000_0000_xx_00;    // ld
        8'h04: t = 20'b0111_0000_1000_0000_xx_00;    // ld8
        8'h05: t = 20'b0000_0000_1001_0000_xx_00;    // add
        8'h06: t = 20'b0000_0000_1111_0000_xx_00;    // add
        8'h07: t = 20'b0000_0000_1010_0000_xx_00;    // add
        8'h09: t = 20'bxxxx_1001_1011_xxxx_xx_00;    // st
        8'h0a: t = 20'bxxxx_1001_1011_xxxx_xx_00;    // st
        8'h0b: t = 20'bxxxx_1001_1011_xxxx_xx_00;    // st
        8'h0e: t = 20'bxxxx_1001_1101_xxxx_xx_00;    // st
        8'h0f: t = 20'bxxxx_1001_1101_xxxx_xx_00;    // st
        8'h11: t = 20'bxxxx_1001_1011_xxxx_xx_00;    // st8
        8'h12: t = 20'bxxxx_1001_1011_xxxx_xx_00;    // st8
        8'h13: t = 20'bxxxx_1001_1011_xxxx_xx_00;    // st8
        8'h16: t = 20'bxxxx_1001_1101_xxxx_xx_00;    // st8
        8'h17: t = 20'bxxxx_1001_1101_xxxx_xx_00;    // st8
        8'h18: t = 20'b0111_1000_1011_1000_xx_00;    // ld
        8'h19: t = 20'b0111_1001_1011_1000_xx_00;    // ld
        8'h1a: t = 20'b0111_1001_1011_1000_xx_00;    // ld
        8'h1b: t = 20'b0111_1001_1011_1000_xx_00;    // ld
        8'h1e: t = 20'b0111_1001_1101_1000_xx_00;    // ld
        8'h1f: t = 20'b0111_1001_1101_1000_xx_00;    // ld
        8'h20: t = 20'b0111_1000_1011_1000_xx_00;    // ld8
        8'h21: t = 20'b0111_1001_1011_1000_xx_00;    // ld8
        8'h22: t = 20'b0111_1001_1011_1000_xx_00;    // ld8
        8'h23: t = 20'b0111_1001_1011_1000_xx_00;    // ld8
        8'h26: t = 20'b0111_1001_1101_1000_xx_00;    // ld8
        8'h27: t = 20'b0111_1001_1101_1000_xx_00;    // ld8
        8'h28: t = 20'b0111_xxxx_1011_1000_xx_00;    // mov
        8'h2c: t = 20'b0111_xxxx_1011_1000_xx_00;    // mov
        8'h2d: t = 20'b0111_xxxx_1011_1000_xx_00;    // mov
        8'h32: t = 20'b1100_1001_1011_1000_xx_00;    // bitrev sxt8
        8'h33: t = 20'b1101_1001_1011_1000_xx_00;    // clz popcount
        8'h38: t = 20'b0000_1000_1011_1000_xx_00;    // add
        8'h39: t = 20'b0000_1001_1011_1000_xx_00;    // add
        8'h3a: t = 20'b0000_1001_1011_1000_xx_00;    // add
        8'h3b: t = 20'b0000_1001_1011_1000_xx_00;    // add
        8'h3c: t = 20'b0000_1000_1011_1000_xx_00;    // add
        8'h3d: t = 20'b0000_1000_1011_1000_xx_00;    // add
        8'h3e: t = 20'b0000_1001_1101_1000_xx_00;    // add
        8'h3f: t = 20'b0000_1001_1101_1000_xx_00;    // add
        8'h40: t = 20'b0001_1000_1011_1000_xx_00;    // rsb
        8'h41: t = 20'b0001_1001_1011_1000_xx_00;    // rsb
        8'h42: t = 20'b0001_1001_1011_1000_xx_00;    // rsb
        8'h43: t = 20'b0001_1001_1011_1000_xx_00;    // rsb
        8'h46: t = 20'b0001_1001_1101_1000_xx_00;    // rsb
        8'h47: t = 20'b0001_1001_1101_1000_xx_00;    // rsb
        8'h48: t = 20'b0100_1000_1011_1000_xx_00;    // xor
        8'h49: t = 20'b0100_1001_1011_1000_xx_00;    // xor
        8'h4a: t = 20'b0100_1001_1011_1000_xx_00;    // xor
        8'h4b: t = 20'b0100_1001_1011_1000_xx_00;    // xor
        8'h4c: t = 20'b0100_1000_1011_1000_xx_00;    // xor
        8'h4d: t = 20'b0100_1000_1011_1000_xx_00;    // xor
        8'h4e: t = 20'b0100_1001_1101_1000_xx_00;    // xor
        8'h4f: t = 20'b0100_1001_1101_1000_xx_00;    // xor
        8'h50: t = 20'b0101_1000_1011_1000_xx_00;    // or
        8'h51: t = 20'b0101_1001_1011_1000_xx_00;    // or
        8'h52: t = 20'b0101_1001_1011_1000_xx_00;    // or
        8'h53: t = 20'b0101_1001_1011_1000_xx_00;    // or
        8'h54: t = 20'b0101_1000_1011_1000_xx_00;    // or
        8'h55: t = 20'b0101_1000_1011_1000_xx_00;    // or
        8'h56: t = 20'b0101_1001_1101_1000_xx_00;    // or
        8'h57: t = 20'b0101_1001_1101_1000_xx_00;    // or
        8'h58: t = 20'b0110_1000_1011_1000_xx_00;    // and
        8'h59: t = 20'b0110_1001_1011_1000_xx_00;    // and
        8'h5a: t = 20'b0110_1001_1011_1000_xx_00;    // and
        8'h5b: t = 20'b0110_1001_1011_1000_xx_00;    // and
        8'h5c: t = 20'b0110_1000_1011_1000_xx_00;    // and
        8'h5d: t = 20'b0110_1000_1011_1000_xx_00;    // and
        8'h5e: t = 20'b0110_1001_1101_1000_xx_00;    // and
        8'h5f: t = 20'b0110_1001_1101_1000_xx_00;    // and
        8'h60: t = 20'b1000_1000_1011_1000_xx_00;    // shl
        8'h62: t = 20'b1000_1001_1011_1000_xx_00;    // shl
        8'h63: t = 20'b1000_1001_1011_1000_xx_00;    // shl
        8'h66: t = 20'b1000_1001_1101_1000_xx_00;    // shl
        8'h67: t = 20'b1000_1001_1101_1000_xx_00;    // shl
        8'h68: t = 20'b1011_1000_1011_1000_xx_00;    // asr
        8'h6a: t = 20'b1011_1001_1011_1000_xx_00;    // asr
        8'h6b: t = 20'b1011_1001_1011_1000_xx_00;    // asr
        8'h6e: t = 20'b1011_1001_1101_1000_xx_00;    // asr
        8'h6f: t = 20'b1011_1001_1101_1000_xx_00;    // asr
        8'h70: t = 20'b1001_1000_1011_1000_xx_00;    // lsr
        8'h72: t = 20'b1001_1001_1011_1000_xx_00;    // lsr
        8'h73: t = 20'b1001_1001_1011_1000_xx_00;    // lsr
        8'h76: t = 20'b1001_1001_1101_1000_xx_00;    // lsr
        8'h77: t = 20'b1001_1001_1101_1000_xx_00;    // lsr
        8'h78: t = 20'b0010_1000_1011_1000_xx_00;    // iseq
        8'h79: t = 20'b0010_1001_1011_1000_xx_00;    // iseq
        8'h7a: t = 20'b0010_1001_1011_1000_xx_00;    // iseq
        8'h7b: t = 20'b0010_1001_1011_1000_xx_00;    // iseq
        8'h7c: t = 20'b0011_1000_1011_1000_xx_00;    // isset
        8'h7d: t = 20'b0011_1000_1011_1000_xx_00;    // isset
        8'h7e: t = 20'b0010_1001_1101_1000_xx_00;    // iseq
        8'h7f: t = 20'b0010_1001_1101_1000_xx_00;    // iseq
        8'h80: t = 20'b0000_0001_0000_0001_xx_00;    // add
        8'h81: t = 20'b0101_0001_1000_0000_xx_00;    // or
        8'h82: t = 20'b0101_0000_1000_0001_xx_00;    // or
        8'h83: t = 20'b0111_xxxx_1000_0000_xx_00;    // mov
        8'h84: t = 20'b0100_0000_1001_0000_xx_00;    // xor
        8'h85: t = 20'b0000_0000_0001_0000_xx_00;    // add
        8'h87: t = 20'bxxxx_xxxx_xxxx_xxxx_xx_00;    // nop
        8'h88: t = 20'b0111_xxxx_0100_1010_xx_00;    // mov
        8'h89: t = 20'b0111_xxxx_0100_1010_xx_00;    // mov
        8'h8a: t = 20'b0111_xxxx_0100_1010_xx_00;    // mov
        8'h8b: t = 20'b0111_xxxx_0100_1010_xx_00;    // mov
        8'h8c: t = 20'b0111_xxxx_0100_1010_xx_00;    // mov
        8'h8d: t = 20'b0111_xxxx_0100_1010_xx_00;    // mov
        8'h8e: t = 20'b0111_xxxx_0100_1010_xx_00;    // mov
        8'h8f: t = 20'b0111_xxxx_0100_1010_xx_00;    // mov
        8'h90: t = 20'b0111_0110_0011_0110_xx_00;    // push
        8'h91: t = 20'b0111_0001_0011_0001_xx_00;    // stm
        8'h92: t = 20'b0111_0110_0011_0110_xx_00;    // push
        8'h93: t = 20'b0111_0001_0011_0001_xx_00;    // stm
        8'h94: t = 20'b0111_0001_0011_0001_xx_00;    // stm
        8'h95: t = 20'b0111_0001_0011_0001_xx_00;    // stm
        8'h96: t = 20'b0111_0110_0011_0110_xx_00;    // push
        8'h97: t = 20'b0111_0110_0011_0110_xx_00;    // push
        8'h98: t = 20'b0111_0110_0011_0110_xx_00;    // pop
        8'h99: t = 20'b0111_0010_0011_0010_xx_00;    // ldm
        8'h9a: t = 20'b0111_0110_0011_0110_xx_00;    // pop
        8'h9b: t = 20'b0111_0010_0011_0010_xx_00;    // ldm
        8'h9c: t = 20'b0111_0010_0011_0010_xx_00;    // ldm
        8'h9d: t = 20'b0111_0010_0011_0010_xx_00;    // ldm
        8'h9e: t = 20'b0111_0110_0011_0110_xx_00;    // pop
        8'h9f: t = 20'b0111_0110_0011_0110_xx_00;    // pop
        8'ha0: t = 20'bxxxx_1000_1100_xxxx_01_01;    // br
        8'ha1: t = 20'bxxxx_1000_xxxx_xxxx_xx_11;    // jmp
        8'ha2: t = 20'bxxxx_xxxx_xxxx_xxxx_xx_10;    // jmp
        8'ha3: t = 20'bxxxx_xxxx_1011_xxxx_xx_01;    // jmpr
        8'ha4: t = 20'bxxxx_1000_1011_xxxx_10_01;    // brclear
        8'ha5: t = 20'bxxxx_1000_1011_xxxx_10_01;    // brclear
        8'ha6: t = 20'bxxxx_1001_1101_xxxx_00_01;    // br
        8'ha7: t = 20'bxxxx_1001_1101_xxxx_00_01;    // br
        8'ha8: t = 20'bxxxx_1000_1011_xxxx_xx_01;    // br8
        8'ha9: t = 20'b0111_1000_0010_0111_xx_11;    // call
        8'haa: t = 20'b0111_xxxx_0010_0111_xx_10;    // call
        8'hab: t = 20'bxxxx_0111_0111_xxxx_xx_11;    // ret
        8'hac: t = 20'bxxxx_1000_1011_xxxx_11_01;    // brset
        8'had: t = 20'bxxxx_1000_1011_xxxx_11_01;    // brset
        8'hae: t = 20'bxxxx_1001_1011_xxxx_xx_01;    // br8
        8'haf: t = 20'bxxxx_1001_1011_xxxx_xx_01;    // br8
        default: t = 20'bxxxxxxxxxxxxxxxxxxxx;
        endcase
    end

    always_ff @(posedge clk)
        if (dispatch) {alu_op, lhs_src, rhs_src, dest_src, cond_src, pc_src} <= t;

endmodule
