// =============================================================================
// ucode.sv - the microcode ROM and its sequencer
// =============================================================================
//
// GENERATED by tools/gen-ucode.js from isa/fructus.toml.  Do not edit; edit the
// spec, tools/control.js or the generator and run `npm run rtl`.
//
// A 512-word ROM of 17-bit words, read synchronously - an iCE40 block RAM,
// initialised from the bitstream.  Its address is the opcode on the bus in a
// step that dispatches, and the word's `next` otherwise.  The word:
//
//     next       9  the address of the following step, unless this one dispatches
//     fetch      1  the byte on the bus is the next byte of this instruction
//     dispatch   1  the byte on the bus is the next opcode: it addresses the ROM
//     wen        1  write the ALU result to the register rtl/dest.sv names
//     halt       1  stopped: the step repeats and consumes nothing
//     trap       1  an opcode this ROM does not implement yet
//     pcload     2  load the pc: 1 always, 2 if the branch is taken
//     lrwrite    1  the register file takes the return address, not the ALU
//
// The first 256 words are the entry points, one per opcode; the shared steps
// sit above them:
//
//     256  EXEC    000000000_0_1_1_0_0_00_0  write the result; the next opcode is on the bus
//     257  FETCH2  100000000_1_0_0_0_0_00_0  fetch byte 2
//     258  HALT    100000010_0_0_0_1_0_00_0  stay here
//     259  TRAP    100000011_0_0_0_0_1_00_0  stay here, flagged
//     260  BOOT    000000000_0_1_0_0_0_00_0  after reset: the first opcode is on the bus
//     261  SLOW    100000000_0_0_0_0_0_00_0  wait: rtl/unary.sv registers the slow pair
//     262  BRF2    100000111_1_0_0_0_0_00_0  a branch's displacement
//     263  BRDO    100001011_0_1_0_0_0_10_0  take it, or dispatch what is already on the bus
//     264  JF2     100001011_1_0_0_0_0_01_0  a wide target's second byte, and load it at once
//     265  JCF2    100001011_1_0_1_0_0_01_1  the same, and lr takes the return address
//     266  JRDO    100001011_0_1_0_0_0_01_0  load a relative target; it is always taken
//     267  PCDISP  000000000_0_1_0_0_0_00_0  the target is on the bus now
//
// THE ALU INSTRUCTIONS NEED ALMOST NOTHING HERE, because rtl/predecode.sv has
// already decided their operation and every source.  One cycle per byte:
//
//     cycle   bus             word                  does
//       1     opcode          the previous EXEC     address the ROM with the bus
//       2     byte 1          entry: fetch          byte 1 into rtl/insn.sv
//      (3     byte 2          FETCH2: fetch         three-byte forms only)
//       3     next opcode     EXEC: wen, dispatch   write the result, dispatch
//
// An instruction that declares `extra_cycles` in the spec - clz and popcount,
// whose result rtl/unary.sv registers - enters through SLOW instead of going
// straight to EXEC: a step that consumes nothing, so the next opcode waits on
// the bus while the register fills.
//
// A ONE-BYTE FORM'S ENTRY WORD FETCHES NOTHING, and that is what makes
// rtl/cpu.sv's early operand read possible.  Every other instruction's entry
// word fetches byte 1, and rtl/cpu.sv reads the operands in that same cycle; a
// one-byte form has no byte to fetch, but its operands are all pinned - a
// register the microcode names, or one of rtl/rhs.sv's constants - so the cycle
// is spent reading them and nothing else.  Two cycles rather than one, and in
// exchange no instruction executes in the cycle it was dispatched in, so
// nothing anywhere needs a forwarding path.
//
// So every two-byte ALU opcode has the same entry word, and so does every
// three-byte one - the ALU operations share not only their successor but
// their whole routine.  The write and the next dispatch share a cycle, and
// nothing conflicts: the write uses the instruction already in rtl/insn.sv and
// rtl/predecode.sv, and the new opcode goes in at the edge that ends it.
//
// ENTRY POINTS, by what the spec says each opcode does:
//
//     one-byte ALU - its entry word fetches nothing, and that cycle is the one
//     the operands are read in:
//         add or mov xor
//     two-byte ALU:
//         mov bitrev sxt8 add rsb xor or and shl asr lsr iseq isset
//     two-byte ALU with a registered result, one extra cycle through SLOW:
//         clz popcount
//     three-byte ALU:
//         add rsb xor or and iseq mov
//     conditional branches - fetch both bytes, then take or dispatch:
//         br brclear brset
//     the short relative jump, a byte of displacement:
//         jmpr
//     wide targets, absolute, with and without a link:
//         jmp
//         call
//     halt:
//         halt
//     nop - its entry dispatches at once, since the next opcode is already on
//     the bus:
//         nop
//     trap - 161 opcodes, every one not yet implemented and every free one.
//
// RESET forces the address to BOOT for as long as it is held, so the first
// word after it dispatches the byte at address 0.  The ROM's output register
// cannot be reset on the part; forcing the address instead needs no reset on
// the block RAM at all.
//
// MEASURED - see rtl/cpu.sv.
// =============================================================================

module ucode (
    input  logic        clk,
    input  logic        rst,
    input  logic [7:0]  bus,       // the byte on the data bus this cycle
    output logic        fetch,
    output logic        dispatch,
    output logic        wen,
    output logic        halt,
    output logic        trap,
    output logic [1:0]  pcload,    // -> rtl/cpu.sv: load the pc, and on what terms
    output logic        lrwrite,   // -> rtl/cpu.sv: the write is a return address
    input  logic        defer      // rtl/cpu.sv: the pc is being loaded, so the
                                   // byte on the bus is not the next opcode
);

    (* ram_style = "block" *)
    logic [16:0] rom [0:511];
    initial begin
        rom[0] = 17'b100000010_0_0_0_1_0_00_0;
        rom[1] = 17'b100000011_0_0_0_0_1_00_0;
        rom[2] = 17'b100000011_0_0_0_0_1_00_0;
        rom[3] = 17'b100000011_0_0_0_0_1_00_0;
        rom[4] = 17'b100000011_0_0_0_0_1_00_0;
        rom[5] = 17'b100000000_0_0_0_0_0_00_0;
        rom[6] = 17'b100000000_0_0_0_0_0_00_0;
        rom[7] = 17'b100000000_0_0_0_0_0_00_0;
        rom[8] = 17'b100000011_0_0_0_0_1_00_0;
        rom[9] = 17'b100000011_0_0_0_0_1_00_0;
        rom[10] = 17'b100000011_0_0_0_0_1_00_0;
        rom[11] = 17'b100000011_0_0_0_0_1_00_0;
        rom[12] = 17'b100000011_0_0_0_0_1_00_0;
        rom[13] = 17'b100000011_0_0_0_0_1_00_0;
        rom[14] = 17'b100000011_0_0_0_0_1_00_0;
        rom[15] = 17'b100000011_0_0_0_0_1_00_0;
        rom[16] = 17'b100000011_0_0_0_0_1_00_0;
        rom[17] = 17'b100000011_0_0_0_0_1_00_0;
        rom[18] = 17'b100000011_0_0_0_0_1_00_0;
        rom[19] = 17'b100000011_0_0_0_0_1_00_0;
        rom[20] = 17'b100000011_0_0_0_0_1_00_0;
        rom[21] = 17'b100000011_0_0_0_0_1_00_0;
        rom[22] = 17'b100000011_0_0_0_0_1_00_0;
        rom[23] = 17'b100000011_0_0_0_0_1_00_0;
        rom[24] = 17'b100000011_0_0_0_0_1_00_0;
        rom[25] = 17'b100000011_0_0_0_0_1_00_0;
        rom[26] = 17'b100000011_0_0_0_0_1_00_0;
        rom[27] = 17'b100000011_0_0_0_0_1_00_0;
        rom[28] = 17'b100000011_0_0_0_0_1_00_0;
        rom[29] = 17'b100000011_0_0_0_0_1_00_0;
        rom[30] = 17'b100000011_0_0_0_0_1_00_0;
        rom[31] = 17'b100000011_0_0_0_0_1_00_0;
        rom[32] = 17'b100000011_0_0_0_0_1_00_0;
        rom[33] = 17'b100000011_0_0_0_0_1_00_0;
        rom[34] = 17'b100000011_0_0_0_0_1_00_0;
        rom[35] = 17'b100000011_0_0_0_0_1_00_0;
        rom[36] = 17'b100000011_0_0_0_0_1_00_0;
        rom[37] = 17'b100000011_0_0_0_0_1_00_0;
        rom[38] = 17'b100000011_0_0_0_0_1_00_0;
        rom[39] = 17'b100000011_0_0_0_0_1_00_0;
        rom[40] = 17'b100000000_1_0_0_0_0_00_0;
        rom[41] = 17'b100000011_0_0_0_0_1_00_0;
        rom[42] = 17'b100000011_0_0_0_0_1_00_0;
        rom[43] = 17'b100000011_0_0_0_0_1_00_0;
        rom[44] = 17'b100000000_1_0_0_0_0_00_0;
        rom[45] = 17'b100000000_1_0_0_0_0_00_0;
        rom[46] = 17'b100000011_0_0_0_0_1_00_0;
        rom[47] = 17'b100000011_0_0_0_0_1_00_0;
        rom[48] = 17'b100000011_0_0_0_0_1_00_0;
        rom[49] = 17'b100000011_0_0_0_0_1_00_0;
        rom[50] = 17'b100000000_1_0_0_0_0_00_0;
        rom[51] = 17'b100000101_1_0_0_0_0_00_0;
        rom[52] = 17'b100000011_0_0_0_0_1_00_0;
        rom[53] = 17'b100000011_0_0_0_0_1_00_0;
        rom[54] = 17'b100000011_0_0_0_0_1_00_0;
        rom[55] = 17'b100000011_0_0_0_0_1_00_0;
        rom[56] = 17'b100000000_1_0_0_0_0_00_0;
        rom[57] = 17'b100000001_1_0_0_0_0_00_0;
        rom[58] = 17'b100000000_1_0_0_0_0_00_0;
        rom[59] = 17'b100000000_1_0_0_0_0_00_0;
        rom[60] = 17'b100000000_1_0_0_0_0_00_0;
        rom[61] = 17'b100000000_1_0_0_0_0_00_0;
        rom[62] = 17'b100000000_1_0_0_0_0_00_0;
        rom[63] = 17'b100000000_1_0_0_0_0_00_0;
        rom[64] = 17'b100000000_1_0_0_0_0_00_0;
        rom[65] = 17'b100000001_1_0_0_0_0_00_0;
        rom[66] = 17'b100000000_1_0_0_0_0_00_0;
        rom[67] = 17'b100000000_1_0_0_0_0_00_0;
        rom[68] = 17'b100000011_0_0_0_0_1_00_0;
        rom[69] = 17'b100000011_0_0_0_0_1_00_0;
        rom[70] = 17'b100000000_1_0_0_0_0_00_0;
        rom[71] = 17'b100000000_1_0_0_0_0_00_0;
        rom[72] = 17'b100000000_1_0_0_0_0_00_0;
        rom[73] = 17'b100000001_1_0_0_0_0_00_0;
        rom[74] = 17'b100000000_1_0_0_0_0_00_0;
        rom[75] = 17'b100000000_1_0_0_0_0_00_0;
        rom[76] = 17'b100000000_1_0_0_0_0_00_0;
        rom[77] = 17'b100000000_1_0_0_0_0_00_0;
        rom[78] = 17'b100000000_1_0_0_0_0_00_0;
        rom[79] = 17'b100000000_1_0_0_0_0_00_0;
        rom[80] = 17'b100000000_1_0_0_0_0_00_0;
        rom[81] = 17'b100000001_1_0_0_0_0_00_0;
        rom[82] = 17'b100000000_1_0_0_0_0_00_0;
        rom[83] = 17'b100000000_1_0_0_0_0_00_0;
        rom[84] = 17'b100000000_1_0_0_0_0_00_0;
        rom[85] = 17'b100000000_1_0_0_0_0_00_0;
        rom[86] = 17'b100000000_1_0_0_0_0_00_0;
        rom[87] = 17'b100000000_1_0_0_0_0_00_0;
        rom[88] = 17'b100000000_1_0_0_0_0_00_0;
        rom[89] = 17'b100000001_1_0_0_0_0_00_0;
        rom[90] = 17'b100000000_1_0_0_0_0_00_0;
        rom[91] = 17'b100000000_1_0_0_0_0_00_0;
        rom[92] = 17'b100000000_1_0_0_0_0_00_0;
        rom[93] = 17'b100000000_1_0_0_0_0_00_0;
        rom[94] = 17'b100000000_1_0_0_0_0_00_0;
        rom[95] = 17'b100000000_1_0_0_0_0_00_0;
        rom[96] = 17'b100000000_1_0_0_0_0_00_0;
        rom[97] = 17'b100000011_0_0_0_0_1_00_0;
        rom[98] = 17'b100000000_1_0_0_0_0_00_0;
        rom[99] = 17'b100000000_1_0_0_0_0_00_0;
        rom[100] = 17'b100000011_0_0_0_0_1_00_0;
        rom[101] = 17'b100000011_0_0_0_0_1_00_0;
        rom[102] = 17'b100000000_1_0_0_0_0_00_0;
        rom[103] = 17'b100000000_1_0_0_0_0_00_0;
        rom[104] = 17'b100000000_1_0_0_0_0_00_0;
        rom[105] = 17'b100000011_0_0_0_0_1_00_0;
        rom[106] = 17'b100000000_1_0_0_0_0_00_0;
        rom[107] = 17'b100000000_1_0_0_0_0_00_0;
        rom[108] = 17'b100000011_0_0_0_0_1_00_0;
        rom[109] = 17'b100000011_0_0_0_0_1_00_0;
        rom[110] = 17'b100000000_1_0_0_0_0_00_0;
        rom[111] = 17'b100000000_1_0_0_0_0_00_0;
        rom[112] = 17'b100000000_1_0_0_0_0_00_0;
        rom[113] = 17'b100000011_0_0_0_0_1_00_0;
        rom[114] = 17'b100000000_1_0_0_0_0_00_0;
        rom[115] = 17'b100000000_1_0_0_0_0_00_0;
        rom[116] = 17'b100000011_0_0_0_0_1_00_0;
        rom[117] = 17'b100000011_0_0_0_0_1_00_0;
        rom[118] = 17'b100000000_1_0_0_0_0_00_0;
        rom[119] = 17'b100000000_1_0_0_0_0_00_0;
        rom[120] = 17'b100000000_1_0_0_0_0_00_0;
        rom[121] = 17'b100000001_1_0_0_0_0_00_0;
        rom[122] = 17'b100000000_1_0_0_0_0_00_0;
        rom[123] = 17'b100000000_1_0_0_0_0_00_0;
        rom[124] = 17'b100000000_1_0_0_0_0_00_0;
        rom[125] = 17'b100000000_1_0_0_0_0_00_0;
        rom[126] = 17'b100000000_1_0_0_0_0_00_0;
        rom[127] = 17'b100000000_1_0_0_0_0_00_0;
        rom[128] = 17'b100000000_0_0_0_0_0_00_0;
        rom[129] = 17'b100000000_0_0_0_0_0_00_0;
        rom[130] = 17'b100000000_0_0_0_0_0_00_0;
        rom[131] = 17'b100000000_0_0_0_0_0_00_0;
        rom[132] = 17'b100000000_0_0_0_0_0_00_0;
        rom[133] = 17'b100000000_0_0_0_0_0_00_0;
        rom[134] = 17'b100000011_0_0_0_0_1_00_0;
        rom[135] = 17'b000000000_0_1_0_0_0_00_0;
        rom[136] = 17'b100000001_1_0_0_0_0_00_0;
        rom[137] = 17'b100000001_1_0_0_0_0_00_0;
        rom[138] = 17'b100000001_1_0_0_0_0_00_0;
        rom[139] = 17'b100000001_1_0_0_0_0_00_0;
        rom[140] = 17'b100000001_1_0_0_0_0_00_0;
        rom[141] = 17'b100000001_1_0_0_0_0_00_0;
        rom[142] = 17'b100000001_1_0_0_0_0_00_0;
        rom[143] = 17'b100000001_1_0_0_0_0_00_0;
        rom[144] = 17'b100000011_0_0_0_0_1_00_0;
        rom[145] = 17'b100000011_0_0_0_0_1_00_0;
        rom[146] = 17'b100000011_0_0_0_0_1_00_0;
        rom[147] = 17'b100000011_0_0_0_0_1_00_0;
        rom[148] = 17'b100000011_0_0_0_0_1_00_0;
        rom[149] = 17'b100000011_0_0_0_0_1_00_0;
        rom[150] = 17'b100000011_0_0_0_0_1_00_0;
        rom[151] = 17'b100000011_0_0_0_0_1_00_0;
        rom[152] = 17'b100000011_0_0_0_0_1_00_0;
        rom[153] = 17'b100000011_0_0_0_0_1_00_0;
        rom[154] = 17'b100000011_0_0_0_0_1_00_0;
        rom[155] = 17'b100000011_0_0_0_0_1_00_0;
        rom[156] = 17'b100000011_0_0_0_0_1_00_0;
        rom[157] = 17'b100000011_0_0_0_0_1_00_0;
        rom[158] = 17'b100000011_0_0_0_0_1_00_0;
        rom[159] = 17'b100000011_0_0_0_0_1_00_0;
        rom[160] = 17'b100000110_1_0_0_0_0_00_0;
        rom[161] = 17'b100001010_1_0_0_0_0_00_0;
        rom[162] = 17'b100001000_1_0_0_0_0_00_0;
        rom[163] = 17'b100000011_0_0_0_0_1_00_0;
        rom[164] = 17'b100000110_1_0_0_0_0_00_0;
        rom[165] = 17'b100000110_1_0_0_0_0_00_0;
        rom[166] = 17'b100000110_1_0_0_0_0_00_0;
        rom[167] = 17'b100000110_1_0_0_0_0_00_0;
        rom[168] = 17'b100000011_0_0_0_0_1_00_0;
        rom[169] = 17'b100000011_0_0_0_0_1_00_0;
        rom[170] = 17'b100001001_1_0_0_0_0_00_0;
        rom[171] = 17'b100000011_0_0_0_0_1_00_0;
        rom[172] = 17'b100000110_1_0_0_0_0_00_0;
        rom[173] = 17'b100000110_1_0_0_0_0_00_0;
        rom[174] = 17'b100000011_0_0_0_0_1_00_0;
        rom[175] = 17'b100000011_0_0_0_0_1_00_0;
        rom[176] = 17'b100000011_0_0_0_0_1_00_0;
        rom[177] = 17'b100000011_0_0_0_0_1_00_0;
        rom[178] = 17'b100000011_0_0_0_0_1_00_0;
        rom[179] = 17'b100000011_0_0_0_0_1_00_0;
        rom[180] = 17'b100000011_0_0_0_0_1_00_0;
        rom[181] = 17'b100000011_0_0_0_0_1_00_0;
        rom[182] = 17'b100000011_0_0_0_0_1_00_0;
        rom[183] = 17'b100000011_0_0_0_0_1_00_0;
        rom[184] = 17'b100000011_0_0_0_0_1_00_0;
        rom[185] = 17'b100000011_0_0_0_0_1_00_0;
        rom[186] = 17'b100000011_0_0_0_0_1_00_0;
        rom[187] = 17'b100000011_0_0_0_0_1_00_0;
        rom[188] = 17'b100000011_0_0_0_0_1_00_0;
        rom[189] = 17'b100000011_0_0_0_0_1_00_0;
        rom[190] = 17'b100000011_0_0_0_0_1_00_0;
        rom[191] = 17'b100000011_0_0_0_0_1_00_0;
        rom[192] = 17'b100000011_0_0_0_0_1_00_0;
        rom[193] = 17'b100000011_0_0_0_0_1_00_0;
        rom[194] = 17'b100000011_0_0_0_0_1_00_0;
        rom[195] = 17'b100000011_0_0_0_0_1_00_0;
        rom[196] = 17'b100000011_0_0_0_0_1_00_0;
        rom[197] = 17'b100000011_0_0_0_0_1_00_0;
        rom[198] = 17'b100000011_0_0_0_0_1_00_0;
        rom[199] = 17'b100000011_0_0_0_0_1_00_0;
        rom[200] = 17'b100000011_0_0_0_0_1_00_0;
        rom[201] = 17'b100000011_0_0_0_0_1_00_0;
        rom[202] = 17'b100000011_0_0_0_0_1_00_0;
        rom[203] = 17'b100000011_0_0_0_0_1_00_0;
        rom[204] = 17'b100000011_0_0_0_0_1_00_0;
        rom[205] = 17'b100000011_0_0_0_0_1_00_0;
        rom[206] = 17'b100000011_0_0_0_0_1_00_0;
        rom[207] = 17'b100000011_0_0_0_0_1_00_0;
        rom[208] = 17'b100000011_0_0_0_0_1_00_0;
        rom[209] = 17'b100000011_0_0_0_0_1_00_0;
        rom[210] = 17'b100000011_0_0_0_0_1_00_0;
        rom[211] = 17'b100000011_0_0_0_0_1_00_0;
        rom[212] = 17'b100000011_0_0_0_0_1_00_0;
        rom[213] = 17'b100000011_0_0_0_0_1_00_0;
        rom[214] = 17'b100000011_0_0_0_0_1_00_0;
        rom[215] = 17'b100000011_0_0_0_0_1_00_0;
        rom[216] = 17'b100000011_0_0_0_0_1_00_0;
        rom[217] = 17'b100000011_0_0_0_0_1_00_0;
        rom[218] = 17'b100000011_0_0_0_0_1_00_0;
        rom[219] = 17'b100000011_0_0_0_0_1_00_0;
        rom[220] = 17'b100000011_0_0_0_0_1_00_0;
        rom[221] = 17'b100000011_0_0_0_0_1_00_0;
        rom[222] = 17'b100000011_0_0_0_0_1_00_0;
        rom[223] = 17'b100000011_0_0_0_0_1_00_0;
        rom[224] = 17'b100000011_0_0_0_0_1_00_0;
        rom[225] = 17'b100000011_0_0_0_0_1_00_0;
        rom[226] = 17'b100000011_0_0_0_0_1_00_0;
        rom[227] = 17'b100000011_0_0_0_0_1_00_0;
        rom[228] = 17'b100000011_0_0_0_0_1_00_0;
        rom[229] = 17'b100000011_0_0_0_0_1_00_0;
        rom[230] = 17'b100000011_0_0_0_0_1_00_0;
        rom[231] = 17'b100000011_0_0_0_0_1_00_0;
        rom[232] = 17'b100000011_0_0_0_0_1_00_0;
        rom[233] = 17'b100000011_0_0_0_0_1_00_0;
        rom[234] = 17'b100000011_0_0_0_0_1_00_0;
        rom[235] = 17'b100000011_0_0_0_0_1_00_0;
        rom[236] = 17'b100000011_0_0_0_0_1_00_0;
        rom[237] = 17'b100000011_0_0_0_0_1_00_0;
        rom[238] = 17'b100000011_0_0_0_0_1_00_0;
        rom[239] = 17'b100000011_0_0_0_0_1_00_0;
        rom[240] = 17'b100000011_0_0_0_0_1_00_0;
        rom[241] = 17'b100000011_0_0_0_0_1_00_0;
        rom[242] = 17'b100000011_0_0_0_0_1_00_0;
        rom[243] = 17'b100000011_0_0_0_0_1_00_0;
        rom[244] = 17'b100000011_0_0_0_0_1_00_0;
        rom[245] = 17'b100000011_0_0_0_0_1_00_0;
        rom[246] = 17'b100000011_0_0_0_0_1_00_0;
        rom[247] = 17'b100000011_0_0_0_0_1_00_0;
        rom[248] = 17'b100000011_0_0_0_0_1_00_0;
        rom[249] = 17'b100000011_0_0_0_0_1_00_0;
        rom[250] = 17'b100000011_0_0_0_0_1_00_0;
        rom[251] = 17'b100000011_0_0_0_0_1_00_0;
        rom[252] = 17'b100000011_0_0_0_0_1_00_0;
        rom[253] = 17'b100000011_0_0_0_0_1_00_0;
        rom[254] = 17'b100000011_0_0_0_0_1_00_0;
        rom[255] = 17'b100000011_0_0_0_0_1_00_0;
        rom[256] = 17'b000000000_0_1_1_0_0_00_0;
        rom[257] = 17'b100000000_1_0_0_0_0_00_0;
        rom[258] = 17'b100000010_0_0_0_1_0_00_0;
        rom[259] = 17'b100000011_0_0_0_0_1_00_0;
        rom[260] = 17'b000000000_0_1_0_0_0_00_0;
        rom[261] = 17'b100000000_0_0_0_0_0_00_0;
        rom[262] = 17'b100000111_1_0_0_0_0_00_0;
        rom[263] = 17'b100001011_0_1_0_0_0_10_0;
        rom[264] = 17'b100001011_1_0_0_0_0_01_0;
        rom[265] = 17'b100001011_1_0_1_0_0_01_1;
        rom[266] = 17'b100001011_0_1_0_0_0_01_0;
        rom[267] = 17'b000000000_0_1_0_0_0_00_0;
    end

    logic [16:0] word;
    wire  [8:0] next;
    wire  taking;                  // this step's dispatch, before the deferral
    assign {next, fetch, taking, wen, halt, trap, pcload, lrwrite} = word;

    // A step that loads the pc says `dispatch` because the NEXT cycle's byte
    // is an opcode; it is this cycle's that is not, when the load actually
    // happens.  So the deferral suppresses both the line and the ROM's use of
    // the bus, and the word's own `next` carries the wait.
    assign dispatch = taking & ~defer;

    wire [8:0] addr = rst ? 9'd260 : (dispatch ? {1'b0, bus} : next);
    always_ff @(posedge clk) word <= rom[addr];

endmodule
