// =============================================================================
// ucode.sv - the processor's microcode ROM
// =============================================================================
//
// GENERATED by tools/gen-ucode.js from tools/ucode.js.  Do not edit.
//
// 21 routines and idle, eight steps each, in 256 words of 32 bits: two
// block RAMs side by side.
//     entry  0  idle        
//     entry  1  ld8          1 byte
//     entry  2  ld           2 bytes
//     entry  3  pop/ldm 1    2 bytes
//     entry  4  pop/ldm 2    4 bytes
//     entry  5  pop/ldm 3    6 bytes
//     entry  6  st8          1 byte
//     entry  7  st           2 bytes
//     entry  8  push/stm 1   2 bytes
//     entry  9  push/stm 2   4 bytes
//     entry 10  push/stm 3   6 bytes
//     entry 11  brk          3 steps
//     entry 12  rti          3 steps
//     entry 13  sei          1 step
//     entry 14  cli          1 step
//     entry 15  slow         2 steps
//     entry 16  mul          2 steps
//     entry 17  ld8 late     1 byte
//     entry 18  ld late      2 bytes
//     entry 19  pop/ldm 1 late 2 bytes
//     entry 20  pop/ldm 2 late 4 bytes
//     entry 21  pop/ldm 3 late 6 bytes
//
// THE WORD
//
//     0      A   an address step: mar, or mar + 1 for a load, and mar steps up
//     1      C   a load's byte arrives and shifts into ldq
//     2      R   dispatch is released
//     3      D   the last step
//     5:4    W   a loaded register is written: 1, 2 or 3, through the ALU
//     6      P   a block move's pointer is written, the same way
//     7      WE  the NEXT step writes memory
//     9:8    KS  the register read this step: 0 .. 2 of the list, 3 a literal
//     10     KH  which half of it a store's next byte is - or, when KS is 3, lr and not sp
//     12:11  SH  a shadow takes aq, the register read the step before: 1 shadow_sp, 2 shadow_lr, 3 shadow_isp
//     15:13  LQ  ldq takes: 1 the pc, 2 shadow_sp, 3 shadow_lr, 4 shadow_isp, 5 the product, 6 clz or popcount
//     17:16  WX  a register is written from ldq, through the ALU: 1 sp, 2 lr
//     19:18  IE  ie: 1 cleared, 2 set
//     21:20  RJ  the fetch goes to: 1 the vector, 2 aq, the register read the step before
//     22     L   C's byte is on mem_late, the word from two edges ago: blit mode
// =============================================================================

module ucode (
    input  logic        clk,
    input  logic [7:0]  addr,      // {entry, step - 1}; 0 when idle
    output logic [31:0] word       // the word addressed at the last edge
);

    logic [31:0] rom [0:255];
    initial begin
        rom[8'h00] = 32'h00000000;
        rom[8'h01] = 32'h00000000;
        rom[8'h02] = 32'h00000000;
        rom[8'h03] = 32'h00000000;
        rom[8'h04] = 32'h00000000;
        rom[8'h05] = 32'h00000000;
        rom[8'h06] = 32'h00000000;
        rom[8'h07] = 32'h00000000;
        rom[8'h08] = 32'h00000002;
        rom[8'h09] = 32'h00000018;
        rom[8'h0a] = 32'h00000000;
        rom[8'h0b] = 32'h00000000;
        rom[8'h0c] = 32'h00000000;
        rom[8'h0d] = 32'h00000000;
        rom[8'h0e] = 32'h00000000;
        rom[8'h0f] = 32'h00000000;
        rom[8'h10] = 32'h00000007;
        rom[8'h11] = 32'h00000002;
        rom[8'h12] = 32'h00000018;
        rom[8'h13] = 32'h00000000;
        rom[8'h14] = 32'h00000000;
        rom[8'h15] = 32'h00000000;
        rom[8'h16] = 32'h00000000;
        rom[8'h17] = 32'h00000000;
        rom[8'h18] = 32'h00000047;
        rom[8'h19] = 32'h00000002;
        rom[8'h1a] = 32'h00000018;
        rom[8'h1b] = 32'h00000000;
        rom[8'h1c] = 32'h00000000;
        rom[8'h1d] = 32'h00000000;
        rom[8'h1e] = 32'h00000000;
        rom[8'h1f] = 32'h00000000;
        rom[8'h20] = 32'h00000043;
        rom[8'h21] = 32'h00000003;
        rom[8'h22] = 32'h00000017;
        rom[8'h23] = 32'h00000002;
        rom[8'h24] = 32'h00000028;
        rom[8'h25] = 32'h00000000;
        rom[8'h26] = 32'h00000000;
        rom[8'h27] = 32'h00000000;
        rom[8'h28] = 32'h00000043;
        rom[8'h29] = 32'h00000003;
        rom[8'h2a] = 32'h00000013;
        rom[8'h2b] = 32'h00000003;
        rom[8'h2c] = 32'h00000027;
        rom[8'h2d] = 32'h00000002;
        rom[8'h2e] = 32'h00000038;
        rom[8'h2f] = 32'h00000000;
        rom[8'h30] = 32'h0000000d;
        rom[8'h31] = 32'h00000000;
        rom[8'h32] = 32'h00000000;
        rom[8'h33] = 32'h00000000;
        rom[8'h34] = 32'h00000000;
        rom[8'h35] = 32'h00000000;
        rom[8'h36] = 32'h00000000;
        rom[8'h37] = 32'h00000000;
        rom[8'h38] = 32'h00000481;
        rom[8'h39] = 32'h0000000d;
        rom[8'h3a] = 32'h00000000;
        rom[8'h3b] = 32'h00000000;
        rom[8'h3c] = 32'h00000000;
        rom[8'h3d] = 32'h00000000;
        rom[8'h3e] = 32'h00000000;
        rom[8'h3f] = 32'h00000000;
        rom[8'h40] = 32'h00000481;
        rom[8'h41] = 32'h00000005;
        rom[8'h42] = 32'h00000048;
        rom[8'h43] = 32'h00000000;
        rom[8'h44] = 32'h00000000;
        rom[8'h45] = 32'h00000000;
        rom[8'h46] = 32'h00000000;
        rom[8'h47] = 32'h00000000;
        rom[8'h48] = 32'h00000481;
        rom[8'h49] = 32'h00000181;
        rom[8'h4a] = 32'h00000581;
        rom[8'h4b] = 32'h00000005;
        rom[8'h4c] = 32'h00000048;
        rom[8'h4d] = 32'h00000000;
        rom[8'h4e] = 32'h00000000;
        rom[8'h4f] = 32'h00000000;
        rom[8'h50] = 32'h00000481;
        rom[8'h51] = 32'h00000181;
        rom[8'h52] = 32'h00000581;
        rom[8'h53] = 32'h00000281;
        rom[8'h54] = 32'h00000681;
        rom[8'h55] = 32'h00000005;
        rom[8'h56] = 32'h00000048;
        rom[8'h57] = 32'h00000000;
        rom[8'h58] = 32'h00042700;
        rom[8'h59] = 32'h00129300;
        rom[8'h5a] = 32'h00010808;
        rom[8'h5b] = 32'h00000000;
        rom[8'h5c] = 32'h00000000;
        rom[8'h5d] = 32'h00000000;
        rom[8'h5e] = 32'h00000000;
        rom[8'h5f] = 32'h00000000;
        rom[8'h60] = 32'h00086700;
        rom[8'h61] = 32'h00224300;
        rom[8'h62] = 32'h00011808;
        rom[8'h63] = 32'h00000000;
        rom[8'h64] = 32'h00000000;
        rom[8'h65] = 32'h00000000;
        rom[8'h66] = 32'h00000000;
        rom[8'h67] = 32'h00000000;
        rom[8'h68] = 32'h0008000c;
        rom[8'h69] = 32'h00000000;
        rom[8'h6a] = 32'h00000000;
        rom[8'h6b] = 32'h00000000;
        rom[8'h6c] = 32'h00000000;
        rom[8'h6d] = 32'h00000000;
        rom[8'h6e] = 32'h00000000;
        rom[8'h6f] = 32'h00000000;
        rom[8'h70] = 32'h0004000c;
        rom[8'h71] = 32'h00000000;
        rom[8'h72] = 32'h00000000;
        rom[8'h73] = 32'h00000000;
        rom[8'h74] = 32'h00000000;
        rom[8'h75] = 32'h00000000;
        rom[8'h76] = 32'h00000000;
        rom[8'h77] = 32'h00000000;
        rom[8'h78] = 32'h0000c000;
        rom[8'h79] = 32'h00000018;
        rom[8'h7a] = 32'h00000000;
        rom[8'h7b] = 32'h00000000;
        rom[8'h7c] = 32'h00000000;
        rom[8'h7d] = 32'h00000000;
        rom[8'h7e] = 32'h00000000;
        rom[8'h7f] = 32'h00000000;
        rom[8'h80] = 32'h0000a000;
        rom[8'h81] = 32'h00000018;
        rom[8'h82] = 32'h00000000;
        rom[8'h83] = 32'h00000000;
        rom[8'h84] = 32'h00000000;
        rom[8'h85] = 32'h00000000;
        rom[8'h86] = 32'h00000000;
        rom[8'h87] = 32'h00000000;
        rom[8'hb0] = 32'h00000000;
        rom[8'hb1] = 32'h00000000;
        rom[8'hb2] = 32'h00000000;
        rom[8'hb3] = 32'h00000000;
        rom[8'hb4] = 32'h00000000;
        rom[8'hb5] = 32'h00000000;
        rom[8'hb6] = 32'h00000000;
        rom[8'hb7] = 32'h00000000;
        rom[8'hb8] = 32'h00000000;
        rom[8'hb9] = 32'h00000000;
        rom[8'hba] = 32'h00000000;
        rom[8'hbb] = 32'h00000000;
        rom[8'hbc] = 32'h00000000;
        rom[8'hbd] = 32'h00000000;
        rom[8'hbe] = 32'h00000000;
        rom[8'hbf] = 32'h00000000;
        rom[8'hc0] = 32'h00000000;
        rom[8'hc1] = 32'h00000000;
        rom[8'hc2] = 32'h00000000;
        rom[8'hc3] = 32'h00000000;
        rom[8'hc4] = 32'h00000000;
        rom[8'hc5] = 32'h00000000;
        rom[8'hc6] = 32'h00000000;
        rom[8'hc7] = 32'h00000000;
        rom[8'hc8] = 32'h00000000;
        rom[8'hc9] = 32'h00000000;
        rom[8'hca] = 32'h00000000;
        rom[8'hcb] = 32'h00000000;
        rom[8'hcc] = 32'h00000000;
        rom[8'hcd] = 32'h00000000;
        rom[8'hce] = 32'h00000000;
        rom[8'hcf] = 32'h00000000;
        rom[8'hd0] = 32'h00000000;
        rom[8'hd1] = 32'h00000000;
        rom[8'hd2] = 32'h00000000;
        rom[8'hd3] = 32'h00000000;
        rom[8'hd4] = 32'h00000000;
        rom[8'hd5] = 32'h00000000;
        rom[8'hd6] = 32'h00000000;
        rom[8'hd7] = 32'h00000000;
        rom[8'hd8] = 32'h00000000;
        rom[8'hd9] = 32'h00000000;
        rom[8'hda] = 32'h00000000;
        rom[8'hdb] = 32'h00000000;
        rom[8'hdc] = 32'h00000000;
        rom[8'hdd] = 32'h00000000;
        rom[8'hde] = 32'h00000000;
        rom[8'hdf] = 32'h00000000;
        rom[8'he0] = 32'h00000000;
        rom[8'he1] = 32'h00000000;
        rom[8'he2] = 32'h00000000;
        rom[8'he3] = 32'h00000000;
        rom[8'he4] = 32'h00000000;
        rom[8'he5] = 32'h00000000;
        rom[8'he6] = 32'h00000000;
        rom[8'he7] = 32'h00000000;
        rom[8'he8] = 32'h00000000;
        rom[8'he9] = 32'h00000000;
        rom[8'hea] = 32'h00000000;
        rom[8'heb] = 32'h00000000;
        rom[8'hec] = 32'h00000000;
        rom[8'hed] = 32'h00000000;
        rom[8'hee] = 32'h00000000;
        rom[8'hef] = 32'h00000000;
        rom[8'hf0] = 32'h00000000;
        rom[8'hf1] = 32'h00000000;
        rom[8'hf2] = 32'h00000000;
        rom[8'hf3] = 32'h00000000;
        rom[8'hf4] = 32'h00000000;
        rom[8'hf5] = 32'h00000000;
        rom[8'hf6] = 32'h00000000;
        rom[8'hf7] = 32'h00000000;
        rom[8'hf8] = 32'h00000000;
        rom[8'hf9] = 32'h00000000;
        rom[8'hfa] = 32'h00000000;
        rom[8'hfb] = 32'h00000000;
        rom[8'hfc] = 32'h00000000;
        rom[8'hfd] = 32'h00000000;
        rom[8'hfe] = 32'h00000000;
        rom[8'hff] = 32'h00000000;
`ifdef FRUCTUS_BLIT
        rom[8'h88] = 32'h00000004;
        rom[8'h89] = 32'h00400002;
        rom[8'h8a] = 32'h00000018;
        rom[8'h8b] = 32'h00000000;
        rom[8'h8c] = 32'h00000000;
        rom[8'h8d] = 32'h00000000;
        rom[8'h8e] = 32'h00000000;
        rom[8'h8f] = 32'h00000000;
        rom[8'h90] = 32'h00000001;
        rom[8'h91] = 32'h00400006;
        rom[8'h92] = 32'h00400002;
        rom[8'h93] = 32'h00000018;
        rom[8'h94] = 32'h00000000;
        rom[8'h95] = 32'h00000000;
        rom[8'h96] = 32'h00000000;
        rom[8'h97] = 32'h00000000;
        rom[8'h98] = 32'h00000041;
        rom[8'h99] = 32'h00400006;
        rom[8'h9a] = 32'h00400002;
        rom[8'h9b] = 32'h00000018;
        rom[8'h9c] = 32'h00000000;
        rom[8'h9d] = 32'h00000000;
        rom[8'h9e] = 32'h00000000;
        rom[8'h9f] = 32'h00000000;
        rom[8'ha0] = 32'h00000041;
        rom[8'ha1] = 32'h00400003;
        rom[8'ha2] = 32'h00400003;
        rom[8'ha3] = 32'h00400016;
        rom[8'ha4] = 32'h00400002;
        rom[8'ha5] = 32'h00000028;
        rom[8'ha6] = 32'h00000000;
        rom[8'ha7] = 32'h00000000;
        rom[8'ha8] = 32'h00000041;
        rom[8'ha9] = 32'h00400003;
        rom[8'haa] = 32'h00400003;
        rom[8'hab] = 32'h00400013;
        rom[8'hac] = 32'h00400003;
        rom[8'had] = 32'h00400026;
        rom[8'hae] = 32'h00400002;
        rom[8'haf] = 32'h00000038;
`else
        rom[8'h88] = 32'h00000000;
        rom[8'h89] = 32'h00000000;
        rom[8'h8a] = 32'h00000000;
        rom[8'h8b] = 32'h00000000;
        rom[8'h8c] = 32'h00000000;
        rom[8'h8d] = 32'h00000000;
        rom[8'h8e] = 32'h00000000;
        rom[8'h8f] = 32'h00000000;
        rom[8'h90] = 32'h00000000;
        rom[8'h91] = 32'h00000000;
        rom[8'h92] = 32'h00000000;
        rom[8'h93] = 32'h00000000;
        rom[8'h94] = 32'h00000000;
        rom[8'h95] = 32'h00000000;
        rom[8'h96] = 32'h00000000;
        rom[8'h97] = 32'h00000000;
        rom[8'h98] = 32'h00000000;
        rom[8'h99] = 32'h00000000;
        rom[8'h9a] = 32'h00000000;
        rom[8'h9b] = 32'h00000000;
        rom[8'h9c] = 32'h00000000;
        rom[8'h9d] = 32'h00000000;
        rom[8'h9e] = 32'h00000000;
        rom[8'h9f] = 32'h00000000;
        rom[8'ha0] = 32'h00000000;
        rom[8'ha1] = 32'h00000000;
        rom[8'ha2] = 32'h00000000;
        rom[8'ha3] = 32'h00000000;
        rom[8'ha4] = 32'h00000000;
        rom[8'ha5] = 32'h00000000;
        rom[8'ha6] = 32'h00000000;
        rom[8'ha7] = 32'h00000000;
        rom[8'ha8] = 32'h00000000;
        rom[8'ha9] = 32'h00000000;
        rom[8'haa] = 32'h00000000;
        rom[8'hab] = 32'h00000000;
        rom[8'hac] = 32'h00000000;
        rom[8'had] = 32'h00000000;
        rom[8'hae] = 32'h00000000;
        rom[8'haf] = 32'h00000000;
`endif
    end

    always_ff @(posedge clk) word <= rom[addr];

endmodule
