// =============================================================================
// unary.sv - the unary ALU
// =============================================================================
//
// GENERATED by tools/gen-unary.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run `npm run rtl`.
//
// 4 operations at opcodes 0x32 and 0x33, selected by rhs[2:1]:
//
//   code  imm3 index  rhs value  operation
//      0     1        0      clz
//      1     4        3      popcount
//      2     5        4      bitrev
//      3     6        6      sxt8
//
// THE SELECTOR IS THE RIGHT-HAND SIDE, AFTER THE LOOKUP.  The unary forms sit
// in the imm3 columns, so {byte1[7:6], opcode[0]} is an imm3 index, rtl/immgen.sv
// turns it into a value and rtl/rhs.sv puts that on the bus the ALU already
// reads.  This block takes two bits of the value, so it has exactly the inputs
// every other ALU operation has - lhs and rhs - and no selector lines run from
// decode to the ALU.  The indices no operation uses alias harmlessly:
//
//     index 0 (-1) reads as sxt8
//     index 2 (1) reads as clz
//     index 3 (2) reads as popcount
//     index 7 (8) reads as clz
//
// TWO BITS, BECAUSE zxt8 IS GONE.  `and rd, rd, #0x00ff` is two bytes through
// immask5, and with a separate source register zero extension is still one
// instruction - `and rd, ra, #255`, three bytes through imm10 - so zxt8 only
// ever saved a byte in that case.  Four operations leave one of the value's
// three low bits unread, and WHICH one was measured rather than assumed - UP5K,
// yosys 0.52 -nobram, nextpnr-ice40 0.7, medians of eight seeds, the ALU alone
// and behind an 8x16 register file:
//
//     rhs[1:0]    45.8 MHz alone    26.1 MHz behind the file
//     rhs[2:1]    46.9              25.9
//
// Level: the select is not on the critical path at either bit, since behind
// the file the late arrival is the register value into clz and popcount.  So
// the choice was made on the encoding, and bits 2:1 keep the codes clz 0,
// popcount 3, bitrev 4 and sxt8 6.
//
// A FOUR-WAY MUX IS WHAT MADE A LATE SELECT CHEAP.  The eight-way block this
// replaced measured two LUT levels slower with its selector off the rhs bus -
// 38.4 against 49.2 MHz - because a late select on a wide mux cannot be folded
// into the logic producing the data.  Four ways on two late bits measure the
// same as the old block with its selector wired from the instruction register.
//
// WHAT THE BLOCK COSTS THE DATAPATH: removing it altogether is worth an eighth
// of the clock behind the register file, 29.1 against 26.0 MHz.  Removing only
// clz or only popcount is worth nothing, because the two are equally deep and
// the other remains.
//
// bitrev IS WIRING and nothing else - a permutation of sixteen nets - and sxt8
// is a fanout.  So the block's entire cost and depth is clz and popcount, plus
// the mux.
//
// clz IS THE PRIORITY ENCODER, not the nibble-and-NOR version.  The nibble one
// is smaller - 21 SB_LUT4 against 31 - but it is five LUT levels against four,
// and depth is the budget worth defending here.
//
// AND clz(0) = 16 IS A REAL COST, kept deliberately.  gcc leaves
// __builtin_clz(0) undefined, and leaving it undefined here would drop the
// answer from five bits to four, taking the 16-input NOR that produces bit 4
// with it: measured, 4 LUT levels and 62.7 MHz becomes 3 levels and 84.1 MHz.
// It is not taken because an instruction whose result depends on how it was
// reached is a bad thing to have in an ISA - but if clz ever turns out to set
// this block's depth, that is where the headroom is.
//
// popcount TAKES THE TOP BIT OUT OF THE ADDER.  A nibble count's bit 2 is set
// only for 1111, and then its low bits are zero - so the total reaches 16 only
// when all four nibbles are full, and y[4] is the AND of the four high bits
// rather than a carry out.  That shortens the final ripple from three steps to
// one: 86 MHz against 70, for one more LUT and one fewer carry cell.
// =============================================================================

module unary (
    input  logic [15:0] a,
    input  logic [1:0]  sel,     // rhs[2:1]: two bits of the imm3 value
    output logic [15:0] y
);

    // --- wiring -------------------------------------------------------------
    wire [15:0] sxt = {{8{a[7]}}, a[7:0]};
    wire [15:0] rev = { a[0],  a[1],  a[2],  a[3],  a[4],  a[5],  a[6],  a[7],
                        a[8],  a[9],  a[10], a[11], a[12], a[13], a[14], a[15] };

    // --- clz: one flat priority encoder -------------------------------------
    logic [4:0] cl;
    always_comb casez (a)
        16'b1???????????????: cl = 5'd0;
        16'b01??????????????: cl = 5'd1;
        16'b001?????????????: cl = 5'd2;
        16'b0001????????????: cl = 5'd3;
        16'b00001???????????: cl = 5'd4;
        16'b000001??????????: cl = 5'd5;
        16'b0000001?????????: cl = 5'd6;
        16'b00000001????????: cl = 5'd7;
        16'b000000001???????: cl = 5'd8;
        16'b0000000001??????: cl = 5'd9;
        16'b00000000001?????: cl = 5'd10;
        16'b000000000001????: cl = 5'd11;
        16'b0000000000001???: cl = 5'd12;
        16'b00000000000001??: cl = 5'd13;
        16'b000000000000001?: cl = 5'd14;
        16'b0000000000000001: cl = 5'd15;
        default:  cl = 5'd16;                   // a == 0
    endcase

    // --- popcount: four nibble counts, then two adds and an AND -------------
    function automatic [2:0] cnt4(input [3:0] n);
        case (n)
        4'h0: cnt4 = 3'd0;
        4'h1: cnt4 = 3'd1;
        4'h2: cnt4 = 3'd1;
        4'h3: cnt4 = 3'd2;
        4'h4: cnt4 = 3'd1;
        4'h5: cnt4 = 3'd2;
        4'h6: cnt4 = 3'd2;
        4'h7: cnt4 = 3'd3;
        4'h8: cnt4 = 3'd1;
        4'h9: cnt4 = 3'd2;
        4'ha: cnt4 = 3'd2;
        4'hb: cnt4 = 3'd3;
        4'hc: cnt4 = 3'd2;
        4'hd: cnt4 = 3'd3;
        4'he: cnt4 = 3'd3;
        4'hf: cnt4 = 3'd4;
        endcase
    endfunction
    wire [2:0] p0 = cnt4(a[3:0]),   p1 = cnt4(a[7:4]);
    wire [2:0] p2 = cnt4(a[11:8]),  p3 = cnt4(a[15:12]);
    wire [3:0] s01 = p0 + p1;
    wire [3:0] s23 = p2 + p3;
    wire [4:0] pc = {p0[2] & p1[2] & p2[2] & p3[2], s01[3:0] + s23[3:0]};

    // --- the mux ------------------------------------------------------------
    always_comb case (sel)
        2'd0: y = {11'd0, cl};       // clz
        2'd1: y = {11'd0, pc};       // popcount
        2'd2: y = rev;               // bitrev
        2'd3: y = sxt;               // sxt8
    endcase

endmodule
