// =============================================================================
// unary.sv - the unary ALU
// =============================================================================
//
// GENERATED by tools/gen-unary.js from isa/fructus.toml.  Do not edit; edit the
// spec, tools/control.js or the generator and run `npm run rtl`.
//
// Four operations in two pairs, one opcode each:
//
//   code  opcode  imm3 index  rhs value  operation
//      0    0x33    1        0      clz       slow
//      1    0x32    4        3      bitrev    fast
//      2    0x33    5        4      popcount  slow
//      3    0x32    6        6      sxt8      fast
//
// `code` is rhs[2:1]: the unary forms sit in the imm3 columns, rtl/immgen.sv
// turns {byte1[7:6], opcode[0]} into a value, and rtl/rhs.sv puts it on the bus
// the ALU already reads.  Within each pair the two codes differ in rhs[2]
// alone, so ONE bit of that value picks the operation, and which pair is
// rtl/alu.sv's operation code - 12 fast, 13 slow - from rtl/predecode.sv.
//
// THE SLOW PAIR IS REGISTERED.  clz and popcount are the deep operations:
// measured in the processor, taking both out of the single cycle was worth a
// tenth of the clock, and taking either alone was not, because they are
// equally deep.  So their result goes into a register at the end of every
// cycle, and the instructions that use it declare an extra cycle in the spec -
// rtl/ucode.sv waits one step before the write.  lhs and the selector do not
// change between the two cycles, so the registered value is the right one.
// The fast pair, sxt8 and bitrev, is wiring and stays combinational.
//
// THAT SPLIT FALLS ON THE OPCODE BECAUSE THE MICROCODE'S ENTRY POINTS DO.  The
// wait is a different routine, and an entry point is chosen by the first byte;
// byte 1 cannot pick it.  tools/control.js refuses a layout in which a pair
// straddles two opcodes.
//
// NOTHING HERE FORCES A CARRY CHAIN.  popcount's adds are written as gates, not
// with `+`, so synthesis infers no carry cells: the adds become LUT logic placed
// alongside the rest of the block, not in the fabric's fixed carry columns.
// Measured, popcount's carry chains had cost more clock in routing than its
// eleven LUTs suggested.
//
// clz IS THE PRIORITY ENCODER, not the nibble-and-NOR version, and clz(0) = 16
// is kept deliberately: an instruction whose result depends on how it was
// reached is a bad thing to have in an ISA, even though leaving it undefined
// would drop the answer to four bits.
//
// MEASURED - see rtl/cpu.sv.
// =============================================================================

module unary (
    input  logic        clk,
    input  logic [15:0] a,
    input  logic        sel,     // rhs[2]: which operation of the pair
    output logic [15:0] fast,    // bitrev or sxt8, this cycle
    output logic [15:0] slow     // clz or popcount, of the previous cycle's a
);

    // --- the fast pair: wiring ------------------------------------------------
    wire [15:0] sxt = {{8{a[7]}}, a[7:0]};
    wire [15:0] rev = { a[0],  a[1],  a[2],  a[3],  a[4],  a[5],  a[6],  a[7],
                        a[8],  a[9],  a[10], a[11], a[12], a[13], a[14], a[15] };

    assign fast = sel ? sxt : rev;

    // --- clz: one flat priority encoder -----------------------------------------
    logic [4:0] cl;
    always_comb casez (a)
        16'b1???????????????: cl = 5'd0;
        16'b01??????????????: cl = 5'd1;
        16'b001?????????????: cl = 5'd2;
        16'b0001????????????: cl = 5'd3;
        16'b00001???????????: cl = 5'd4;
        16'b000001??????????: cl = 5'd5;
        16'b0000001?????????: cl = 5'd6;
        16'b00000001????????: cl = 5'd7;
        16'b000000001???????: cl = 5'd8;
        16'b0000000001??????: cl = 5'd9;
        16'b00000000001?????: cl = 5'd10;
        16'b000000000001????: cl = 5'd11;
        16'b0000000000001???: cl = 5'd12;
        16'b00000000000001??: cl = 5'd13;
        16'b000000000000001?: cl = 5'd14;
        16'b0000000000000001: cl = 5'd15;
        default:  cl = 5'd16;                   // a == 0
    endcase

    // --- popcount: four nibble counts, then two adds written as gates ------------
    function automatic [2:0] cnt4(input [3:0] n);
        case (n)
        4'h0: cnt4 = 3'd0;
        4'h1: cnt4 = 3'd1;
        4'h2: cnt4 = 3'd1;
        4'h3: cnt4 = 3'd2;
        4'h4: cnt4 = 3'd1;
        4'h5: cnt4 = 3'd2;
        4'h6: cnt4 = 3'd2;
        4'h7: cnt4 = 3'd3;
        4'h8: cnt4 = 3'd1;
        4'h9: cnt4 = 3'd2;
        4'ha: cnt4 = 3'd2;
        4'hb: cnt4 = 3'd3;
        4'hc: cnt4 = 3'd2;
        4'hd: cnt4 = 3'd3;
        4'he: cnt4 = 3'd3;
        4'hf: cnt4 = 3'd4;
        endcase
    endfunction
    function automatic [3:0] add3(input [2:0] x, input [2:0] y);
        logic [2:0] c;
        c[0] = x[0] & y[0];
        c[1] = (x[1] & y[1]) | (c[0] & (x[1] ^ y[1]));
        c[2] = (x[2] & y[2]) | (c[1] & (x[2] ^ y[2]));
        add3 = {c[2], x[2] ^ y[2] ^ c[1], x[1] ^ y[1] ^ c[0], x[0] ^ y[0]};
    endfunction
    function automatic [4:0] add4(input [3:0] x, input [3:0] y);
        logic [3:0] c;
        c[0] = x[0] & y[0];
        c[1] = (x[1] & y[1]) | (c[0] & (x[1] ^ y[1]));
        c[2] = (x[2] & y[2]) | (c[1] & (x[2] ^ y[2]));
        c[3] = (x[3] & y[3]) | (c[2] & (x[3] ^ y[3]));
        add4 = {c[3], x[3] ^ y[3] ^ c[2], x[2] ^ y[2] ^ c[1], x[1] ^ y[1] ^ c[0], x[0] ^ y[0]};
    endfunction
    wire [2:0] p0 = cnt4(a[3:0]),   p1 = cnt4(a[7:4]);
    wire [2:0] p2 = cnt4(a[11:8]),  p3 = cnt4(a[15:12]);
    wire [4:0] pc = add4(add3(p0, p1), add3(p2, p3));

    // --- the slow pair, registered -----------------------------------------------
    always_ff @(posedge clk) slow <= sel ? {11'd0, pc} : {11'd0, cl};

endmodule
