#!/usr/bin/env node
// =============================================================================
// gen-unary.js - the unary ALU, from isa/fructus.toml
// =============================================================================
//
//   node tools/gen-unary.js > rtl/unary.sv
//
// Two pairs of unary operations: a fast pair that is wiring - sxt8 and bitrev -
// and a slow pair - clz and popcount - whose result is registered, because the
// spec gives those two an extra cycle.  The OPERATIONS are hand-written below;
// where each sits, and which is fast, comes from the spec through
// tools/control.js, so an operation cannot be added or moved without this file
// either implementing it or refusing to run.
// =============================================================================

import { unaryLayout } from './control.js';

const L = unaryLayout();

const IMPL = {
  sxt8:     'sxt',
  bitrev:   'rev',
  clz:      "{11'd0, cl}",
  popcount: "{11'd0, pc}",
};
for (const o of L.ops)
  if (!(o.mnemonic in IMPL)) throw new Error(`unary ${o.mnemonic} is not implemented by rtl/unary.sv`);
if ([...L.fast, ...L.slow].some((m, i) => m && ['sxt8', 'bitrev'].includes(m) !== i < 2))
  throw new Error(`clz and popcount must be the slow pair and sxt8 and bitrev the fast one: fast ${L.fast}, slow ${L.slow}`);

const impl = (m) => (m ? IMPL[m] : "16'hxxxx");
const hex = (n) => `0x${n.toString(16).padStart(2, '0')}`;
const listed = [...L.ops].sort((a, b) => a.code - b.code).map((o) =>
  `//     ${String(o.code).padStart(2)}    ${hex(o.op)}   ${String(o.index).padStart(2)}      ${String(o.value).padStart(3)}      ${o.mnemonic.padEnd(9)} ${o.slow ? 'slow' : 'fast'}`)
  .join('\n');

const pcRows = [...Array(16).keys()]
  .map((n) => `        4'h${n.toString(16)}: cnt4 = 3'd${n.toString(2).split('').filter((c) => c === '1').length};`)
  .join('\n');
const clzRows = [...Array(16).keys()].map((i) => {
  const pat = '0'.repeat(i) + '1' + '?'.repeat(15 - i);
  return `        16'b${pat}: cl = 5'd${i};`;
}).join('\n');

process.stdout.write(`// =============================================================================
// unary.sv - the unary ALU
// =============================================================================
//
// GENERATED by tools/gen-unary.js from isa/fructus.toml.  Do not edit; edit the
// spec, tools/control.js or the generator and run \`npm run rtl\`.
//
// Four operations in two pairs, one opcode each:
//
//   code  opcode  imm3 index  rhs value  operation
${listed}
//
// \`code\` is rhs[2:1]: the unary forms sit in the imm3 columns, rtl/immgen.sv
// turns {byte1[7:6], opcode[0]} into a value, and rtl/rhs.sv puts it on the bus
// the ALU already reads.  Within each pair the two codes differ in rhs[${L.selBit}]
// alone, so ONE bit of that value picks the operation, and which pair is
// rtl/alu.sv's operation code - 12 fast, 13 slow - from rtl/predecode.sv.
//
// THE SLOW PAIR IS REGISTERED.  clz and popcount are the deep operations:
// measured in the processor, taking both out of the single cycle was worth a
// tenth of the clock, and taking either alone was not, because they are
// equally deep.  So their result goes into a register at the end of every
// cycle, and the instructions that use it declare an extra cycle in the spec -
// rtl/ucode.sv waits one step before the write.  lhs and the selector do not
// change between the two cycles, so the registered value is the right one.
// The fast pair, sxt8 and bitrev, is wiring and stays combinational.
//
// THAT SPLIT FALLS ON THE OPCODE BECAUSE THE MICROCODE'S ENTRY POINTS DO.  The
// wait is a different routine, and an entry point is chosen by the first byte;
// byte 1 cannot pick it.  tools/control.js refuses a layout in which a pair
// straddles two opcodes.
//
// NOTHING HERE FORCES A CARRY CHAIN.  popcount's adds are written as gates, not
// with \`+\`, so synthesis infers no carry cells: the adds become LUT logic placed
// alongside the rest of the block, not in the fabric's fixed carry columns.
// Measured, popcount's carry chains had cost more clock in routing than its
// eleven LUTs suggested.
//
// clz IS THE PRIORITY ENCODER, not the nibble-and-NOR version, and clz(0) = 16
// is kept deliberately: an instruction whose result depends on how it was
// reached is a bad thing to have in an ISA, even though leaving it undefined
// would drop the answer to four bits.
//
// MEASURED - see rtl/cpu.sv.
// =============================================================================

module unary (
    input  logic        clk,
    input  logic [15:0] a,
    input  logic [15:0] araw,    // the same read, one cycle earlier: see popcount
    input  logic        sel,     // rhs[${L.selBit}]: which operation of the pair
    output logic [15:0] fast,    // ${L.fast[0]} or ${L.fast[1]}, this cycle
    output logic [15:0] slow     // ${L.slow[0]} or ${L.slow[1]}, of the previous cycle's a
);

    // --- the fast pair: wiring ------------------------------------------------
    wire [15:0] sxt = {{8{a[7]}}, a[7:0]};
    wire [15:0] rev = { a[0],  a[1],  a[2],  a[3],  a[4],  a[5],  a[6],  a[7],
                        a[8],  a[9],  a[10], a[11], a[12], a[13], a[14], a[15] };

    assign fast = sel ? ${impl(L.fast[1])} : ${impl(L.fast[0])};

    // --- clz: one flat priority encoder -----------------------------------------
    logic [4:0] cl;
    always_comb casez (a)
${clzRows}
        default:  cl = 5'd16;                   // a == 0
    endcase

    // --- popcount: the nibble counts a cycle early, then the adds ---------------
    function automatic [2:0] cnt4(input [3:0] n);
        case (n)
${pcRows}
        endcase
    endfunction
    function automatic [3:0] add3(input [2:0] x, input [2:0] y);
        logic [2:0] c;
        c[0] = x[0] & y[0];
        c[1] = (x[1] & y[1]) | (c[0] & (x[1] ^ y[1]));
        c[2] = (x[2] & y[2]) | (c[1] & (x[2] ^ y[2]));
        add3 = {c[2], x[2] ^ y[2] ^ c[1], x[1] ^ y[1] ^ c[0], x[0] ^ y[0]};
    endfunction
    function automatic [4:0] add4(input [3:0] x, input [3:0] y);
        logic [3:0] c;
        c[0] = x[0] & y[0];
        c[1] = (x[1] & y[1]) | (c[0] & (x[1] ^ y[1]));
        c[2] = (x[2] & y[2]) | (c[1] & (x[2] ^ y[2]));
        c[3] = (x[3] & y[3]) | (c[2] & (x[3] ^ y[3]));
        add4 = {c[3], x[3] ^ y[3] ^ c[2], x[2] ^ y[2] ^ c[1], x[1] ^ y[1] ^ c[0], x[0] ^ y[0]};
    endfunction
    // STAGE ONE IS THE FOUR NIBBLE COUNTS AND NOTHING ELSE.  It reads araw, the
    // register file's output BEFORE the operand flop, so it runs in the cycle
    // that READS the register rather than the cycle after it - and it costs
    // that cycle one LUT4 level, because each of a count's three bits is a
    // function of the nibble's four.
    //
    // STAGE TWO is both 3-bit adds and the 4-bit add, out of the flop alone.
    // The slow pair's own cycle used to be nearly empty; now it carries the
    // tree, and the two cycles are level instead of one being twice the other.
    //
    // THE LATENCY DOES NOT CHANGE, which is the whole point.  q holds the counts
    // of the value read in the previous cycle, which is the value the operand
    // flop is presenting now, so slow still lands one cycle after a and the two
    // instructions still declare extra_cycles = 1.  Nothing above the RTL moves:
    // not the cost model, not the microcode, not a single cycle count.
    //
    // MEASURED on the whole processor, medians of sixteen placement seeds:
    //
    //   the tree whole, as it was            27.96 MHz
    //   counts AND both adds in cycle one    27.95   the adds spend the slack
    //   the whole tree behind its own flop   29.93   but costs a second cycle
    //   the counts alone, as written here    30.27
    //
    // The second row is why the split is HERE and not one level later: cycle
    // one already holds the microcode read, rtl/predecode.sv and the register
    // file, and the two 3-bit adds are more than its remaining slack.
    wire [2:0] p0 = cnt4(araw[3:0]),   p1 = cnt4(araw[7:4]);
    wire [2:0] p2 = cnt4(araw[11:8]),  p3 = cnt4(araw[15:12]);
    logic [11:0] q;
    always_ff @(posedge clk) q <= {p3, p2, p1, p0};
    wire [4:0] pc = add4(add3(q[2:0], q[5:3]), add3(q[8:6], q[11:9]));

    // --- the slow pair, registered -----------------------------------------------
    always_ff @(posedge clk) slow <= sel ? ${impl(L.slow[1])} : ${impl(L.slow[0])};

endmodule
`);
