#!/usr/bin/env node
// =============================================================================
// gen-compare.js - the branch decision, from isa/fructus.toml
// =============================================================================
//
//   node tools/gen-compare.js > rtl/compare.sv
//
// A unit beside rtl/alu.sv that takes the same two operands and answers one
// bit, `taken`, for the branch logic.  Its answer never enters the ALU's result,
// so the carry chain, the flags and the condition logic sit on a path of their
// own.
//
// WHICH INSTRUCTIONS it serves is read off their `semantics`: every `if (...)`
// that decides a branch.  One the rules here do not recognise makes the
// generator fail.
// =============================================================================

import { loadSpec } from './isa.js';

const spec = loadSpec();
const NAMES = spec.optype.cond3.names;
const STRUCT = ['lt', 'lo', 'le', 'ls', 'eq', 'ne', 'vs', 'vc'];
if (STRUCT.some((n, i) => NAMES[i] !== n))
  throw new Error(`cond3 is ${NAMES.join(' ')}; the condition logic below assumes ${STRUCT.join(' ')}`);

const RULES = [
  [/^if \(test\(cond, R\[a\], R\[b\], 16\)\) /,    'subtract', 'br, the cond3 field'],
  [/^if \(test\(k\.cond, R\[a\], k\.imm, 16\)\) /, 'subtract', 'br, the condimm5 table'],
  [/^if \(\(R\[a\] & mask\) == 0\) /,              'mask',     'brclear, eq'],
  [/^if \(\(R\[a\] & mask\) != 0\) /,              'mask',     'brset, ne'],
];
const LATER = new Set([]);
const served = { subtract: [], mask: [] };
for (const insn of spec.insn) {
  const sem = insn.semantics ?? '';
  if (!/^if \(/.test(sem) || LATER.has(insn.mnemonic)) continue;
  const rule = RULES.find(([re]) => re.test(sem));
  if (!rule) throw new Error(`${insn.mnemonic}: no compare mode matches "${sem}"`);
  if (!served[rule[1]].includes(rule[2])) served[rule[1]].push(rule[2]);
}
for (const [mode, who] of Object.entries(served))
  if (!who.length) throw new Error(`nothing uses the ${mode} mode`);

process.stdout.write(`// =============================================================================
// compare.sv - the branch decision
// =============================================================================
//
// GENERATED by tools/gen-compare.js from isa/fructus.toml.  Do not edit; edit
// the spec or the generator and run \`npm run rtl\`.
//
// The same two operands as rtl/alu.sv, a condition from rtl/cond.sv, and one
// bit out.  Two modes:
//
//   subtract   the condition on the flags of rhs - lhs
//              ${served.subtract.join('; ')}
//   mask       eq or ne on lhs & rhs being zero
//              ${served.mask.join('; ')}
//
// The mode is rtl/cond.sv's \`mask\`, which is its source field's bit 1: the
// fixed eq and ne sources serve exactly the two mask branches.  So choosing the
// mode costs the microcode nothing.
//
// IT IS NOT THE ALU, and that is the point.  Nothing here reaches a register;
// \`taken\` goes to the branch logic and nowhere else, so the carry chain, the
// flags and the condition logic lengthen no path but their own.  iseq and isset,
// which answer a bit into a register, are ALU operations - and need no carry.
//
// THE CONDITION LOGIC is laid out on cond3's order - lt lo le ls eq ne vs vc:
//
//     lt  N ^ V        le  lt | Z        eq  Z        vs  V
//     lo  ~C           ls  lo | Z        ne  ~Z       vc  ~V
//
// so bit 0 of the first four picks unsigned and bit 1 adds Z, and in the last
// four bit 1 picks V over Z and bit 0 inverts.  \`neg\` inverts once more, for
// the packed branch's mirrored entries; see rtl/cond.sv.
//
// Z DOES NOT WAIT FOR THE CARRY CHAIN.  rhs - lhs is zero exactly when the two
// are equal, so the subtract mode's Z is the NOR of lhs ^ rhs, beside the adder
// rather than after it; the mask mode's is the NOR of lhs & rhs.
//
// MEASURED - see rtl/alu.sv, which has the numbers for both units.
// =============================================================================

module compare (
    input  logic [15:0] lhs,     // register file port A: rtl/lhs.sv
    input  logic [15:0] rhs,     // rtl/rhs.sv
    input  logic [2:0]  cond,    // rtl/cond.sv: a cond3 index
    input  logic        neg,     // rtl/cond.sv: invert the answer
    input  logic        mask,    // rtl/cond.sv: test lhs & rhs rather than subtract
    output logic        taken    // -> the branch logic
);

    // --- rhs - lhs, for its flags only ---------------------------------------
    wire [16:0] s = {1'b0, rhs} + {1'b0, ~lhs} + 17'd1;
    wire c = s[16];                                   // no borrow: rhs >= lhs
    wire n = s[15];
    wire v = (rhs[15] ^ lhs[15]) & (rhs[15] ^ s[15]);
    wire z = mask ? ~|(lhs & rhs) : ~|(lhs ^ rhs);

    // --- the condition -------------------------------------------------------
    wire ord  = cond[0] ? ~c : n ^ v;
    wire base = cond[2] ? (cond[1] ? v : z) : (ord | (cond[1] & z));
    assign taken = base ^ (cond[2] & cond[0]) ^ neg;

endmodule
`);
