#!/usr/bin/env node
// =============================================================================
// gen-opcodes.js - the binutils opcode table, from isa/fructus.toml
// =============================================================================
//
//   node tools/gen-opcodes.js --header > vendor/binutils-gdb/include/opcode/fructus.h
//   node tools/gen-opcodes.js --table  > vendor/binutils-gdb/opcodes/fructus-opc.c
//
// opcodes/ is the library gas and the disassembler SHARE, so this table is the
// one place binutils learns what an instruction is.  Generating it from the
// spec is what keeps gas, customasm, the simulator and the RTL describing the
// same machine - the fourth consumer of one file, after gen-customasm.js,
// gen-opcode-map.js and the rtl/ generators.
//
// WHAT THE TABLE HOLDS, and why it is only four fields.  Fructus commits to
// `length_from_first_byte`: the length of an instruction is a function of byte
// 0 alone, so a disassembler needs no lookahead and the table is flat - 256
// entries, indexed directly, no form bits to mask out.  moxie needs three
// tables keyed by form; this needs one.
//
//   length   1, 2 or 3
//   itype    the operand LAYOUT, derived from the encoding rather than named
//            by hand - two forms with the same layout get the same itype even
//            when they are different instructions
//   pcrel    whether the immediate is a DISPLACEMENT.  Not part of the itype,
//            because `jmpr rel16` and `jmp abs16` genuinely share a layout -
//            what differs is how to read it, and a printer that misses the
//            difference names the wrong address and looks right doing it
//   name     the mnemonic, or NULL where the opcode is unused
//
// The VALUE TABLES come too, because an index is not a value: byte 1 of
// `add rd, ra, #imm3` holds 6, and what the programmer wrote was `#8`.  A
// disassembler without imm3[] prints the index and lies.
// =============================================================================

import { loadSpec } from './isa.js';
import { buildDecoder } from './decode.js';

const spec = loadSpec();
const { table } = buildDecoder(spec);
const mode = process.argv.includes('--header') ? 'header' : 'table';

// --- the itypes, derived ------------------------------------------------------
// An itype is the sorted list of ENCODED operand types.  Sorted so that two
// forms differing only in the order they happen to list operands collapse, and
// encoded rather than logical so that `#off` at 3 bits and `#off` at 10 bits are
// different layouts - which they are, to anything that has to decode them.
const sigOf = (c) => {
  const parts = [...c.slices.keys()].map((op) => c.encType.get(op)).sort();
  return `${c.nbytes}B_${parts.join('_') || 'none'}`;
};
const itypeName = (sig) => 'FRUCTUS_' + sig.toUpperCase().replace(/[^A-Z0-9]/g, '_');

const sigs = new Set();
for (let b = 0; b < 256; b++) if (table[b][0]) sigs.add(sigOf(table[b][0]));
const ordered = [...sigs].sort();

// --- value tables -------------------------------------------------------------
const t = spec.optype;
const u16 = (v) => (v >>> 0) & 0xffff;
const arr = (name, vals, fmt = (v) => `0x${u16(v).toString(16).padStart(4, '0')}`) =>
  `const unsigned short ${name}[${vals.length}] =\n  {\n` +
  vals.map((v, i) => `    ${fmt(v)}${i < vals.length - 1 ? ',' : ' '}`).join('\n') +
  `\n  };\n`;

const banner = `/* Fructus opcode table.

   GENERATED by tools/gen-opcodes.js from isa/fructus.toml.  Do not edit; edit
   the spec and run \`npm run binutils\`.

   This file is part of the GNU Binutils.  It is free software; you can
   redistribute it and/or modify it under the terms of the GNU General Public
   License as published by the Free Software Foundation; either version 3, or
   (at your option) any later version.  */

`;

if (mode === 'header') {
  process.stdout.write(`${banner}#ifndef _FRUCTUS_H_
#define _FRUCTUS_H_

/* Every instruction's length is a function of its FIRST BYTE alone - that is a
   documented commitment of the ISA, not an accident of the current encoding -
   so this table is flat and indexed directly by that byte.  An unused opcode
   has a NULL name and a length of 0.  */

typedef struct fructus_opc_info_t
{
  unsigned char  length;    /* 1, 2 or 3; 0 if the opcode is unused */
  unsigned char  itype;     /* operand layout - one of the FRUCTUS_* below */
  unsigned char  pcrel;     /* 1 if its immediate is a DISPLACEMENT */
  const char *   name;      /* mnemonic, or NULL */
} fructus_opc_info_t;

/* WHY pcrel IS A FIELD AND NOT PART OF THE itype.  An itype is a bit LAYOUT,
   and \`jmpr rel16' and \`jmp abs16' have the same one: a whole opcode byte then
   a 16-bit immediate, low byte first.  What differs is what the immediate
   MEANS, and a disassembler that ignores the difference prints the raw
   displacement where an address belongs - a listing that looks right and names
   the wrong place.  Two itypes would say the layouts differ, which would be a
   lie; this says the layouts are the same and the reading is not.  */

extern const fructus_opc_info_t fructus_opc_info[256];

/* The operand layouts, derived from the encodings rather than named by hand.
   Two forms with the same layout share an itype even when they are different
   instructions, which is exactly what a disassembler wants: the layout decides
   how to print, the name decides what to call it.  */

enum fructus_itype
{
  FRUCTUS_UNUSED = 0,
${ordered.map((s, i) => `  ${itypeName(s).padEnd(30)} = ${i + 1}${i < ordered.length - 1 ? ',' : ''}`).join('\n')}
};

/* An INDEX IS NOT A VALUE.  Byte 1 of \`add rd, ra, #imm3\` holds 6 and the
   programmer wrote #8; a disassembler without these tables prints the index and
   lies.  imm3 and shift3 are the same bits read through different tables, which
   is why both are here.  */

extern const unsigned short fructus_imm3[8];
extern const unsigned short fructus_shift3[8];
extern const unsigned short fructus_immbit5[32];
extern const unsigned short fructus_immask5[32];

/* condimm5 packs a CONDITION and a CONSTANT into five bits.  Both halves are
   needed to print one, so they come as parallel arrays.  */
extern const char * const  fructus_condimm5_cond[32];
extern const short         fructus_condimm5_imm[32];

extern const char * const  fructus_reg_names[8];
extern const char * const  fructus_cond_names[8];

#endif /* _FRUCTUS_H_ */
`);
} else {
  const rows = [];
  for (let b = 0; b < 256; b++) {
    const c = table[b][0];
    const hex = `0x${b.toString(16).padStart(2, '0')}`;
    if (!c) { rows.push(`    { 0, FRUCTUS_UNUSED, 0, NULL },${' '.repeat(8)}/* ${hex} */`); continue; }
    const pcrel = (c.insn.operands ?? []).some((o) => o.pcrel && c.slices.has(o.name)) ? 1 : 0;
    rows.push(`    { ${c.nbytes}, ${itypeName(sigOf(c))}, ${pcrel}, "${c.insn.mnemonic}" },`
            + ` `.repeat(Math.max(1, 41 - itypeName(sigOf(c)).length - c.insn.mnemonic.length))
            + `/* ${hex} */`);
  }
  const cd = t.condimm5.values;
  process.stdout.write(`${banner}#include "sysdep.h"
#include "opcode/fructus.h"

const fructus_opc_info_t fructus_opc_info[256] =
  {
${rows.join('\n')}
  };

${arr('fructus_imm3', t.imm3.values)}
${arr('fructus_shift3', t.shift3.values)}
${arr('fructus_immbit5', t.immbit5.values)}
${arr('fructus_immask5', t.immask5.values)}
const char * const fructus_condimm5_cond[32] =
  {
${cd.map((e, i) => `    "${e[0]}"${i < cd.length - 1 ? ',' : ' '}`).join('\n')}
  };

const short fructus_condimm5_imm[32] =
  {
${cd.map((e, i) => `    ${e[1]}${i < cd.length - 1 ? ',' : ' '}`).join('\n')}
  };

const char * const fructus_reg_names[8] =
  { ${t.reg.names.map((n) => `"${n}"`).join(', ')} };

const char * const fructus_cond_names[8] =
  { ${t.cond3.names.map((n) => `"${n}"`).join(', ')} };
`);
}
