#!/usr/bin/env node
// =============================================================================
// gen-alu.js - the ALU and its operation code, from isa/fructus.toml
// =============================================================================
//
//   node tools/gen-alu.js > rtl/alu.sv
//
// The operation is a four-bit microcode field; the spec says nothing may decode
// it from the opcode byte.  What the spec does decide is which operation each
// instruction needs, and this generator works that out from every instruction's
// `semantics`.  An instruction whose semantics matches no operation - and is not
// listed as served elsewhere - makes the generator fail, so a new instruction
// cannot arrive without an answer to "which operation".
//
// Branch decisions are not the ALU's: rtl/compare.sv takes the same operands
// and answers them.
// =============================================================================

import { loadSpec } from './isa.js';
import { ALU_OPS as OPS, ALU_RULES as RULES, ALU_ELSEWHERE as ELSEWHERE, ALU_LATER as LATER, unaryLayout } from './control.js';

const UNARY = unaryLayout();

const spec = loadSpec();


const uses = new Map(OPS.map((o) => [o.name, []]));
const skipped = [];
for (const insn of spec.insn) {
  const sem = insn.semantics ?? '';
  if (LATER.has(insn.mnemonic)) { if (!skipped.includes(insn.mnemonic)) skipped.push(insn.mnemonic); continue; }
  if (ELSEWHERE.some(([re]) => re.test(sem))) continue;
  const rule = RULES.find(([re]) => re.test(sem));
  if (!rule) throw new Error(`${insn.mnemonic}: no ALU operation matches "${sem}"`);
  const [re, op, note] = rule;
  const name = typeof op === 'function' ? op(sem.match(re), insn) : op;
  const label = note ? `${insn.mnemonic} (${note})` : insn.mnemonic;
  if (!uses.get(name).includes(label)) uses.get(name).push(label);
}
for (const o of OPS) if (!uses.get(o.name).length) throw new Error(`no instruction uses ${o.name}`);

const wrap = (words, first, indent, width = 79) => {
  const lines = [];
  let cur = first, fresh = true;
  for (const w of words) {
    if (!fresh && cur.length + 1 + w.length > width) { lines.push(cur); cur = indent; fresh = true; }
    cur += (fresh ? '' : ' ') + w;
    fresh = false;
  }
  lines.push(cur);
  return lines.join('\n');
};
const table = OPS.map((o) => `//   ${String(o.code).padStart(2)}  ${o.name.padEnd(6)} ${o.does}\n`
  + wrap(uses.get(o.name).map((u, i, a) => (i < a.length - 1 ? `${u},` : u)).join(' ').split(' '),
         '//            ', '//            ')).join('\n');
const free = [...Array(16).keys()].filter((c) => !OPS.some((o) => o.code === c));

process.stdout.write(`// =============================================================================
// alu.sv - the ALU
// =============================================================================
//
// GENERATED by tools/gen-alu.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run \`npm run rtl\`.
//
// Two sixteen-bit inputs and one sixteen-bit output, as README.md says, and a
// four-bit microcode field for the operation.  Every operation, and the
// instructions whose semantics call for it:
//
${table}
//
//   ${free.join(', ')} are free.  Not yet: ${skipped.join(', ')}.
//
// BRANCHES ARE DECIDED BESIDE THE ALU, NOT IN IT.  rtl/compare.sv takes the
// same two operands and answers one bit that never enters this block's result,
// so nothing here waits for flags.  What stays is what writes a register: iseq
// is the NOR of lhs ^ rhs and isset the OR of lhs & rhs, neither of which needs
// the carry chain, so the only carry left in the ALU is add and rsb's own.
//
// THE SLOW PAIR IS REGISTERED.  clz and popcount are the two deep operations,
// so rtl/unary.sv puts a register behind them: operation 13 reads the result
// computed from the previous cycle's lhs, and the microcode gives those
// instructions the cycle to compute it in - rtl/ucode.sv's SLOW step.  lhs and
// rhs do not change between the two cycles, because the instruction and its
// selects are already in flops.  So no path through them is longer than one
// operand select, a unary pair, and a register.
//
// AND SO IS THE PRODUCT, the same way and for the same reason: operation 14
// reads an SB_MAC16's own register, which the SLOW step fills from lhs and rhs
// and EXEC reads out.  It is PIPELINE_16x16_MULT_REG2, after the adder that
// joins the four 8x8 partial products, so the whole multiply - about 8 ns by
// Lattice's figures, and 4 more getting to the DSP's column - happens in the
// SLOW cycle, and EXEC sees a register at 2 ns clock-to-out.  clk is there
// for these two and nothing else.
//
// THE DSP IS INSTANTIATED, NOT INFERRED.  Given \`always_ff prod <= lhs * rhs\`,
// yosys's -dsp does use one SB_MAC16 - but it moves copies of rtl/cpu.sv's
// operand flops into the DSP as its input registers, so the logic in front
// of those flops, the memory's byte select and the address adder, has to reach
// the DSP's column at the edge of the die as well.  Measured, medians of
// eight seeds: 29.05 MHz by nextpnr and 27.33 by icetime without mul, 26.59
// and 25.11 inferred, 29.48 and 27.69 as it is here - no cost the seeds can
// see.  And -dsp rewrites an instantiated SB_MAC16's registers the same way,
// so nothing may synthesise this with it.  iverilog has no SB_MAC16, and
// simulates the product it computes.
//
// NEITHER TIMER SEES INSIDE IT.  nextpnr-ice40 0.7 has no arcs through
// SB_MAC16 and icetime ignores its register parameters, so the SLOW cycle's
// multiply is checked against Lattice's figures and not measured.
//
// THE CODES FOLLOW THE CIRCUIT.  Code bit 0 is the adder's subtract, so add and
// rsb differ in one wire.  The shifts put their direction in bit 0 and
// arithmetic in bit 1, so asr is 11 and 10 is free.
//
// MEASURED on an iCE40 UP5K, yosys 0.52 -nobram + nextpnr-ice40 0.7, logic
// cells and the median of five placement seeds.  ALONE is registered operands
// into the units and a flop behind each; the DATAPATH is placement A of
// rtl/insn.sv - the instruction and microcode registered, rtl/lhs.sv and
// rtl/rhs.sv reading an 8x16 register file, rtl/cond.sv, the units, flops:
//
//                                              alone             datapath
//     one ALU with the comparison inside       500   37.9 MHz    1061   23.4 MHz
//     THIS FILE alone                          515   45.0        1035   26.5
//     rtl/compare.sv alone                     167   47.1         672   26.0
//     THIS FILE and rtl/compare.sv together    540   45.3        1055   25.2
//
// SEPARATING THEM IS WORTH A FIFTH OF THE ALU'S CLOCK on its own, and a twelfth
// behind the register file, for a second subtractor.  The comparison had set
// the combined ALU's speed: its critical path ran from the subtract, through
// the carry chain, N and V and the condition, to the negate.  Now the ALU's
// path ends at its result mux, and the compare unit has headroom beside it.
//
// BEHIND THE REGISTER FILE THE TWO PATHS ARE LEVEL, at about 26 MHz each, and
// what sets that is in front of both: a bare add in the same place measured
// 38.0.  Reading a register through rtl/lhs.sv and rtl/rhs.sv is the next thing
// to shorten, and rtl/insn.sv's placement C - register addresses from \`view\`
// - is the measured way to do it.
//
// Two shapes were measured and not taken, with the comparison still inside:
// splitting the result mux by speed into an inner mux over xor, or, and, rhs
// and test and an eight-input outer one was no faster and twenty cells bigger,
// because the width of the mux was never what set the clock; and signed lt as
// (signs differ ? rhs[15] : ~C) instead of N ^ V was correct but inside the
// seeds' noise.
// =============================================================================

module alu (
    input  logic        clk,     // for the slow pair and the product only
    input  logic [15:0] lhs,     // register file port A: rtl/lhs.sv
    input  logic [15:0] rhs,     // rtl/rhs.sv
    input  logic [3:0]  op,      // microcode: which operation
    output logic [15:0] y
);

    wire        sub  = op[0];
    wire [15:0] sum  = rhs + (lhs ^ {16{sub}}) + {15'd0, sub};
    wire [15:0] xorv = lhs ^ rhs;
    wire [15:0] andv = lhs & rhs;
    wire [15:0] hiv  = {rhs[7:0], lhs[7:0]};
    wire [3:0]  amt  = rhs[3:0];
    wire [15:0] unf, uns;
    unary u (.clk(clk), .a(lhs), .sel(rhs[${UNARY.wide ? '2:1' : UNARY.selBit}]), .fast(unf), .slow(uns));   // ${UNARY.wide ? 'two bits' : 'a bit'} of the imm3 value
    wire  [15:0] prod;                                   // lhs * rhs, a cycle late
\`ifdef SYNTHESIS
    wire  [31:0] mac_o;
    SB_MAC16 #(
        .A_REG(1'b0), .B_REG(1'b0), .C_REG(1'b0), .D_REG(1'b0),
        .TOP_8x8_MULT_REG(1'b0), .BOT_8x8_MULT_REG(1'b0),
        .PIPELINE_16x16_MULT_REG1(1'b0), .PIPELINE_16x16_MULT_REG2(1'b1),
        .TOPOUTPUT_SELECT(2'b11), .BOTOUTPUT_SELECT(2'b11),
        .TOPADDSUB_LOWERINPUT(2'b10), .TOPADDSUB_UPPERINPUT(1'b1), .TOPADDSUB_CARRYSELECT(2'b11),
        .BOTADDSUB_LOWERINPUT(2'b10), .BOTADDSUB_UPPERINPUT(1'b1), .BOTADDSUB_CARRYSELECT(2'b00),
        .MODE_8x8(1'b0), .A_SIGNED(1'b0), .B_SIGNED(1'b0)
    ) mac (
        .CLK(clk), .CE(1'b1), .A(lhs), .B(rhs), .C(16'd0), .D(16'd0),
        .AHOLD(1'b0), .BHOLD(1'b0), .CHOLD(1'b0), .DHOLD(1'b0),
        .IRSTTOP(1'b0), .IRSTBOT(1'b0), .ORSTTOP(1'b0), .ORSTBOT(1'b0),
        .OLOADTOP(1'b0), .OLOADBOT(1'b0), .ADDSUBTOP(1'b0), .ADDSUBBOT(1'b0),
        .OHOLDTOP(1'b0), .OHOLDBOT(1'b0), .CI(1'b0), .ACCUMCI(1'b0), .SIGNEXTIN(1'b0),
        .O(mac_o), .CO(), .ACCUMCO(), .SIGNEXTOUT()
    );
    assign prod = mac_o[15:0];                           // the low half is all mul keeps
\`else
    logic [15:0] prod_q;
    always_ff @(posedge clk) prod_q <= lhs * rhs;
    assign prod = prod_q;
\`endif

    always_comb case (op)
        4'd0, 4'd1: y = sum;
        4'd2:       y = {15'd0, ~|xorv};
        4'd3:       y = {15'd0, |andv};
        4'd4:       y = xorv;
        4'd5:       y = lhs | rhs;
        4'd6:       y = andv;
        4'd7:       y = rhs;
        4'd8:       y = lhs << amt;
        4'd9:       y = lhs >> amt;
        4'd10:      y = hiv;
        4'd11:      y = $signed(lhs) >>> amt;
        4'd12:      y = unf;
        4'd13:      y = uns;
        4'd14:      y = prod;
        default:    y = 16'hxxxx;
    endcase

endmodule
`);
