#!/usr/bin/env node
// =============================================================================
// gen-isa.js - the facts about the instruction set that rtl/ writes by hand
// =============================================================================
//
//   node tools/gen-isa.js > rtl/isa.svh
//
// rtl/cpu.sv and rtl/alu.sv are written by hand, but a few things in them are
// facts about the instruction set rather than choices about the circuit: the
// exception vector, which registers sp and lr are, and which bit of the
// right-hand immediate chooses each unary operation.  They come from here, as
// macros, so that a change to isa/fructus.toml reaches them by `npm run rtl`.
//
// MACROS AND NOT A PACKAGE, because yosys's mapping answers to the text: every
// macro expands to exactly the expression that was written in its place, and
// the synthesised netlist was compared, and was the same, before and after.
// An equivalent expression written differently can move the processor by a
// MHz or more - see rtl/cpu.sv's header.
//
// WHAT CANNOT BE A MACRO IS CHECKED HERE INSTEAD, and fails `npm run rtl` with
// the place to change:
//
//   - brk is opcode 0, because an interrupt is a brk put in place of the
//     opcode by an AND - rtl/cpu.sv, `op = opraw & ...`;
//   - sp and lr differ only in bit 0, because a routine names them as
//     {`FRUCTUS_REG_SPLR, which} - rtl/cpu.sv, `kreg`;
//   - the unary operations are the five rtl/alu.sv computes, since a new one
//     needs its circuit written whichever bit chooses it.
// =============================================================================

import { loadSpec } from './isa.js';
import { unaryLayout } from './control.js';

const spec = loadSpec();
const fail = (msg) => { throw new Error(`gen-isa.js: ${msg}`); };

// --- the vector and the registers --------------------------------------------------
const vector = spec.cpu.vectors.brk;
const regs = spec.optype.reg;
const reg = (name) => {
  const k = regs.names.indexOf(regs.aliases?.[name] ?? name);
  if (k < 0) fail(`isa/fructus.toml names no register ${name}`);
  return k;
};
const sp = reg('sp'), lr = reg('lr');
if ((sp ^ lr) !== 1 || (sp & 1) !== 0)
  fail(`sp is r${sp} and lr r${lr}: rtl/cpu.sv's kreg names them as {${sp >> 1}, which}, so they must be an even register and the one after it`);

const brkForm = spec.insn.find((i) => i.mnemonic === 'brk')?.form?.[0]?.encoding;
if (!brkForm) fail('isa/fructus.toml has no brk');
const brk = parseInt(brkForm.replace(/[\s_]/g, ''), 2);
if (brk !== 0)
  fail(`brk is opcode 0x${brk.toString(16)}: rtl/cpu.sv makes an interrupt a brk by ANDing the opcode to 0, which must become a mux`);

// --- the unary operations ------------------------------------------------------------
// rtl/alu.sv computes these five; unaryLayout() says which bit of the right-hand
// immediate's bits 2:1 - `usel` - tells them apart.
const u = unaryLayout();
const FAST = ['bitrev', 'clmul', 'sxt8'], SLOW = ['clz', 'popcount'];
const fastHas = [...u.fast, u.fastThird?.mnemonic].filter(Boolean).sort();
const slowHas = [...u.slow, u.slowThird?.mnemonic].filter(Boolean).sort();
if (fastHas.join() !== FAST.join() || slowHas.join() !== SLOW.join())
  fail(`the spec's unary operations are ${fastHas.join(', ')} and, slow, ${slowHas.join(', ')}; `
       + `rtl/alu.sv computes ${FAST.join(', ')} and ${SLOW.join(', ')}`);
const s = u.selBit - 1, o = u.otherBit - 1;     // usel's bit for the pair, and for a third
const bit = (i, level) => (level ? `usel[${i}]` : `~usel[${i}]`);
const fastPair = `usel[${s}] ? ${u.fast[1]} : ${u.fast[0]}`;
const fast = u.fastThird ? `${bit(o, u.fastThird.level)} ? ${u.fastThird.mnemonic} : ${fastPair}` : fastPair;
const pop = u.slow[1] === 'popcount' ? `usel[${s}]` : `~usel[${s}]`;

const hex = (v, w) => v.toString(16).padStart(w, '0');
process.stdout.write(`// =============================================================================
// isa.svh - the facts about the instruction set that rtl/ writes by hand
// =============================================================================
//
// GENERATED by tools/gen-isa.js from isa/fructus.toml.  Do not edit.
//
// brk is opcode 0x${hex(brk, 2)}, and sp and lr are r${sp} and r${lr}: rtl/cpu.sv relies on
// both, and tools/gen-isa.js checks them.
// =============================================================================

\`ifndef FRUCTUS_ISA_SVH
\`define FRUCTUS_ISA_SVH

// [cpu.vectors] brk: where brk and the interrupt line go.
\`define FRUCTUS_VECTOR_BRK 16'h${hex(vector, 4)}

// The registers the exception routines and the block moves name.
\`define FRUCTUS_REG_SP 3'd${sp}
\`define FRUCTUS_REG_LR 3'd${lr}
\`define FRUCTUS_REG_SPLR 2'd${sp >> 1}   // sp and lr but for bit 0, which is 1 for lr

// The fast unary operations, by usel - the right-hand immediate's bits 2:1.
\`define FRUCTUS_UNARY_FAST(usel, bitrev, clmul, sxt8) (${fast})

// The slow pair, clz and popcount: popcount when this is 1.
\`define FRUCTUS_UNARY_POP(usel) (${pop})

\`endif
`);
