#!/usr/bin/env node
// =============================================================================
// gen-rhs.js - the ALU's right-hand-side selector, from isa/fructus.toml
// =============================================================================
//
//   node tools/gen-rhs.js > rtl/rhs.sv
//
// Wraps rtl/immgen.sv with the ONE microcode field that says where the ALU's
// right-hand side comes from this cycle, and with the constants and registers
// the microcode needs when the instruction stream supplies nothing useful.
//
// The encoding is a hardware choice and lives here, not in the spec.  What the
// spec decides - and what this file checks - is that every one-byte
// abbreviation's right-hand side is reachable from it.  See tests/rtl-check.mjs.
// =============================================================================

import { loadSpec } from './isa.js';
import { buildDecoder, decode } from './decode.js';
import { RHS_REG as REG, RHS_IMM16 as IMM16, RHS_PCSUM as PCSUM,
         RHS_KON as KON, RHS_MODE as MODE } from './control.js';

const spec = loadSpec();
const u16 = (v) => (v >>> 0) & 0xffff;


// --- what a one-byte form's right-hand side must be --------------------------
// Every one-byte form pins all its operands, so its right-hand side is a
// constant in `fix`.  A value this field cannot produce means the microcode
// cannot express the instruction, so the generator refuses rather than emitting
// something that cannot work.
{
  const consts = Object.values(KON);
  const regs = Object.keys(REG).map(Number);
  for (const insn of spec.insn)
    for (const form of insn.form ?? []) {
      if ((form.encoding ?? '').replace(/[^01_]/g, '').replace(/_/g, '').length !== 8) continue;
      const fix = form.fix ?? {};
      if ('imm' in fix || 'off' in fix) {
        const v = 'imm' in fix ? fix.imm : fix.off;
        if (!consts.includes(v))
          throw new Error(`${insn.mnemonic}/${form.name}: rhs #${v} is not one of ${consts.join(', ')}`);
      } else if ('b' in fix) {
        if (!regs.includes(fix.b))
          throw new Error(`${insn.mnemonic}/${form.name}: rhs r${fix.b} is not one of r${regs.join(', r')}`);
      }
    }
}

// --- what code 4 must be ------------------------------------------------------
// Every instruction that writes a whole 16-bit constant into a register takes
// it from bytes 1 and 2, low byte first, so the value is insn[23:8] - a slice.
// Checked against the decoder rather than assumed, and the generator refuses to
// emit a code that nothing uses.
{
  const dec = buildDecoder(spec);
  let users = 0;
  for (let op = 0; op < 256; op++) {
    const d = decode(dec, [op, 0, 0], 0);
    if (!d || d.nbytes !== 3 || !/^\s*R\[[a-z]\]\s*=\s*imm\s*$/.test(d.insn.semantics ?? '')) continue;
    users++;
    for (const [b1, b2] of [[0x34, 0x12], [0xff, 0x00], [0x00, 0xff], [0x5a, 0xa5]]) {
      const got = u16(decode(dec, [op, b1, b2], 0).ops.imm);
      if (got !== ((b2 << 8) | b1))
        throw new Error(`0x${op.toString(16)} ${d.insn.mnemonic}/${d.form.name}: bytes ${b1}, ${b2} `
                      + `decode to #${got}, not byte 1 low and byte 2 high`);
    }
  }
  if (!users) throw new Error('nothing loads a 16-bit immediate into a register, so code 4 is unused');
}

const row = (n) => {
  const c = n & 7;
  if (n < 8) return REG[c] ? REG[c]
                  : c === IMM16 ? 'imm16, from the bytes'
                  : c === PCSUM ? 'pc + 2, a call\'s lr'
                  : 'reserved';
  return c in KON ? `#${KON[c]}` : MODE[c];
};
const table = [0, 1, 2, 3, 4, 5, 6, 7]
  .map((i) => `//   ${String(i).padStart(2)}  ${row(i).padEnd(24)}${String(i + 8).padStart(2)}  ${row(i + 8)}`)
  .join('\n');

process.stdout.write(`// =============================================================================
// rhs.sv - what the ALU's right-hand side is this cycle
// =============================================================================
//
// GENERATED by tools/gen-rhs.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run \`npm run rtl\`.
//
// rtl/immgen.sv turns the instruction bytes into a value.  This decides whether
// the ALU gets that, a register, or one of a few constants, from ONE four-bit
// microcode field:
//
${table}
//
// THE ENCODING IS WHY THIS IS NEARLY FREE.  src[3] = 0 is a register and
// src[2:0] IS its number, so \`regnum\` is wiring rather than a lookup; and
// src[3] = 1 reads src[2:0] as a 3-bit SIGNED constant, so \`konst\` is one
// signal fanned out thirteen ways rather than a table.  That is why -2 and -1
// sit at 14 and 15 instead of in numeric order - 110 and 111 ARE -2 and -1 -
// and why the three modes take 011, 100 and 101, the patterns that would have
// meant 3, -4 and -3.
//
// Measured against the four separate control bits this replaces: 149 SB_LUT4
// against 136 bare, but 432 cells against 430 once placed beside a real 8x16
// register file, at the same four LUT levels.  Two cells for a microcode bit.
//
// ONE OF THE RESERVED CODES HAS NOW BEEN SPENT, on the terms this paragraph
// used to set out: 2 and 3 fall in the register half and decode as r2 and r3 by
// accident of the wiring, so a use for either owes a small decode, and not
// before.  Code 2 is that use - a call's return address - and code 3 is still
// r3 by accident and still costs nothing to leave there.
//
// WHY THE PC'S ADDER AND NOT AN INCREMENTER OF ITS OWN.  The adder that
// prepares a relative branch's target is IDLE DURING EVERY CALL: an absolute
// call's target is the instruction's own bytes and a register call's is the
// operand flop.  So a call borrows it with the addend forced to 1 and gets
// pc + 2, which is the address after the call, for no adder at all.
//
// The point is not the cells, it is where the mux ends up.  The return address
// used to reach the register file through a mux ON THE WRITE PORT, which sits
// at the end of the ALU's path and lengthened it for every instruction, not
// just calls.  Here it is one arm of a mux that was already there, on the side
// of rhs that settles a cycle early.  MEASURED on the whole processor, medians
// of eight placement seeds: 1013 cells and 29.67 MHz with the write-port mux,
// 1004 and 32.95 with the return address arriving as an operand instead.
//
// CODE 4 IS THAT SMALL DECODE, spent on the 16-bit immediate.  \`mov rd, #imm16\`
// cannot use immgen: its opcode[2:0] is the destination register, not a column,
// so immgen's mode there depends on which register is loaded.  The value is
// bytes 1 and 2, low first - insn[23:8], wiring.  The generator checks that
// against the decoder.  What it costs:
//
//   use_reg gains a term but no input - it already depended on all four bits
//     of src, because of port B;
//   the value joins the constants, not the register value, so the new mux sits
//     on the side of rhs that is already early;
//   regnum does not change - code 4 is not a register, so its number is a
//     don't-care, and the wiring's r4 is harmless.
//
// It does not need an ALU operation of its own either: it rides the same
// pass-through the short movs use.
//
// MEASURED against the file without it, same harness - an 8x16 register file
// read through port B, -nobram, medians of five placement seeds, on the
// shifting immreg this file then read:
//
//                         rhs -> flop                 rhs + add -> flop
//     without code 4      475 cells  4 levels  54.9   494 cells  38.2 MHz
//     with it             505 cells  4 levels  56.9   505 cells  37.5 MHz
//
// No level, and no clock beyond the two or three MHz the seeds wander by.  The
// cells are thirty rather than the sixteen a 2:1 mux predicts - probably
// because \`lit\` is no longer just the code bits fanned out, which ABC could fold
// into the final mux for nothing; not confirmed.
//
// MOVING TO THE 24-BIT REGISTER changed only wiring, and measured as such:
// 498 cells and 57.2 MHz on immreg against 505 and 57.7 on insn.sv, and 37.3
// against 37.0 through the add - noise both ways.
//
// AND THE CONSTANTS ARE EXACTLY WHAT THE ONE-BYTE OPCODES NEED.  Every one-byte
// form pins all its operands, so each has a fixed right-hand side, and all of
// them land inside this set: #0 for the two implicit loads and the three movs,
// #1 #-1 #2 for the r0 increments, r1 and r0 for the two one-byte adds, and lr
// for ret.  The generator FAILS on a one-byte form whose right-hand side it
// cannot produce, because an abbreviation the microcode cannot express is not
// an abbreviation.
//
// regnum COMES OFF THE INSTRUCTION BYTES, not out of immgen, which is why
// immgen drives x at +6 and +7 rather than putting the same three bits on its
// output.  Sourcing it from immgen would put the whole immediate unit in front
// of the register file: six LUT levels and 31 MHz, against four and 38 here,
// because the file's read now overlaps immgen entirely.
// =============================================================================

module rhs (
    input  logic [23:0] insn,    // the instruction, byte 0 low: rtl/insn.sv
    input  logic [3:0]  src,     // microcode: where the right-hand side comes from
    input  logic [15:0] regval,  // register file port B, addressed by regnum
    input  logic [15:0] pcsum,   // rtl/cpu.sv's pc adder, before its flop
    output logic [2:0]  regnum,  // -> register file port B address
    output logic [15:0] value    // not \`rhs\`: a port named after its module
                                 // is an error to verilator
);

    wire [2:0] c = src[2:0];

    wire use_reg = (~src[3] & c != 3'd${IMM16} & c != 3'd${PCSUM})
                 | (src[3] & c == 3'd${Object.keys(MODE).find((k) => MODE[k].startsWith('port B'))});
    wire use_imm = src[3] & (c == 3'd${Object.keys(MODE).find((k) => MODE[k] === 'immgen, normal')}
                           | c == 3'd${Object.keys(MODE).find((k) => MODE[k].endsWith('condimm5'))});
    wire cimm    = src[3] & (c == 3'd${Object.keys(MODE).find((k) => MODE[k].endsWith('condimm5'))});

    wire [15:0] konst = {{13{c[2]}}, c};        // the code bits, sign extended

    wire [15:0] imm;
    immgen g (.insn(insn), .cimm(cimm), .imm(imm));

    // regnum only matters when a register is selected, so codes 8..15 other
    // than port B are don't-cares and one 3-bit mux serves both halves.
    wire [2:0] k3 = {insn[15:14], insn[0]};
    assign regnum = src[3] ? k3 : c;

    // imm16 joins the constants rather than the register value: both are flop
    // outputs, so this mux is on the side of rhs that arrives early.
    wire [15:0] imm16 = insn[23:8];             // byte 1 low, byte 2 high
    wire [15:0] low   = (c == 3'd${PCSUM}) ? pcsum : imm16;
    wire [15:0] lit   = src[3] ? konst : low;

    assign value = use_reg ? regval : (use_imm ? imm : lit);

endmodule
`);
