#!/usr/bin/env node
// =============================================================================
// gen-unary.js - the unary ALU, from isa/fructus.toml
// =============================================================================
//
//   node tools/gen-unary.js > rtl/unary.sv
//
// The eight-way unary block: sxt8, zxt8, clz, bitrev and popcount, plus three
// free slots.  The OPERATIONS are hand-written below - they are real hardware
// and the spec describes what they compute, not how - but the SELECTOR TABLE is
// read out of the encodings, so an operation cannot be added to the spec
// without this file either implementing it or refusing to run.
// =============================================================================

import { loadSpec } from './isa.js';

const spec = loadSpec();

// --- who sits at which selector ---------------------------------------------
// byte 0 is 0011_101s and byte 1 is ddda_aass, so the selector is
// {byte1[1:0], opcode[0]} - which is the same three bits that carry ALU port B
// and the imm3 index everywhere else in the map.
const slots = new Map();
for (const insn of spec.insn)
  for (const form of insn.form ?? []) {
    const bits = (form.encoding ?? '').replace(/[\s_]/g, '');
    if (bits.length !== 16 || !/^0011101[01]ddda?aa?[01][01]$/.test(bits.replace(/aa/, 'aa'))) continue;
    if (!/^0011101[01]/.test(bits)) continue;
    const s = Number(bits[7]);
    const ss = parseInt(bits.slice(14, 16), 2);
    if (Number.isNaN(ss)) continue;
    const sel = (ss << 1) | s;
    if (slots.has(sel)) throw new Error(`unary selector ${sel} claimed twice`);
    slots.set(sel, insn.mnemonic);
  }

// --- what this file knows how to build --------------------------------------
const IMPL = {
  sxt8:     'sxt',
  zxt8:     'zxt',
  bitrev:   'rev',
  clz:      '{11\'d0, cl}',
  popcount: '{11\'d0, pc}',
};
for (const [sel, m] of slots)
  if (!(m in IMPL)) throw new Error(`unary selector ${sel} is '${m}', which rtl/unary.sv does not implement`);

const rows = [...slots].sort((a, b) => a[0] - b[0])
  .map(([sel, m]) => `        3'd${sel}: y = ${IMPL[m]};${' '.repeat(Math.max(1, 18 - IMPL[m].length))}// ${m}`)
  .join('\n');
const listed = [...slots].sort((a, b) => a[0] - b[0]).map(([s, m]) => `//   ${s}  ${m}`).join('\n');

// popcount's nibble table and clz's priority encoder, both written out here so
// the file has no dependencies.
const pcRows = [...Array(16).keys()]
  .map((n) => `        4'h${n.toString(16)}: ${'pcn'} = 3'd${n.toString(2).split('').filter((c) => c === '1').length};`)
  .join('\n');
const clzRows = [...Array(16).keys()].map((i) => {
  const pat = '0'.repeat(i) + '1' + '?'.repeat(15 - i);
  return `        16'b${pat}: cl = 5'd${i};`;
}).join('\n');

process.stdout.write(`// =============================================================================
// unary.sv - the unary ALU
// =============================================================================
//
// GENERATED by tools/gen-unary.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run \`npm run rtl\`.
//
// Eight selector values, five of them used:
//
${listed}
//
// The selector is {byte1[1:0], opcode[0]} - the same three bits that carry ALU
// port B and the imm3 index everywhere else, so the field needs no decode of
// its own.  The operations are hand-written; only the table above is generated,
// which is what makes adding an operation to the spec fail here rather than
// silently produce a block that does not implement it.
//
// TWO OF THE FIVE ARE FREE.  bitrev is wiring and nothing else - a permutation
// of sixteen nets - and sxt8/zxt8 are a fanout and a constant.  So the block's
// entire cost and depth is clz and popcount, plus the mux.
//
// clz IS THE PRIORITY ENCODER, not the nibble-and-NOR version.  The nibble one
// is smaller - 21 SB_LUT4 against 31 - but it is five LUT levels against four,
// and depth is the budget worth defending here: measured on its own the block
// is 8.1 ns of logic and 10.6 ns of ROUTING, and the unary ALU sits further
// from the register file than the main ALU does.
//
// AND clz(0) = 16 IS A REAL COST, kept deliberately.  gcc leaves
// __builtin_clz(0) undefined, and leaving it undefined here would drop the
// answer from five bits to four, taking the 16-input NOR that produces bit 4
// with it: measured, 4 LUT levels and 62.7 MHz becomes 3 levels and 84.1 MHz.
// That is 34% of the clock for a case software can paper over in one \`br eq\`.
// It is not taken because an instruction whose result depends on how it was
// reached is a bad thing to have in an ISA - but if clz ever turns out to set
// this block's depth, that is where the headroom is.
//
// THE SELECTOR COULD BE THE ALU'S OWN RIGHT-HAND SIDE, and that is worth
// recording even though it is not what this file does yet.  The unary forms sit
// in the imm3 columns, so the three selector bits are also an imm3 INDEX, and
// rtl/immgen.sv already turns that index into a value on the rhs bus:
//
//     index   0    1    2    3    4    5    6    7
//     value  -1    0    1    2    3    4    6    8
//     low 3   7    0    1    2    3    4    6    0   <- 7 collides with 1
//
// Seven of the eight give distinct low three bits, so up to SEVEN operations
// can be selected by rhs[2:0] with no selector wires at all - the unary block
// would take exactly the two inputs every other ALU operation takes, lhs and
// rhs, and need nothing else routed to it.
//
// IT LOOKS FREE AND IS NOT.  Measured with the whole right-hand-side chain in
// both harnesses, so the only difference is where the selector comes from:
//
//     selector off the instruction register   342 cells   5 levels   49.2 MHz
//     selector off the rhs bus                334 cells   7 levels   38.4 MHz
//
// Eight cells for two LUT levels.  The reasoning that says it should be free -
// rhs is four levels away, the unary operations are four levels from lhs, so
// the mux lands at five either way - misses that the mux is TWO levels for a
// five-way 16-bit select, and that with the selector arriving at level zero
// ABC folds its first level into the logic producing the data.  clz's final
// encoder LUT can compute "my value, already gated by whether clz is selected",
// because the selector is a spare input at that point.  Arriving at level four
// it cannot, and the mux becomes two levels bolted on the end.
//
// Which is the same rule that put cimm in the microcode word rather than
// decoding it here: a control signal that arrives EARLY gets absorbed, one that
// arrives LATE gets added.  Three selector wires from the instruction register
// are not the cost; the folding they permit is worth two levels.
//
// popcount TAKES THE TOP BIT OUT OF THE ADDER.  A nibble count's bit 2 is set
// only for 1111, and then its low bits are zero - so the total reaches 16 only
// when all four nibbles are full, and y[4] is the AND of the four high bits
// rather than a carry out.  That shortens the final ripple from three steps to
// one: 86 MHz against 70, for one more LUT and one fewer carry cell.
// =============================================================================

module unary (
    input  logic [15:0] a,
    input  logic [2:0]  sel,     // {byte1[1:0], opcode[0]}
    output logic [15:0] y
);

    // --- wiring -------------------------------------------------------------
    wire [15:0] sxt = {{8{a[7]}}, a[7:0]};
    wire [15:0] zxt = {8'd0, a[7:0]};
    wire [15:0] rev = { a[0],  a[1],  a[2],  a[3],  a[4],  a[5],  a[6],  a[7],
                        a[8],  a[9],  a[10], a[11], a[12], a[13], a[14], a[15] };

    // --- clz: one flat priority encoder -------------------------------------
    logic [4:0] cl;
    always_comb casez (a)
${clzRows}
        default:  cl = 5'd16;                   // a == 0
    endcase

    // --- popcount: four nibble counts, then two adds and an AND -------------
    function automatic [2:0] cnt4(input [3:0] n);
        case (n)
${pcRows.replace(/pcn/g, 'cnt4')}
        endcase
    endfunction
    wire [2:0] p0 = cnt4(a[3:0]),   p1 = cnt4(a[7:4]);
    wire [2:0] p2 = cnt4(a[11:8]),  p3 = cnt4(a[15:12]);
    wire [3:0] s01 = p0 + p1;
    wire [3:0] s23 = p2 + p3;
    wire [4:0] pc = {p0[2] & p1[2] & p2[2] & p3[2], s01[3:0] + s23[3:0]};

    // --- the mux ------------------------------------------------------------
    always_comb case (sel)
${rows}
        default: y = 16'hxxxx;                  // the three free selectors
    endcase

endmodule
`);
