#!/usr/bin/env node
// =============================================================================
// gen-rhs.js - the ALU's right-hand-side selector, from isa/fructus.toml
// =============================================================================
//
//   node tools/gen-rhs.js > rtl/rhs.sv
//
// Wraps rtl/immgen.sv with the four microcode lines that say how to READ its
// output, and with the small set of constants the microcode needs when the
// instruction stream supplies nothing useful.
//
// The constant set is a hardware choice and lives here, not in the spec.  What
// the spec decides - and what this file checks - is that every one-byte
// abbreviation's right-hand side is reachable from it.  See tests/rtl-check.mjs.
// =============================================================================

import { loadSpec } from './isa.js';

const spec = loadSpec();

// --- the override constants -------------------------------------------------
// Four values, two microcode bits.  See the module header for why these four.
const K = [-1, 0, 1, 2];
const u16 = (v) => (v >>> 0) & 0xffff;

// A one-byte form pins every operand, so its right-hand side is a constant in
// `fix`.  Any such value must be producible, or the microcode cannot express
// the instruction - which is a spec-level constraint on adding abbreviations,
// so the generator refuses rather than emitting something that cannot work.
{
  const regs = K.map((v) => u16(v) & 7);
  for (const insn of spec.insn)
    for (const form of insn.form ?? []) {
      const enc = (form.encoding ?? '').replace(/[^01_a-z]/g, '');
      if (enc.replace(/_/g, '').length !== 8) continue;      // one byte only
      const fix = form.fix ?? {};
      if ('imm' in fix || 'off' in fix) {
        const v = 'imm' in fix ? fix.imm : fix.off;
        if (!K.includes(v))
          throw new Error(`${insn.mnemonic}/${form.name}: rhs #${v} is not one of ${K.join(', ')}`);
      } else if ('b' in fix) {
        if (!regs.includes(fix.b))
          throw new Error(`${insn.mnemonic}/${form.name}: rhs r${fix.b} is not one of r${regs.join(', r')}`);
      }
    }
}

const hex16 = (v) => `16'h${u16(v).toString(16).padStart(4, '0')}`;

process.stdout.write(`// =============================================================================
// rhs.sv - what the ALU's right-hand side is this cycle
// =============================================================================
//
// GENERATED by tools/gen-rhs.js from isa/fructus.toml.  Do not edit; edit the
// spec or the generator and run \`npm run rtl\`.
//
// rtl/immgen.sv turns the instruction bytes into either a value or a register
// number; this decides which of those the ALU gets, and lets the microcode
// override both with a small fixed set.  FOUR MICROCODE LINES:
//
//     k_use     take the constant below instead of immgen's output
//     k[1:0]    which one: ${K.map((v) => `#${v}`).join(', ')}
//     as_reg    what came out is a register NUMBER; use the file's port B
//
// THE REGISTER OVERRIDES COME FREE, which is the whole reason for this shape.
// The four constants are ${K.map((v) => hex16(v)).join(', ')}, and their low
// three bits are ${K.map((v) => 'r' + (u16(v) & 7)).join(', ')} - so the SAME
// two microcode bits that pick a constant pick a register, and \`as_reg\` says
// which of the two readings applies.  No separate register-override field
// exists.  r7 is lr, so this is also how the microcode reaches the link
// register for ret and call.
//
// AND THE SET IS EXACTLY WHAT THE ONE-BYTE OPCODES NEED.  Every one-byte form
// pins all its operands, so each has a fixed right-hand side:
//
//     ld r0, [r0, #0]   #0        add r0, r0, r1    r1
//     ld8 r0, [r0, #0]  #0        add r1, r1, r0    r0
//     add r0, r0, #1    #1        or  r0, r1, #0    #0
//     add r0, r0, #-1   #-1       or  r1, r0, #0    #0
//     add r0, r0, #2    #2        mov r0, #0        #0
//     ret               lr = r7
//
// Nothing needs a value outside the set and r2 is spare.  The generator FAILS
// if a new one-byte form breaks that, because an abbreviation the microcode
// cannot express is not an abbreviation.
//
// (The four constants are also imm3[0..3], which is a coincidence rather than a
// dependency - but it means the imm3 table could generate them if the sixteen
// LUTs below ever mattered.  They do not: this whole module is 38 LUT4 on top
// of immgen's 81.)
//
// regnum COMES OFF THE INSTRUCTION BYTES DIRECTLY, not off the selected value,
// even though immgen's +6/+7 output has the same three bits in it.  Taking it
// from immgen would put the whole immediate unit in front of the register file:
// measured with a real 8x16 file behind it, that is six LUT levels and 31 MHz
// against four levels and 37 MHz for the version below, because here the file's
// read overlaps immgen entirely instead of waiting for it.
// =============================================================================

module rhs (
    input  logic [15:0] ir,      // immreg: the last two instruction bytes
    input  logic [2:0]  sel,     // opcode[2:0]
    input  logic        k_use,   // microcode: use the constant, not immgen
    input  logic [1:0]  k,       // microcode: which constant
    input  logic        as_reg,  // microcode: read it as a register number
    input  logic [15:0] regval,  // register file port B, addressed by regnum
    output logic [2:0]  regnum,  // -> register file port B address
    output logic [15:0] rhs
);

    wire [15:0] imm;
    immgen g (.ir(ir), .sel(sel), .imm(imm));

    logic [15:0] konst;
    always_comb case (k)
${K.map((v, n) => `        2'd${n}: konst = ${hex16(v)};`).join('\n')}
    endcase

    // Port B's register number, straight off the bytes - the same three bits
    // immgen puts on its output at +6 and +7, taken a level earlier.
    wire [2:0] k3 = {ir[1:0], sel[0]};
    assign regnum = k_use ? konst[2:0] : k3;

    assign rhs = as_reg ? regval : (k_use ? konst : imm);

endmodule
`);
