#!/usr/bin/env node
// =============================================================================
// gen-cpu.js - the processor, as far as it goes
// =============================================================================
//
//   node tools/gen-cpu.js > rtl/cpu.sv
//
// The top level that joins the generated blocks into something that runs
// programs: the pc, rtl/insn.sv, rtl/predecode.sv, rtl/ucode.sv, the operand
// selects, the ALU, the destination and the register file.  Memory is outside
// it, behind a synchronous-read address and byte.  It holds no rules of its
// own - everything it decides is decided in the blocks - so this generator only
// writes the wiring, and exists so that rtl/ stays generated throughout.
// =============================================================================

import { RHS_PCSUM as PCSUM, DEST_FIELD } from './control.js';

// The microcode's overrides name a field; these are the codes those fields
// have in rtl/lhs.sv and rtl/dest.sv.  Port B's is 10 on port A and 11 on the
// write port, because the two blocks number their fields differently.
const destOf  = (what) => Number(Object.keys(DEST_FIELD).find((k) => DEST_FIELD[k].name === what));
const DEST_RD = destOf('rd field'), DEST_RA = destOf('ra field'), DEST_B = destOf('port B field');

process.stdout.write(`// =============================================================================
// cpu.sv - the processor, as far as it goes
// =============================================================================
//
// GENERATED by tools/gen-cpu.js.  Do not edit; edit the generator and run
// \`npm run rtl\`.
//
// What runs: whatever rtl/ucode.sv implements, which is now EVERY INSTRUCTION
// IN THE ISA BUT ONE.  Every instruction whose effect is one ALU result written
// to one register; the transfers of control; the loads and stores, at both
// widths and in every addressing form; the block moves - push, pop, and the
// post-updating stm and ldm; and halt and nop.
//
// br8 is the exception, and by decision rather than oversight: see
// tools/control.js's ALU_LATER, which is the list of one it now holds.
//
// MEMORY IS OUTSIDE, as a synchronous read: \`mem_addr\` is sampled at the clock
// edge and the byte at that address is on \`mem_rdata\` for the following cycle.
// That is the UP5K's SPRAM and the 6502-like bus the cost model describes: one
// cycle per byte.
//
// THE pc IS THE ADDRESS OF THE BYTE ON THE BUS.  A step that consumes that byte
// - a fetch or a dispatch - presents pc + 1 at the edge that ends it, so the
// following byte arrives for the next step; one that consumes nothing presents
// pc again.  Reset presents 0, so the first word after it finds address 0's
// byte on the bus and dispatches it.
//
// \`result\` IS THE ALU'S OUTPUT, and it is now a port for the test benches
// rather than for the design.  It was added when nothing here could reach
// memory: the register file fed only the ALU and the ALU only the register
// file, and a synthesis tool is entitled to remove a loop nothing observes.
// The stores gave the datapath an output of its own on mem_wdata, so that loop
// is observed now whether this port exists or not.
//
// THE REGISTER FILE IS FLOPS AND MUXES, never block RAM: its two reads are
// asynchronous, which the part's block RAM is not.  The attribute says so,
// because the ROM beside it is block RAM and synthesis is left free to infer.
//
// THE OPERANDS ARE READ A CYCLE BEFORE THEY ARE USED, which is where the clock
// comes from.  rtl/lhs.sv, rtl/rhs.sv and rtl/immgen.sv read \`view\` - the
// instruction with this cycle's byte already in place - so an instruction's
// last fetch cycle also selects, reads and latches both ALU inputs.  The
// execute cycle is then flops -> ALU -> result mux -> register file, with the
// register read out of it entirely.
//
// NO FORWARDING IS NEEDED, and that is a property of the sequencing rather than
// luck.  Every instruction has a cycle between its dispatch and its execute -
// a fetch for the multi-byte forms, an entry word that fetches nothing for the
// one-byte ones - and the previous write lands at the edge that begins it.
// So a read never shares a cycle with the write it must see.  An instruction
// that executed in its dispatch cycle would need a bypass from the ALU result
// into these flops, which measured 5 MHz slower than the extra cycle costs.
//
// MEMORY HAS AN ADDER OF ITS OWN, and it is not a luxury: a load's bytes come
// back through the ALU, so the ALU cannot also be adding \`R[a] + off\` while
// they do.  The address unit is that adder - the two operand flops, or its own
// last address and one of three constants - and it walks an access upwards a
// byte at a time from wherever it started, so one adder serves any width.  THE
// pc STANDS STILL while it drives the bus, because what is on the bus then is
// data and not an instruction byte.
//
// SO AN ACCESS COSTS ONE CYCLE MORE THAN ITS BYTES AND ITS DATA, for that add.
// The alternative is to add the address in the cycle its last byte arrives -
// out of the register file, through rtl/immgen.sv and an adder, into the
// memory's address pins - which costs no cycles and puts the exact path the
// early operand read was introduced to remove in front of the memory instead.
// MEASURED, medians of eight placement seeds, real SB_SPRAM256KA:
//
//                                          RAM   LUT4   levels     MHz
//     no memory unit at all                   2   1008    7 -  8   32.34
//     THE ADDRESS A CYCLE LATER, as here      3   1141    8 -  9   28.95
//     the address in the fetch cycle          3   1141   21 - 24   20.54
//
// A third of the clock against one cycle on the accesses alone, and the cycle
// is much the cheaper of the two.  THE LAST TWO ROWS ARE THE SAME CELLS - 1141
// LUT4 and 1367 logic cells either way - so this is not a question of how much
// hardware an address costs but of WHERE THE ADDER SITS.  In the third row it
// sits in front of the memory's address pins, and the path ends where it was
// always going to end: at the address bus, three times as deep for it.
//
// The third block RAM is the microcode word, which the memory control took from
// 16 bits to 25.
//
// THE BYTES COMING BACK SHIFT INTO THE RIGHT-HAND OPERAND FLOP, low byte first,
// so a 16-bit value assembles itself in place and rtl/alu.sv's pass-through is
// the whole of a load's arithmetic - no operation was added to the ALU for it.
//
// CAPTURING INTO THE LEFT FLOP INSTEAD COSTS FIVE MHZ, and measured one thing
// at a time it is the CAPTURE that costs them and not the arithmetic.  From the
// shift capture alone, with the address unit absent from every row:
//
//                                          LUT4    MHz
//     the shift capture alone              1048   32.69
//     and an ALU operation to combine      1049   32.08
//     and a wider choice of port A's NUMBER 1052   31.98
//     and a mux on the LEFT flop's input   1083   27.54
//
// An operation that mixes two halves is one cell, because it is one more arm on
// a result mux that was already there; widening where port A's register number
// comes from is four.  The mux on the left flop is thirty-five cells and the
// clock, because THAT flop feeds rtl/unary.sv: the critical path of that row
// runs from the memory's byte select into rtl/unary.sv's register, so anything
// in front of the left flop lands in front of clz and popcount, the deepest
// logic in the machine.  The right flop feeds nothing deep.
//
// MEASURED on an iCE40 UP5K, yosys 0.52 + nextpnr-ice40 0.7, behind a real
// SB_SPRAM256KA holding the program, logic cells and the median of eight
// placement seeds:
//
//                                                    LUT4   block RAMs   MHz
//     rtl/predecode.sv's table left to infer            858        3      20.9
//     microcode ROM in block RAM, predecode in LUTs     922        1      21.9
//     microcode ROM in LUTs as well                     956        0      22.0
//     clz and popcount registered                       947        2      23.7
//     the mask columns swapped, immask5 reordered       938        2      23.3
//     the operands read a cycle early                   866        2      34.3
//     loads and stores, with an address unit           1141        3      28.95
//
// The early rows were measured on a machine that had no transfers of control
// yet, so they are a history of this file rather than a series anything can be
// subtracted from; the table above compares the memory unit against the
// machine as it stood immediately before it.
//
// READING THE OPERANDS EARLY IS THE LARGEST STEP MEASURED SO FAR: 23.3 to 34.3
// MHz, medians of eight placement seeds, and 72 cells smaller.  The critical
// path went from ten cells to seven - instruction register, select, register
// read, ALU, write - and is now operand flop, ALU, result mux, write, with 9.5
// ns of logic against 20.5 of routing.  The register file's read muxes no
// longer feed the ALU at all, which is where the cells went too.
//
// THE ALTERNATIVE WAS A FORWARDING PATH, and it was measured rather than
// argued: letting a one-byte form execute in its dispatch cycle needs the ALU
// result muxed into these flops, which came out at 27.2 MHz against 34.3, for
// 52 more cells.  Charging those forms a second cycle instead costs 6 to 11 per
// cent of executed instructions one cycle each - measured over every
// gcc.c-torture binary - and buys the other 89 to 94 per cent a third more
// clock.  Whole programs run about 1.44 times faster at every optimisation
// level.
//
// PREDECODE MUST BE KEPT OUT OF BLOCK RAM, and was not at first: a table feeding
// flops that load together is a synchronous ROM, synthesis inferred one, and
// the selects then came out of a block RAM's slow clock-to-out at a fixed place
// on the die - a twentieth of the clock.  rtl/predecode.sv now says so with an
// attribute.
//
// THE SLOW UNARY PAIR HAD BEEN SETTING THE CLOCK.  Registering clz and
// popcount's result, and giving those two instructions an extra cycle through
// rtl/ucode.sv's SLOW step, took the processor from 21.9 to 23.7 MHz - against
// 23.8 with the unary block removed altogether, so nearly all of that gain,
// keeping every operation, for 25 LUTs.  The ROM now spans two block RAMs, since
// SLOW is a new word and the contents stopped collapsing into one.
//
// THE MICROCODE ROM IS STILL NOT ON THE CRITICAL PATH.  In LUTs it was 34 more
// cells and the same clock.  The critical path starts at rtl/insn.sv's fields or
// predecode's rhs source and runs through the operand selects and the ALU to
// the result, and routing is two thirds of it: 29 ns of wire against 13 of
// logic.
// =============================================================================

module cpu (
    input  logic        clk,
    input  logic        rst,
    output logic [15:0] mem_addr,    // -> memory: sampled at the clock edge
    input  logic [7:0]  mem_rdata,   // <- the byte at the address sampled last edge
    output logic [7:0]  mem_wdata,   // -> memory: the byte to write there
    output logic        mem_we,      // -> memory: write it at that same edge
    output logic        halted,
    output logic        trapped,
    output logic [15:0] result       // the ALU's output; the stores below give the datapath
                                     // an output of its own, so this is for the test bench
);

    // --- sequencing -----------------------------------------------------------
    // \`defer\` is the one thing the microcode cannot know for itself: a taken
    // branch's target is not on the bus yet, so the step that loads the pc must
    // not dispatch, and the ROM follows its \`next\` into a waiting step instead.
    wire fetch, dispatch, wen;
    wire [1:0] pcload;
    wire amem, abase, we, luse;
    wire [1:0] akon, dcap, wsel, dalt;
    wire [3:0] lalt;
    wire defer;
    ucode u (.clk(clk), .rst(rst), .bus(mem_rdata), .defer(defer), .fetch(fetch),
             .dispatch(dispatch), .wen(wen), .pcload(pcload),
             .amem(amem), .abase(abase), .akon(akon), .we(we), .wsel(wsel),
             .dcap(dcap), .luse(luse), .lalt(lalt), .dalt(dalt),
             .halt(halted), .trap(trapped));

    logic [15:0] pc;
    wire [15:0] pc_next = pc + 16'd1;

    // --- the instruction ------------------------------------------------------
    wire [23:0] q, view;
    insn i (.clk(clk), .bus(mem_rdata), .fetch(fetch), .dispatch(dispatch), .q(q), .view(view));

    wire [3:0] alu_op, lhs_src, rhs_src, dest_src;
    wire [1:0] cond_src;
    wire [1:0] pc_src;
    predecode p (.clk(clk), .bus(mem_rdata), .dispatch(dispatch), .alu_op(alu_op),
                 .lhs_src(lhs_src), .rhs_src(rhs_src), .dest_src(dest_src),
                 .cond_src(cond_src), .pc_src(pc_src));

    // --- the pc's adder, and what it is adding this cycle -----------------------
    // One adder prepares the relative branch target: pc + the displacement byte
    // + 1, with the carry in standing for that + 1 rather than a second adder
    // chained behind the first.
    //
    // IT IS IDLE DURING EVERY CALL - an absolute call's target is the
    // instruction's own bytes and a register call's is the operand flop - so a
    // call borrows it, with the addend forced to 1.
    //
    // THAT IS TRUE ONLY BECAUSE THERE IS NO RELATIVE CALL.  A callr would want
    // this adder for its target and the same adder for its return address in
    // the same cycle, and one of the two would need an adder of its own.  The
    // wide relative transfers were taken out because a linker and no ASLR made
    // them pointless; this is the second thing that bought.  tools/gen-predecode.js
    // refuses a row that asks for both, so a relative call cannot come back
    // without that refusal being dealt with first.
    //
    // The sum is then pc + 2,
    // which is the address after a two- or three-byte call and so is what lr
    // must hold.  rtl/rhs.sv takes it as a right-hand side under code ${PCSUM},
    // and the pass-through carries it to the register file, so the write port
    // needs no mux of its own.  The mux it used to need was worth 3.3 MHz.
    wire [15:0] off    = {{8{mem_rdata[7]}}, mem_rdata};
    wire        retadr = (rhs_src == 4'd${PCSUM});
    wire [15:0] addend = retadr ? 16'd1 : off;
    wire [15:0] pcsum  = pc + addend + 16'd1;

    // --- the datapath, with the operands read a cycle early ---------------------
    (* ram_style = "logic" *)
    logic [15:0] R [0:7];

    wire [2:0]  an, bn, wn;
    wire [15:0] bval, y;
    wire [15:0] adr;                 // the address unit's sum, assigned below
    // A STEP MAY OVERRIDE PORT A, and a store is why.  Its data register is not
    // the one its address was computed from, and no predecoded select can be
    // both - the address register is the one the instruction names, and the
    // source register is the rd field.  So the store's address cycle says so.
    //
    // PUSH IS WHY THERE ARE THREE OF THEM.  It reads three registers in turn,
    // from the three places the encoding puts them, while its predecoded select
    // is busy naming sp for the address unit.
    //
    // AND THE STEP CARRIES THE CODE ITSELF, so this is a 2:1 and not a 4:1.
    // That matters because it is in SERIES with rtl/lhs.sv's own decode and the
    // register file's read, and that chain ends at the memory's data pins - the
    // critical path of the whole machine.  A 4:1 over codes is two LUT levels
    // where this is one, and the microcode bits it costs are free: measured,
    // padding the word from 29 bits to 37 and taking a fifth block RAM moved
    // the clock by 0.01 MHz.  Spend width, buy levels.
    //
    // MEASURED, medians of eight seeds: 26.28 MHz with a 4:1 over two-bit
    // selectors and a 29-bit word, 26.91 with this and 32 - and the wider word
    // still fits in four block RAMs, so the bits were free after all.  The
    // whole distribution moved, 25.4 .. 26.8 to 26.3 .. 27.4, which is what
    // distinguishes a real gain from a lucky median.
    wire [3:0] lhs_eff = luse ? lalt : lhs_src;
    lhs  l (.insn(view), .src(lhs_eff), .regnum(an));
    rhs  r (.insn(view), .src(rhs_src), .regval(R[bn]), .pcsum(pcsum), .adr(adr),
            .regnum(bn), .value(bval));

    // Both ALU inputs, as of the last edge.  The cycle that fills them is the
    // instruction's last fetch - or, for a one-byte form with no byte to fetch,
    // the entry cycle rtl/ucode.sv gives it instead - so what the ALU reads is
    // a cycle old and the register file has already taken the previous
    // instruction's write.
    // A LOADED BYTE LANDS IN THE RIGHT-HAND FLOP, never the left.  Shifted in,
    // it assembles a 16-bit value out of two cycles with no operation of its
    // own; zero extended, it is an 8-bit load complete.  The left flop is left
    // alone on purpose - it feeds rtl/unary.sv, and a mux in front of it costs
    // clz and popcount five MHz.  See the table above.
    logic [15:0] aq, bq;
    always_ff @(posedge clk) begin
        aq <= R[an];
        bq <= (dcap == 2'd1) ? {mem_rdata, bq[15:8]}
            : (dcap == 2'd2) ? {8'h00, mem_rdata} : bval;
    end

    // --- the address unit -------------------------------------------------------
    // The second adder.  Its left input is the left-hand operand flop or its own
    // last address, its right the right-hand operand flop or one of three
    // constants - so \`R[a] + off\` and \`R[a] + R[b]\` are the same add to it,
    // rtl/rhs.sv having already chosen which of the two the flop holds, and an
    // access of any width is that add and then steps of one.
    //
    // \`mar\` LOADS ONLY ON THE CYCLES THAT DRIVE THE BUS, so an access leaves its
    // last address behind it - which is what push and pop will want when they
    // come to write sp back from it.
    logic [15:0] mar;
    wire [15:0] aleft  = abase ? mar : aq;
    wire [15:0] aright = (akon == 2'd0) ? bq
                       : (akon == 2'd1) ? 16'd0
                       : (akon == 2'd2) ? 16'd1 : 16'hffff;
    assign adr = aleft + aright;
    always_ff @(posedge clk) if (amem) mar <= adr;

    // --- and what a store puts on it --------------------------------------------
    // THE STORE DATA COMES OUT OF A FLOP, so nothing combinational stands between
    // the register file and the memory's data pins.  A step picks the byte with
    // \`wsel\` and the NEXT step writes it, which is why a store spends a cycle
    // filling before its first byte goes out and then one byte a cycle for as
    // long as it lasts.  The address cycle does the filling, so the cost is one
    // cycle per store however many bytes it moves: push triple pays it once.
    //
    // WHAT IT BUYS, medians of eight placement seeds on the whole processor:
    // 26.91 MHz with this mux driving the pins directly, 30.46 with the flop.
    // Every measurement before it ended at \`ram_RAM.DATAIN_*\`; this one does not
    // - the critical path moves to the right operand flop and the ALU.
    //
    // AND ONLY STORES PAY, because a load's bytes arrive from the memory into
    // \`bq\`, which always was a flop - loads, pop and ldm are untouched.  Stores
    // are 2.7% of all cycles across div32, malloc, setjmp and abi-struct, so the
    // cost is 1.027 against a clock of 1.132: ten percent faster in real time.
    //
    // PUSH WALKS DOWN, so it writes its HIGH byte first - and it takes both
    // bytes off port A, holding \`lalt\` on the same register for the pair, which
    // is why there are three sources here and not four.  The fourth, the flop's
    // low half, was measured at 1.6 MHz and is not needed: 25.80 against 27.39.
    wire [7:0] wdata_c = (wsel == 2'd0) ? R[an][7:0]
                       : (wsel == 2'd1) ? R[an][15:8] : aq[15:8];
    logic [7:0] wdata_q;
    always_ff @(posedge clk) wdata_q <= wdata_c;
    assign mem_wdata = wdata_q;
    assign mem_we    = we;

    // lraw IS THE REGISTER FILE'S OUTPUT, not the flop's: rtl/unary.sv counts
    // popcount's nibbles from it, in the cycle that reads the register rather
    // than the cycle after, so its tree is level across the two.  Same latency.
    alu  a (.clk(clk), .lhs(aq), .lraw(R[an]), .rhs(bq), .op(alu_op), .y(y));
    // AND A STEP MAY OVERRIDE THE WRITE PORT, which is pop's need.  Predecode
    // carries the POINTER an instruction walks - sp, r1 or r2 - because that is
    // the write every one of them ends with; the registers loaded on the way
    // are named by the step instead, and there can be three of them.  This mux
    // picks between 4-bit codes out of flops and the ROM, feeding a decode
    // rtl/dest.sv already had, which is why it measured four cells and no clock.
    wire [3:0] dest_eff = (dalt == 2'd0) ? dest_src
                        : (dalt == 2'd1) ? 4'd${DEST_RD}
                        : (dalt == 2'd2) ? 4'd${DEST_RA} : 4'd${DEST_B};
    dest d (.insn(q), .src(dest_eff), .regnum(wn));

    // --- the condition, decided a cycle before it is used ----------------------
    wire [2:0] ccode; wire cneg, cmask, taken;
    cond    cu (.insn(q), .src(cond_src), .code(ccode), .neg(cneg), .mask(cmask));
    compare cp (.lhs(aq), .rhs(bq), .cond(ccode), .neg(cneg), .mask(cmask), .taken(taken));
    logic taken_q;
    always_ff @(posedge clk) taken_q <= taken;

    // --- the branch target, in the cycle its last byte arrives -----------------
    // The adder above prepared it: a displacement is always the instruction's
    // LAST byte, so the sum is relatched at every fetch and the one that
    // matters is the last.  A call's cycles latch pc + 2 here instead, and no
    // call ever reads it - its target is the instruction's bytes or the
    // operand flop.
    logic [15:0] tgt;
    always_ff @(posedge clk) tgt <= pcsum;

    // --- which address the next cycle reads ------------------------------------
    // Every candidate settled at an earlier edge or is wiring, so this is a mux
    // and nothing else: the incrementer, the target adder's flop, the
    // instruction's own bytes, and the right-hand operand.  \`pcload\` says
    // whether this step loads the pc and whether the verdict decides it.
    wire [15:0] wide = view[23:8];          // a wide target, as its last byte lands
    wire taking = pcload[0] | (pcload[1] & taken_q);
    assign defer = taking;
    wire [15:0] seq = (fetch | dispatch) ? pc_next : pc;
    always_comb begin
        if (rst)          mem_addr = 16'd0;
        else if (amem)    mem_addr = adr;      // a data cycle: the address unit has it
        else if (!taking) mem_addr = seq;
        else case (pc_src)
            2'd2:         mem_addr = wide;         // the wide target, as it arrives
            2'd3:         mem_addr = aq;           // a register: ret, jmp ra, call ra
            default:      mem_addr = tgt;          // the relative target
        endcase
    end
    // THE pc STANDS STILL THROUGH A DATA CYCLE: the address on the bus then is
    // not where the next instruction byte lives, so it must not be remembered as
    // one.  Every other cycle presents either pc or pc + 1, and this records it.
    always_ff @(posedge clk) if (!amem) pc <= mem_addr;

    // --- the register file's write ---------------------------------------------
    // Straight out of the ALU, with nothing in front of it.  A call's return
    // address is an ALU result like any other: rtl/rhs.sv hands it the pc
    // adder's sum and rtl/alu.sv's pass-through carries it here.  The mux that
    // used to sit here was worth 3.3 MHz - 29.67 against 32.95, medians of
    // eight seeds - because it was at the end of the path every instruction
    // takes, not just the calls that needed it.
    always_ff @(posedge clk) if (wen) R[wn] <= y;
    assign result = y;

endmodule
`);
