#!/usr/bin/env node
// =============================================================================
// gen-gcc.js - the immediate tables the GCC port needs, from isa/fructus.toml
// =============================================================================
//
//   node tools/gen-gcc.js > vendor/gcc/gcc/config/fructus/fructus-isa.h
//
// The compiler never has to know an encoding - gas picks the form - but it does
// have to know which CONSTANTS some form can carry, because gas has no scratch
// register to fall back on.  An `add r1, r2, #1000' that no form encodes is a
// gas error, not a two-instruction expansion, so every immediate the compiler
// prints must be one the tables below admit.
//
// Five tables, all of them values rather than indices:
//
//   imm3       the two-register table immediate, ALU and memory
//   shift3     the same three bits read as a shift count
//   immbit5    single bits and their complements, tied ALU forms and brset
//   immask5    fields and stripes and their complements, likewise
//   condimm5   the packed condition-and-constant of `br ra, #k' - the most
//              constrained immediate in the machine, and the reason this file
//              exists rather than a few constants typed into fructus.cc
//
// The signed ranges (imm5, imm10) are not tables and come through as bit
// widths.  Everything is derived from the spec so that moving an entry there
// moves what the compiler is willing to emit.
// =============================================================================

import { loadSpec } from './isa.js';

const spec = loadSpec();
const t = spec.optype;

const u16 = (v) => ((v % 0x10000) + 0x10000) % 0x10000;
const hex = (v) => '0x' + u16(v).toString(16).padStart(4, '0');

function values(name) {
  const ty = t[name];
  if (ty.kind !== 'table') throw new Error(`${name} is not a table`);
  return ty.values;
}

function bitsOf(name) {
  const ty = t[name];
  if (ty.kind !== 'int' || !ty.signed) throw new Error(`${name} is not a signed int`);
  return ty.bits;
}

const out = [];
const emit = (s = '') => out.push(s);

emit('/* Generated by tools/gen-gcc.js from isa/fructus.toml - do not edit.');
emit('');
emit('   The constants each immediate form of the ISA can carry.  The port');
emit('   consults these to decide which constants an instruction may be printed');
emit('   with; gas then picks the form.  */');
emit('');
emit('#ifndef GCC_FRUCTUS_ISA_H');
emit('#define GCC_FRUCTUS_ISA_H');
emit('');
emit(`#define FRUCTUS_IMM5_BITS  ${bitsOf('imm5')}`);
emit(`#define FRUCTUS_IMM10_BITS ${bitsOf('imm10')}`);
emit(`#define FRUCTUS_OFF8_BITS  ${bitsOf('off8')}`);
emit('');

function table(name, cname, fmt) {
  const v = values(name);
  emit(`static const int ${cname}[${v.length}] = {`);
  for (let i = 0; i < v.length; i += 8)
    emit('  ' + v.slice(i, i + 8).map(fmt).join(', ') + (i + 8 < v.length ? ',' : ''));
  emit('};');
  emit('');
}

table('imm3', 'fructus_imm3', String);
table('shift3', 'fructus_shift3', String);
table('immbit5', 'fructus_immbit5', hex);
table('immask5', 'fructus_immask5', hex);

// condimm5: the condition names are cond3's own spellings.  The port matches a
// comparison against these by TRUTH SET rather than by spelling, as gas does,
// so it needs only the entries themselves.
const c5 = t.condimm5;
if (c5.kind !== 'combo') throw new Error('condimm5 is not a combo');
emit('struct fructus_condimm { const char *cond; int imm; };');
emit('');
emit(`static const struct fructus_condimm fructus_condimm5[${c5.values.length}] = {`);
emit(c5.values.map(([c, k]) => `  { "${c}", ${k} }`).join(',\n'));
emit('};');
emit('');
emit('#endif /* GCC_FRUCTUS_ISA_H */');

process.stdout.write(out.join('\n') + '\n');
