#!/usr/bin/env node
// =============================================================================
// gen-immgen.js - the immediate unit, generated from isa/fructus.toml
// =============================================================================
//
//   node tools/gen-immgen.js > rtl/immgen.sv
//
// One combinational block that produces the 16-bit immediate right-hand side
// for every instruction that has one: the ALU and shift groups, mov, the load
// and store displacements, and the two mask branches.  58 opcodes.
//
// Its only inputs are `immreg` - the last two instruction bytes fetched - and
// `opcode[2:0]`.  There is no control line from the microcode word, which is
// what this file exists to demonstrate; every distinction it needs is already
// in those five bits.  See rtl/immgen.sv's own header for why.
//
// THE VALUE TABLES ARE READ FROM THE SPEC, not transcribed.  tests/immgen-
// check.mjs generates its vectors from the same TOML and runs them against the
// generated Verilog under iverilog, so a table edit that the circuit cannot
// express fails the suite rather than shipping.
// =============================================================================

import { loadSpec } from './isa.js';

const spec = loadSpec();
const t = spec.optype;
const hex16 = (v) => `16'h${(((v) >>> 0) & 0xffff).toString(16).padStart(4, '0')}`;

// --- the properties this circuit depends on, asserted here as well as in
// --- check.js, because a generator that silently emits wrong logic is worse
// --- than one that refuses to run.
for (let n = 0; n < 16; n++) {
  for (const name of ['immbit5', 'immask5'])
    if (((t[name].values[n] ^ t[name].values[n + 16]) & 0xffff) !== 0xffff)
      throw new Error(`${name}: entry ${n + 16} is not the complement of ${n}`);
}
for (let n = 0; n < 8; n++)
  if ((t.imm3.values[n] & 15) !== (t.shift3.values[n] & 15))
    throw new Error(`shift3[${n}] is not imm3[${n}] & 15`);

const caseTable = (name, vals, w, sel) =>
  `    always_comb case (${sel})\n` +
  vals.map((v, n) => `        ${w}'d${n}: ${name} = ${hex16(v)};`).join('\n') +
  `\n    endcase`;

process.stdout.write(`// =============================================================================
// immgen.sv - the immediate right-hand side
// =============================================================================
//
// GENERATED by tools/gen-immgen.js from isa/fructus.toml.  Do not edit; edit
// the spec and regenerate with \`npm run rtl\`.
//
// One combinational block serving 58 opcodes: every ALU and shift group, mov,
// the load and store displacements, and brclear/brset.  Its inputs are the two
// most recently fetched instruction bytes and the low three bits of the opcode
// register.  NOTHING ELSE - no width bit, no shift bit, no microcode control
// line.  Four properties of the encoding make that possible.
//
// 1. THE COLUMN IS THE MODE.  Every instruction with an immediate puts it in
//    the same column of the opcode map, so opcode[2:0] alone says which of the
//    five immediate modes to produce:
//
//      +0  imm5      signed -16..15, and the tied load displacement
//      +1  immbit5   32 single-bit masks
//      +2  imm3      the small-constant table  (+3 is its second opcode)
//      +4  imm10     signed, spanning two bytes
//      +5  immask5   32 field and stripe masks
//      +6, +7              the three-operand forms: NO IMMEDIATE, x
//
// 2. +6 AND +7 ARE DELIBERATELY UNDEFINED.  Everything there takes its
//    right-hand side from a register, and rtl/rhs.sv gets that register's
//    number straight off the instruction bytes rather than from here - so this
//    block computing it too would be a second copy of the same three wires,
//    free to drift from the first.
//
//    Driving x rather than a tidy zero is the point: an x reaching the ALU says
//    the microcode asked for an immediate from an instruction that has none,
//    which is a bug, and it should be loud in simulation rather than quietly
//    plausible.  0x16 and 0x17 make that concrete - they are \`mov rd, #imm16\`,
//    where opcode[2:0] is the DESTINATION REGISTER and not a mode selector at
//    all, so this block's output there is meaningless for a third reason again.
//
// 3. opcode[0] IS sel[0].  The imm3 index is {byte1[1:0], opcode[0]} - the spec
//    spells this \`imm3[0]\`, so the pair of opcodes at +2 and +3 ARE the low
//    index bit.  It is already an input; the index costs no logic.
//
// 4. THE TWO 5-BIT TABLES SHARE THEIR COMPLEMENT HALF.  For both immbit5 and
//    immask5 the upper sixteen entries are exact bitwise complements of the
//    lower sixteen - asserted by the generator, not assumed - and sel[2] is
//    what distinguishes the two (+1 against +5).  So the sixteen-entry halves
//    are chosen first and the complement XOR is applied once, not twice.
//
// 5. imm3 AND shift3 ARE ONE TABLE.  They differ at index 0 alone, -1 against
//    15, and the shifter masks its right-hand side to four bits, so -1 IS 15 to
//    a shift.  shift3 is an assembler vocabulary - it exists to reject
//    \`shl rd, ra, #-1\` - and the datapath never needs to know about it.
//
// FIELD POSITION IS A TIMING PROPERTY, AND IT IS A CONTRACT ON THE MICROCODE.
// immreg holds the last two bytes fetched, so byte 1 moves as the third byte
// arrives.  This block reads a five-bit field at ir[4:0] and the ten-bit field
// at ir[9:0], which is correct if and only if:
//
//     ANY FIVE-BIT FIELD IS CONSUMED BEFORE THE THIRD BYTE IS FETCHED.
//
// For the two-byte forms that is vacuous - there is no third byte.  For
// brclear and brset it is a real ordering requirement, and the natural one: the
// mask test does not need the displacement, so it overlaps the fetch of it and
// costs nothing.  The ten-bit field is the opposite case - it cannot be read
// until byte 2 arrives, and by then it is contiguous at ir[9:0].
//
// Break that ordering and this block silently reads the wrong five bits.  There
// is no signal that would catch it, which is why it is written down here.
//
// The register-select fields have the same alignment question and DO NOT escape
// it the same way: \`ld rd, [ra, #imm10]\` needs ra at the moment it needs the
// displacement, which is after byte 2 has shifted byte 1 upwards.  Read the
// operands into the ALU input latches early, or give byte 1 its own register.
//
// NEITHER br FORM RIDES THIS BLOCK.  The two-register branches are at +6 and
// +7, where there is no immediate; and the packed form at +0 reads five bits
// through condimm5, which fuses a condition with a constant rather than being a
// plain immediate.  The branch unit decodes that one for itself.
//
// MEASURED on an iCE40 UP5K: 79 SB_LUT4, three LUT levels, 100 MHz placed.
// =============================================================================

module immgen (
    input  logic [15:0] ir,     // immreg: the last two instruction bytes
    input  logic [2:0]  sel,    // opcode[2:0]
    output logic [15:0] imm
);

    // --- the two modes that are pure wiring ---------------------------------
    wire [15:0] i5  = {{11{ir[4]}}, ir[4:0]};      // +0  imm5, and off5
    wire [15:0] i10 = {{6{ir[9]}},  ir[9:0]};      // +4  imm10, contiguous

    // --- +2 / +3: imm3, which is also shift3 --------------------------------
    wire [2:0] k3 = {ir[1:0], sel[0]};
    logic [3:0] lo3;
${caseTable('lo3', t.imm3.values.map((v) => v & 15), 3, 'k3').replace(/16'h([0-9a-f]{4})/g, (_, h) => `4'h${h.slice(-1)}`)}
    // Index 0 is the only entry whose top twelve bits are set: -1 for the ALU,
    // and 15 to a shifter, which masks.  One gate, not a second table.
    wire neg = (k3 == 3'd0);
    wire [15:0] i3v = {{12{neg}}, lo3};

    // --- +1 / +5: immbit5 and immask5, sharing one complement layer ---------
    wire [3:0] n4 = ir[3:0];
    logic [15:0] tbit, tmask;
${caseTable('tbit', t.immbit5.values.slice(0, 16), 4, 'n4')}
${caseTable('tmask', t.immask5.values.slice(0, 16), 4, 'n4')}
    wire [15:0] tsel = (sel[2] ? tmask : tbit) ^ {16{ir[4]}};

    // --- the mode mux -------------------------------------------------------
    // +6 and +7 have no immediate; x rather than 0 both lets the mapper treat
    // them as don't-cares and makes a microcode misuse visible in simulation.
    always_comb case (sel)
        3'd0:        imm = i5;
        3'd1, 3'd5:  imm = tsel;
        3'd2, 3'd3:  imm = i3v;
        3'd4:        imm = i10;
        default:     imm = 16'hxxxx;
    endcase

endmodule
`);
