#!/usr/bin/env node
// =============================================================================
// gen-ucode.js - the processor's microcode ROM
// =============================================================================
//
//   node tools/gen-ucode.js > rtl/ucode.sv
//
// WHAT IS MICROCODED IS WHAT GETS COMPLICATED.  Every ALU instruction, branch
// and jump runs through rtl/cpu.sv's three stages with no microcode at
// all.  A memory instruction's ALU cycle is an ordinary add too - its first
// address - and the steps after it, one byte a cycle, are what this ROM holds.
// It is a block RAM: the control that took eight shift-register schedules and
// their masks in LUTs takes one of the part's thirty RAMs instead.
//
// THE ADDRESS is {entry, step - 1}, and the ENTRY IS PREDECODE'S: a column of
// rtl/classify.sv, which has the time to look it up, carried through
// decode and the ALU stage like any other field.  So any opcode can start any
// routine, and routines can be shared - push and stm step alike, and so do
// pop and ldm, since only their pointer's offset differs, and that is the
// ALU's business.  tools/ucode.js holds the routines and assigns the
// entries; both generators read it.  Entry 0 is idle, all zeros.
//
// THE ROM'S OUTPUT IS REGISTERED, as a block RAM's is, so the word for step k
// is addressed in step k - 1 and every control still comes out of a flop.
// The ALU cycle addresses step 1.  What happens IN the ALU cycle - a load's
// first address, a store's first byte, a one-byte load releasing dispatch at
// once - is decided by logic in rtl/cpu.sv, since no word could have
// been read for it.
//
// THE WORD is tools/ucode.js's FIELDS, printed in rtl/ucode.sv's
// header.  It is 32 bits, two block RAMs side by side, since the exception
// routines' fields do not fit beside the memory instructions' in sixteen.
//
// THE STEPS of a memory instruction are rtl/cpu.sv's, and its header
// gives the reasons.  For N bytes, B a register:
//
//     store  address 1 .. N; release at N; done at N, or N + 1 for a block,
//            whose pointer is written then - last, so a stored register that
//            is the pointer is read as it was
//     load   address 1 .. N - 1 - the first went out in the ALU cycle;
//            bytes arrive 1 .. N; register i written at 1 + (i + 1) B;
//            release at N - 1; done at N + 1; a block's pointer written at 1,
//            first, and a loaded register that is the pointer not written
//
// THE EXCEPTION ROUTINES - brk, rti, sei, cli - move registers and shadows
// through the same two paths: a register is read through decode's borrowed
// left port, and written from ldq through the ALU's pass-through.  So no
// register and shadow are exchanged in one step, and each read comes before
// the write it must not see, in the order isa/fructus.toml gives the
// statements.  A hardware interrupt runs brk's routine: rtl/cpu.sv
// dispatches a brk in place of the instruction it preempts.
// =============================================================================

import { ROUTINES, FIELDS, WORD_BITS, words as romWords } from './ucode.js';

const words = romWords();
const hex = (v, w) => v.toString(16).padStart(w, '0');
// THE LATE COPIES ARE WRITTEN ONLY UNDER FRUCTUS_BLIT.  yosys reads a ROM's
// contents when it maps the logic around it, and with them in, unreachable
// as they are without blit mode, the core came out 31 LUT4s different.
const line = (w, a) => `        rom[8'h${hex(a, 2)}] = ${WORD_BITS}'h${hex(w, WORD_BITS / 4)};`;
const isLate = (a) => ROUTINES[a >> 3]?.key?.startsWith('late:');
const init = words.map((w, a) => (isLate(a) ? null : line(w, a))).filter((l) => l).join('\n')
           + '\n`ifdef FRUCTUS_BLIT\n'
           + words.map((w, a) => (isLate(a) ? line(w, a) : null)).filter((l) => l).join('\n')
           + '\n`else\n'
           + words.map((w, a) => (isLate(a) ? line(0, a) : null)).filter((l) => l).join('\n')
           + '\n`endif';
const fields = FIELDS.map(([f, bit, width, what]) => {
  const at = width > 1 ? `${bit + width - 1}:${bit}` : `${bit}`;
  return `//     ${at.padEnd(6)} ${f.padEnd(3)} ${what}`;
}).join('\n');

process.stdout.write(`// =============================================================================
// ucode.sv - the processor's microcode ROM
// =============================================================================
//
// GENERATED by tools/gen-ucode.js from tools/ucode.js.  Do not edit.
//
// ${ROUTINES.length - 1} routines and idle, eight steps each, in 256 words of ${WORD_BITS} bits: two
// block RAMs side by side.
${ROUTINES.map((r, e) => `//     entry ${String(e).padStart(2)}  ${r.name.padEnd(12)}${r.bytes ? ` ${r.bytes} byte${r.bytes > 1 ? 's' : ''}` : r.steps.length ? ` ${r.steps.length} step${r.steps.length > 1 ? 's' : ''}` : ''}`).join('\n')}
//
// THE WORD
//
${fields}
// =============================================================================

module ucode (
    input  logic        clk,
    input  logic [7:0]  addr,      // {entry, step - 1}; 0 when idle
    output logic [${WORD_BITS - 1}:0] word       // the word addressed at the last edge
);

    logic [${WORD_BITS - 1}:0] rom [0:255];
    initial begin
${init}
    end

    always_ff @(posedge clk) word <= rom[addr];

endmodule
`);
