// =============================================================================
// classify.sv - the pipelined experiment's predecode: what the opcode is
// =============================================================================
//
// GENERATED by tools/gen-pipe-classify.js from isa/fructus.toml.  Do not edit.
//
// Combinational, over the opcode byte as it arrives in the dispatch cycle.
// rtl/pipe/cpu.sv decides from kind and length alone whether the next dispatch
// can follow at once, and latches the rest for the decode stage.
//
// 149 opcodes: 86 ALU, 50 microcoded - 40 of them memory instructions and
// 4 exception instructions - 7 conditional branches, 6 jumps.
// AN OPCODE THE SPEC LEAVES EMPTY IS MICROCODED, AND ITS LENGTH IS LEFT TO THE
// MAPPER.  Microcoded stops dispatch, and it traps in the ALU stage whatever
// pc was worked out behind it, so the length is never used.  Pinned at one, as
// it was, it measured 32.96 MHz against 33.59, and the length's lookup was on
// the critical path in some seeds; free, it is on none.  The empty cells -
// 107 of them - let synthesis carry the pattern of the rows and columns
// across them.
// Rearranging the opcodes that ARE used, with the empties still pinned, made
// it worse: 31.08.
// =============================================================================

module classify (
    input  logic [7:0] op,
    output logic [1:0] kind,      // 0 ALU, 1 microcoded, 2 conditional branch, 3 jump
    output logic [1:0] len,       // 1, 2 or 3 bytes
    output logic       wen,       // an ALU row writes its destination
    output logic       halt,      // it is halt
    output logic [3:0] alu_op,    // -> rtl/pipe/alu.sv
    output logic [3:0] lhs_src,   // -> rtl/lhs.sv
    output logic [3:0] rhs_src,   // rtl/rhs.sv's codes, read by rtl/pipe/cpu.sv's decode
    output logic [3:0] dest_src,  // -> rtl/dest.sv
    output logic [1:0] cond_src,  // -> rtl/cond.sv, for a conditional branch
    output logic [1:0] pc_src,    // a jump's target: 1 relative, 2 absolute, 3 register
    output logic       mem,       // a memory instruction: the rest describe it
    output logic       mst,       //   it stores
    output logic       mw2,       //   two bytes a register
    output logic [1:0] mn,        //   1, 2 or 3 registers
    output logic       mblk,      //   a block move, walking and writing back lhs
    output logic       mpush,     //   downward, so its registers lie reversed
    output logic       useq,      // it runs a routine: a memory or exception instruction
    output logic [4:0] uent       // where its routine starts in rtl/pipe/ucode.sv
);

    logic [37:0] t;
    always_comb begin
        (* rom_style = "logic" *)
        case (op)
        8'h00: t = 38'b01_01_0_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_1_01011;    // brk
        8'h01: t = 38'b01_01_x_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // halt
        8'h02: t = 38'b01_01_0_xxxx_0111_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_1_01100;    // rti
        8'h03: t = 38'b01_01_0_0000_0000_1000_0000_xx_xx_1_0_1_01_0_0_1_00010;    // ld
        8'h04: t = 38'b01_01_0_0000_0000_1000_0000_xx_xx_1_0_0_01_0_0_1_00001;    // ld8
        8'h05: t = 38'b00_01_1_0000_0000_1001_0000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h06: t = 38'b00_01_1_0000_0000_1111_0000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h07: t = 38'b00_01_1_0000_0000_1010_0000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h09: t = 38'b01_11_0_0000_1001_1011_1000_xx_xx_1_1_1_01_0_0_1_00111;    // st
        8'h0a: t = 38'b01_10_0_0000_1001_1011_1000_xx_xx_1_1_1_01_0_0_1_00111;    // st
        8'h0b: t = 38'b01_10_0_0000_1001_1011_1000_xx_xx_1_1_1_01_0_0_1_00111;    // st
        8'h0e: t = 38'b01_10_0_0000_1001_1101_1000_xx_xx_1_1_1_01_0_0_1_00111;    // st
        8'h0f: t = 38'b01_10_0_0000_1001_1101_1000_xx_xx_1_1_1_01_0_0_1_00111;    // st
        8'h11: t = 38'b01_11_0_0000_1001_1011_1000_xx_xx_1_1_0_01_0_0_1_00110;    // st8
        8'h12: t = 38'b01_10_0_0000_1001_1011_1000_xx_xx_1_1_0_01_0_0_1_00110;    // st8
        8'h13: t = 38'b01_10_0_0000_1001_1011_1000_xx_xx_1_1_0_01_0_0_1_00110;    // st8
        8'h16: t = 38'b01_10_0_0000_1001_1101_1000_xx_xx_1_1_0_01_0_0_1_00110;    // st8
        8'h17: t = 38'b01_10_0_0000_1001_1101_1000_xx_xx_1_1_0_01_0_0_1_00110;    // st8
        8'h18: t = 38'b01_10_0_0000_1000_1011_1000_xx_xx_1_0_1_01_0_0_1_00010;    // ld
        8'h19: t = 38'b01_11_0_0000_1001_1011_1000_xx_xx_1_0_1_01_0_0_1_00010;    // ld
        8'h1a: t = 38'b01_10_0_0000_1001_1011_1000_xx_xx_1_0_1_01_0_0_1_00010;    // ld
        8'h1b: t = 38'b01_10_0_0000_1001_1011_1000_xx_xx_1_0_1_01_0_0_1_00010;    // ld
        8'h1e: t = 38'b01_10_0_0000_1001_1101_1000_xx_xx_1_0_1_01_0_0_1_00010;    // ld
        8'h1f: t = 38'b01_10_0_0000_1001_1101_1000_xx_xx_1_0_1_01_0_0_1_00010;    // ld
        8'h20: t = 38'b01_10_0_0000_1000_1011_1000_xx_xx_1_0_0_01_0_0_1_00001;    // ld8
        8'h21: t = 38'b01_11_0_0000_1001_1011_1000_xx_xx_1_0_0_01_0_0_1_00001;    // ld8
        8'h22: t = 38'b01_10_0_0000_1001_1011_1000_xx_xx_1_0_0_01_0_0_1_00001;    // ld8
        8'h23: t = 38'b01_10_0_0000_1001_1011_1000_xx_xx_1_0_0_01_0_0_1_00001;    // ld8
        8'h26: t = 38'b01_10_0_0000_1001_1101_1000_xx_xx_1_0_0_01_0_0_1_00001;    // ld8
        8'h27: t = 38'b01_10_0_0000_1001_1101_1000_xx_xx_1_0_0_01_0_0_1_00001;    // ld8
        8'h28: t = 38'b00_10_1_0111_xxxx_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h29: t = 38'b00_11_1_1010_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // movhi
        8'h2c: t = 38'b00_10_1_0111_xxxx_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h2d: t = 38'b00_10_1_0111_xxxx_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h2e: t = 38'b00_10_1_1010_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // movhi
        8'h2f: t = 38'b00_10_1_1010_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // movhi
        8'h30: t = 38'b01_10_x_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mul
        8'h31: t = 38'b01_11_x_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mul
        8'h32: t = 38'b00_10_1_1100_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // clmul bitrev sxt8
        8'h33: t = 38'b01_10_x_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // clz popcount
        8'h36: t = 38'b01_10_x_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mul
        8'h37: t = 38'b01_10_x_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mul
        8'h38: t = 38'b00_10_1_0000_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h39: t = 38'b00_11_1_0000_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h3a: t = 38'b00_10_1_0000_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h3b: t = 38'b00_10_1_0000_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h3c: t = 38'b00_10_1_0000_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h3d: t = 38'b00_10_1_0000_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h3e: t = 38'b00_10_1_0000_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h3f: t = 38'b00_10_1_0000_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h40: t = 38'b00_10_1_0001_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // rsb
        8'h41: t = 38'b00_11_1_0001_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // rsb
        8'h42: t = 38'b00_10_1_0001_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // rsb
        8'h43: t = 38'b00_10_1_0001_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // rsb
        8'h46: t = 38'b00_10_1_0001_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // rsb
        8'h47: t = 38'b00_10_1_0001_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // rsb
        8'h48: t = 38'b00_10_1_0100_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // xor
        8'h49: t = 38'b00_11_1_0100_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // xor
        8'h4a: t = 38'b00_10_1_0100_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // xor
        8'h4b: t = 38'b00_10_1_0100_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // xor
        8'h4c: t = 38'b00_10_1_0100_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // xor
        8'h4d: t = 38'b00_10_1_0100_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // xor
        8'h4e: t = 38'b00_10_1_0100_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // xor
        8'h4f: t = 38'b00_10_1_0100_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // xor
        8'h50: t = 38'b00_10_1_0101_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // or
        8'h51: t = 38'b00_11_1_0101_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // or
        8'h52: t = 38'b00_10_1_0101_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // or
        8'h53: t = 38'b00_10_1_0101_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // or
        8'h54: t = 38'b00_10_1_0101_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // or
        8'h55: t = 38'b00_10_1_0101_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // or
        8'h56: t = 38'b00_10_1_0101_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // or
        8'h57: t = 38'b00_10_1_0101_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // or
        8'h58: t = 38'b00_10_1_0110_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // and
        8'h59: t = 38'b00_11_1_0110_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // and
        8'h5a: t = 38'b00_10_1_0110_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // and
        8'h5b: t = 38'b00_10_1_0110_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // and
        8'h5c: t = 38'b00_10_1_0110_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // and
        8'h5d: t = 38'b00_10_1_0110_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // and
        8'h5e: t = 38'b00_10_1_0110_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // and
        8'h5f: t = 38'b00_10_1_0110_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // and
        8'h60: t = 38'b00_10_1_1000_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // shl
        8'h62: t = 38'b00_10_1_1000_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // shl
        8'h63: t = 38'b00_10_1_1000_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // shl
        8'h66: t = 38'b00_10_1_1000_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // shl
        8'h67: t = 38'b00_10_1_1000_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // shl
        8'h68: t = 38'b00_10_1_1011_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // asr
        8'h6a: t = 38'b00_10_1_1011_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // asr
        8'h6b: t = 38'b00_10_1_1011_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // asr
        8'h6e: t = 38'b00_10_1_1011_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // asr
        8'h6f: t = 38'b00_10_1_1011_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // asr
        8'h70: t = 38'b00_10_1_1001_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // lsr
        8'h72: t = 38'b00_10_1_1001_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // lsr
        8'h73: t = 38'b00_10_1_1001_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // lsr
        8'h76: t = 38'b00_10_1_1001_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // lsr
        8'h77: t = 38'b00_10_1_1001_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // lsr
        8'h78: t = 38'b00_10_1_0010_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // iseq
        8'h79: t = 38'b00_11_1_0010_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // iseq
        8'h7a: t = 38'b00_10_1_0010_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // iseq
        8'h7b: t = 38'b00_10_1_0010_1001_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // iseq
        8'h7c: t = 38'b00_10_1_0011_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // isset
        8'h7d: t = 38'b00_10_1_0011_1000_1011_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // isset
        8'h7e: t = 38'b00_10_1_0010_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // iseq
        8'h7f: t = 38'b00_10_1_0010_1001_1101_1000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // iseq
        8'h80: t = 38'b00_01_1_0000_0001_0000_0001_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h81: t = 38'b00_01_1_0101_0001_1000_0000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // or
        8'h82: t = 38'b00_01_1_0101_0000_1000_0001_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // or
        8'h83: t = 38'b00_01_1_0111_xxxx_1000_0000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h84: t = 38'b00_01_1_0100_0000_1001_0000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // xor
        8'h85: t = 38'b00_01_1_0000_0000_0001_0000_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // add
        8'h87: t = 38'b00_01_0_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // nop
        8'h88: t = 38'b00_11_1_0111_xxxx_0100_1010_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h89: t = 38'b00_11_1_0111_xxxx_0100_1010_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h8a: t = 38'b00_11_1_0111_xxxx_0100_1010_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h8b: t = 38'b00_11_1_0111_xxxx_0100_1010_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h8c: t = 38'b00_11_1_0111_xxxx_0100_1010_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h8d: t = 38'b00_11_1_0111_xxxx_0100_1010_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h8e: t = 38'b00_11_1_0111_xxxx_0100_1010_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h8f: t = 38'b00_11_1_0111_xxxx_0100_1010_xx_xx_0_x_x_xx_x_x_0_xxxxx;    // mov
        8'h90: t = 38'b01_10_0_0000_0110_0011_1000_xx_xx_1_1_1_01_1_1_1_01000;    // push
        8'h91: t = 38'b01_10_0_0000_0001_0011_1000_xx_xx_1_1_1_01_1_0_1_01000;    // stm
        8'h92: t = 38'b01_10_0_0000_0110_0011_1000_xx_xx_1_1_1_10_1_1_1_01001;    // push
        8'h93: t = 38'b01_10_0_0000_0001_0011_1000_xx_xx_1_1_1_10_1_0_1_01001;    // stm
        8'h94: t = 38'b01_10_0_0000_0001_0011_1000_xx_xx_1_1_1_11_1_0_1_01010;    // stm
        8'h95: t = 38'b01_10_0_0000_0001_0011_1000_xx_xx_1_1_1_11_1_0_1_01010;    // stm
        8'h96: t = 38'b01_10_0_0000_0110_0011_1000_xx_xx_1_1_1_11_1_1_1_01010;    // push
        8'h97: t = 38'b01_10_0_0000_0110_0011_1000_xx_xx_1_1_1_11_1_1_1_01010;    // push
        8'h98: t = 38'b01_10_0_0000_0110_0011_1000_xx_xx_1_0_1_01_1_0_1_00011;    // pop
        8'h99: t = 38'b01_10_0_0000_0010_0011_1000_xx_xx_1_0_1_01_1_0_1_00011;    // ldm
        8'h9a: t = 38'b01_10_0_0000_0110_0011_1000_xx_xx_1_0_1_10_1_0_1_00100;    // pop
        8'h9b: t = 38'b01_10_0_0000_0010_0011_1000_xx_xx_1_0_1_10_1_0_1_00100;    // ldm
        8'h9c: t = 38'b01_10_0_0000_0010_0011_1000_xx_xx_1_0_1_11_1_0_1_00101;    // ldm
        8'h9d: t = 38'b01_10_0_0000_0010_0011_1000_xx_xx_1_0_1_11_1_0_1_00101;    // ldm
        8'h9e: t = 38'b01_10_0_0000_0110_0011_1000_xx_xx_1_0_1_11_1_0_1_00101;    // pop
        8'h9f: t = 38'b01_10_0_0000_0110_0011_1000_xx_xx_1_0_1_11_1_0_1_00101;    // pop
        8'ha0: t = 38'b10_11_0_xxxx_1000_1100_xxxx_01_01_0_x_x_xx_x_x_0_xxxxx;    // br
        8'ha1: t = 38'b11_11_0_xxxx_xxxx_xxxx_xxxx_xx_10_0_x_x_xx_x_x_0_xxxxx;    // jmp
        8'ha2: t = 38'b11_10_0_xxxx_1000_xxxx_xxxx_xx_11_0_x_x_xx_x_x_0_xxxxx;    // jmp
        8'ha3: t = 38'b11_10_0_xxxx_xxxx_1011_xxxx_xx_01_0_x_x_xx_x_x_0_xxxxx;    // jmpr
        8'ha4: t = 38'b10_11_0_xxxx_1000_1011_xxxx_10_01_0_x_x_xx_x_x_0_xxxxx;    // brclr
        8'ha5: t = 38'b10_11_0_xxxx_1000_1011_xxxx_10_01_0_x_x_xx_x_x_0_xxxxx;    // brclr
        8'ha6: t = 38'b10_11_0_xxxx_1001_1101_xxxx_00_01_0_x_x_xx_x_x_0_xxxxx;    // br
        8'ha7: t = 38'b10_11_0_xxxx_1001_1101_xxxx_00_01_0_x_x_xx_x_x_0_xxxxx;    // br
        8'ha9: t = 38'b11_11_1_0111_xxxx_0010_0111_xx_10_0_x_x_xx_x_x_0_xxxxx;    // call
        8'haa: t = 38'b11_10_1_0111_1000_0010_0111_xx_11_0_x_x_xx_x_x_0_xxxxx;    // call
        8'hab: t = 38'b11_01_0_xxxx_0111_0111_xxxx_xx_11_0_x_x_xx_x_x_0_xxxxx;    // ret
        8'hac: t = 38'b10_11_0_xxxx_1000_1011_xxxx_11_01_0_x_x_xx_x_x_0_xxxxx;    // brset
        8'had: t = 38'b10_11_0_xxxx_1000_1011_xxxx_11_01_0_x_x_xx_x_x_0_xxxxx;    // brset
        8'hae: t = 38'b01_01_0_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_1_01101;    // sei
        8'haf: t = 38'b01_01_0_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_1_01110;    // cli
        default: t = 38'b01_xx_x_xxxx_xxxx_xxxx_xxxx_xx_xx_0_x_x_xx_x_x_0_xxxxx;
        endcase
    end

    assign {kind, len, wen, alu_op, lhs_src, rhs_src, dest_src, cond_src, pc_src,
            mem, mst, mw2, mn, mblk, mpush, useq, uent} = t;
    assign halt = (op == 8'h01);

endmodule
