// =============================================================================
// classify.sv - the pipelined experiment's predecode: what the opcode is
// =============================================================================
//
// GENERATED by tools/gen-pipe-classify.js from isa/fructus.toml.  Do not edit.
//
// Combinational, over the opcode byte as it arrives in the dispatch cycle.
// rtl/pipe/cpu.sv decides from kind and length alone whether the next dispatch
// can follow at once, and latches the rest for the decode stage.
//
// 149 opcodes: 86 ALU, 56 microcoded, 7 conditional branches.
// An opcode the spec leaves empty is microcoded and one byte long, so that the
// experiment stops at it rather than running on into the bytes after it.
// =============================================================================

module classify (
    input  logic [7:0] op,
    output logic [1:0] kind,      // 0 ALU, 1 microcoded, 2 conditional branch
    output logic [1:0] len,       // 1, 2 or 3 bytes
    output logic       wen,       // an ALU row writes its destination
    output logic       halt,      // it is halt
    output logic [3:0] alu_op,    // -> rtl/pipe/alu.sv
    output logic [3:0] lhs_src,   // -> rtl/lhs.sv
    output logic [3:0] rhs_src,   // rtl/rhs.sv's codes, read by rtl/pipe/cpu.sv's decode
    output logic [3:0] dest_src   // -> rtl/dest.sv
);

    logic [20:0] t;
    always_comb begin
        (* rom_style = "logic" *)
        case (op)
        8'h00: t = 21'b01_01_x_xxxx_xxxx_xxxx_xxxx;    // brk
        8'h01: t = 21'b01_01_x_xxxx_xxxx_xxxx_xxxx;    // halt
        8'h02: t = 21'b01_01_x_xxxx_xxxx_xxxx_xxxx;    // rti
        8'h03: t = 21'b01_01_x_xxxx_xxxx_xxxx_xxxx;    // ld
        8'h04: t = 21'b01_01_x_xxxx_xxxx_xxxx_xxxx;    // ld8
        8'h05: t = 21'b00_01_1_0000_0000_1001_0000;    // add
        8'h06: t = 21'b00_01_1_0000_0000_1111_0000;    // add
        8'h07: t = 21'b00_01_1_0000_0000_1010_0000;    // add
        8'h09: t = 21'b01_11_x_xxxx_xxxx_xxxx_xxxx;    // st
        8'h0a: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // st
        8'h0b: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // st
        8'h0e: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // st
        8'h0f: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // st
        8'h11: t = 21'b01_11_x_xxxx_xxxx_xxxx_xxxx;    // st8
        8'h12: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // st8
        8'h13: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // st8
        8'h16: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // st8
        8'h17: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // st8
        8'h18: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ld
        8'h19: t = 21'b01_11_x_xxxx_xxxx_xxxx_xxxx;    // ld
        8'h1a: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ld
        8'h1b: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ld
        8'h1e: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ld
        8'h1f: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ld
        8'h20: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ld8
        8'h21: t = 21'b01_11_x_xxxx_xxxx_xxxx_xxxx;    // ld8
        8'h22: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ld8
        8'h23: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ld8
        8'h26: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ld8
        8'h27: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ld8
        8'h28: t = 21'b00_10_1_0111_xxxx_1011_1000;    // mov
        8'h29: t = 21'b00_11_1_1010_1001_1011_1000;    // movhi
        8'h2c: t = 21'b00_10_1_0111_xxxx_1011_1000;    // mov
        8'h2d: t = 21'b00_10_1_0111_xxxx_1011_1000;    // mov
        8'h2e: t = 21'b00_10_1_1010_1001_1101_1000;    // movhi
        8'h2f: t = 21'b00_10_1_1010_1001_1101_1000;    // movhi
        8'h30: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // mul
        8'h31: t = 21'b01_11_x_xxxx_xxxx_xxxx_xxxx;    // mul
        8'h32: t = 21'b00_10_1_1100_1001_1011_1000;    // clmul bitrev sxt8
        8'h33: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // clz popcount
        8'h36: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // mul
        8'h37: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // mul
        8'h38: t = 21'b00_10_1_0000_1000_1011_1000;    // add
        8'h39: t = 21'b00_11_1_0000_1001_1011_1000;    // add
        8'h3a: t = 21'b00_10_1_0000_1001_1011_1000;    // add
        8'h3b: t = 21'b00_10_1_0000_1001_1011_1000;    // add
        8'h3c: t = 21'b00_10_1_0000_1000_1011_1000;    // add
        8'h3d: t = 21'b00_10_1_0000_1000_1011_1000;    // add
        8'h3e: t = 21'b00_10_1_0000_1001_1101_1000;    // add
        8'h3f: t = 21'b00_10_1_0000_1001_1101_1000;    // add
        8'h40: t = 21'b00_10_1_0001_1000_1011_1000;    // rsb
        8'h41: t = 21'b00_11_1_0001_1001_1011_1000;    // rsb
        8'h42: t = 21'b00_10_1_0001_1001_1011_1000;    // rsb
        8'h43: t = 21'b00_10_1_0001_1001_1011_1000;    // rsb
        8'h46: t = 21'b00_10_1_0001_1001_1101_1000;    // rsb
        8'h47: t = 21'b00_10_1_0001_1001_1101_1000;    // rsb
        8'h48: t = 21'b00_10_1_0100_1000_1011_1000;    // xor
        8'h49: t = 21'b00_11_1_0100_1001_1011_1000;    // xor
        8'h4a: t = 21'b00_10_1_0100_1001_1011_1000;    // xor
        8'h4b: t = 21'b00_10_1_0100_1001_1011_1000;    // xor
        8'h4c: t = 21'b00_10_1_0100_1000_1011_1000;    // xor
        8'h4d: t = 21'b00_10_1_0100_1000_1011_1000;    // xor
        8'h4e: t = 21'b00_10_1_0100_1001_1101_1000;    // xor
        8'h4f: t = 21'b00_10_1_0100_1001_1101_1000;    // xor
        8'h50: t = 21'b00_10_1_0101_1000_1011_1000;    // or
        8'h51: t = 21'b00_11_1_0101_1001_1011_1000;    // or
        8'h52: t = 21'b00_10_1_0101_1001_1011_1000;    // or
        8'h53: t = 21'b00_10_1_0101_1001_1011_1000;    // or
        8'h54: t = 21'b00_10_1_0101_1000_1011_1000;    // or
        8'h55: t = 21'b00_10_1_0101_1000_1011_1000;    // or
        8'h56: t = 21'b00_10_1_0101_1001_1101_1000;    // or
        8'h57: t = 21'b00_10_1_0101_1001_1101_1000;    // or
        8'h58: t = 21'b00_10_1_0110_1000_1011_1000;    // and
        8'h59: t = 21'b00_11_1_0110_1001_1011_1000;    // and
        8'h5a: t = 21'b00_10_1_0110_1001_1011_1000;    // and
        8'h5b: t = 21'b00_10_1_0110_1001_1011_1000;    // and
        8'h5c: t = 21'b00_10_1_0110_1000_1011_1000;    // and
        8'h5d: t = 21'b00_10_1_0110_1000_1011_1000;    // and
        8'h5e: t = 21'b00_10_1_0110_1001_1101_1000;    // and
        8'h5f: t = 21'b00_10_1_0110_1001_1101_1000;    // and
        8'h60: t = 21'b00_10_1_1000_1000_1011_1000;    // shl
        8'h62: t = 21'b00_10_1_1000_1001_1011_1000;    // shl
        8'h63: t = 21'b00_10_1_1000_1001_1011_1000;    // shl
        8'h66: t = 21'b00_10_1_1000_1001_1101_1000;    // shl
        8'h67: t = 21'b00_10_1_1000_1001_1101_1000;    // shl
        8'h68: t = 21'b00_10_1_1011_1000_1011_1000;    // asr
        8'h6a: t = 21'b00_10_1_1011_1001_1011_1000;    // asr
        8'h6b: t = 21'b00_10_1_1011_1001_1011_1000;    // asr
        8'h6e: t = 21'b00_10_1_1011_1001_1101_1000;    // asr
        8'h6f: t = 21'b00_10_1_1011_1001_1101_1000;    // asr
        8'h70: t = 21'b00_10_1_1001_1000_1011_1000;    // lsr
        8'h72: t = 21'b00_10_1_1001_1001_1011_1000;    // lsr
        8'h73: t = 21'b00_10_1_1001_1001_1011_1000;    // lsr
        8'h76: t = 21'b00_10_1_1001_1001_1101_1000;    // lsr
        8'h77: t = 21'b00_10_1_1001_1001_1101_1000;    // lsr
        8'h78: t = 21'b00_10_1_0010_1000_1011_1000;    // iseq
        8'h79: t = 21'b00_11_1_0010_1001_1011_1000;    // iseq
        8'h7a: t = 21'b00_10_1_0010_1001_1011_1000;    // iseq
        8'h7b: t = 21'b00_10_1_0010_1001_1011_1000;    // iseq
        8'h7c: t = 21'b00_10_1_0011_1000_1011_1000;    // isset
        8'h7d: t = 21'b00_10_1_0011_1000_1011_1000;    // isset
        8'h7e: t = 21'b00_10_1_0010_1001_1101_1000;    // iseq
        8'h7f: t = 21'b00_10_1_0010_1001_1101_1000;    // iseq
        8'h80: t = 21'b00_01_1_0000_0001_0000_0001;    // add
        8'h81: t = 21'b00_01_1_0101_0001_1000_0000;    // or
        8'h82: t = 21'b00_01_1_0101_0000_1000_0001;    // or
        8'h83: t = 21'b00_01_1_0111_xxxx_1000_0000;    // mov
        8'h84: t = 21'b00_01_1_0100_0000_1001_0000;    // xor
        8'h85: t = 21'b00_01_1_0000_0000_0001_0000;    // add
        8'h87: t = 21'b00_01_0_xxxx_xxxx_xxxx_xxxx;    // nop
        8'h88: t = 21'b00_11_1_0111_xxxx_0100_1010;    // mov
        8'h89: t = 21'b00_11_1_0111_xxxx_0100_1010;    // mov
        8'h8a: t = 21'b00_11_1_0111_xxxx_0100_1010;    // mov
        8'h8b: t = 21'b00_11_1_0111_xxxx_0100_1010;    // mov
        8'h8c: t = 21'b00_11_1_0111_xxxx_0100_1010;    // mov
        8'h8d: t = 21'b00_11_1_0111_xxxx_0100_1010;    // mov
        8'h8e: t = 21'b00_11_1_0111_xxxx_0100_1010;    // mov
        8'h8f: t = 21'b00_11_1_0111_xxxx_0100_1010;    // mov
        8'h90: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // push
        8'h91: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // stm
        8'h92: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // push
        8'h93: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // stm
        8'h94: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // stm
        8'h95: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // stm
        8'h96: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // push
        8'h97: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // push
        8'h98: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // pop
        8'h99: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ldm
        8'h9a: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // pop
        8'h9b: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ldm
        8'h9c: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ldm
        8'h9d: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // ldm
        8'h9e: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // pop
        8'h9f: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // pop
        8'ha0: t = 21'b10_11_x_xxxx_xxxx_xxxx_xxxx;    // br
        8'ha1: t = 21'b01_11_x_xxxx_xxxx_xxxx_xxxx;    // jmp
        8'ha2: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // jmp
        8'ha3: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // jmpr
        8'ha4: t = 21'b10_11_x_xxxx_xxxx_xxxx_xxxx;    // brclr
        8'ha5: t = 21'b10_11_x_xxxx_xxxx_xxxx_xxxx;    // brclr
        8'ha6: t = 21'b10_11_x_xxxx_xxxx_xxxx_xxxx;    // br
        8'ha7: t = 21'b10_11_x_xxxx_xxxx_xxxx_xxxx;    // br
        8'ha9: t = 21'b01_11_x_xxxx_xxxx_xxxx_xxxx;    // call
        8'haa: t = 21'b01_10_x_xxxx_xxxx_xxxx_xxxx;    // call
        8'hab: t = 21'b01_01_x_xxxx_xxxx_xxxx_xxxx;    // ret
        8'hac: t = 21'b10_11_x_xxxx_xxxx_xxxx_xxxx;    // brset
        8'had: t = 21'b10_11_x_xxxx_xxxx_xxxx_xxxx;    // brset
        8'hae: t = 21'b01_01_x_xxxx_xxxx_xxxx_xxxx;    // sei
        8'haf: t = 21'b01_01_x_xxxx_xxxx_xxxx_xxxx;    // cli
        default: t = 21'b01_01_x_xxxx_xxxx_xxxx_xxxx;
        endcase
    end

    assign {kind, len, wen, alu_op, lhs_src, rhs_src, dest_src} = t;
    assign halt = (op == 8'h01);

endmodule
