// =============================================================================
// ucode.sv - the pipelined experiment's microcode ROM
// =============================================================================
//
// GENERATED by tools/gen-pipe-ucode.js, whose header describes the word.
// Do not edit.
//
// 10 routines and idle, eight steps each, in 256 words of 16 bits: one
// block RAM.
//     entry  0  idle        
//     entry  1  ld8          1 byte
//     entry  2  ld           2 bytes
//     entry  3  pop/ldm 1    2 bytes
//     entry  4  pop/ldm 2    4 bytes
//     entry  5  pop/ldm 3    6 bytes
//     entry  6  st8          1 byte
//     entry  7  st           2 bytes
//     entry  8  push/stm 1   2 bytes
//     entry  9  push/stm 2   4 bytes
//     entry 10  push/stm 3   6 bytes
// =============================================================================

module pipe_ucode (
    input  logic        clk,
    input  logic [7:0]  addr,      // {entry, step - 1}; 0 when idle
    output logic [15:0] word       // the word addressed at the last edge
);

    logic [15:0] rom [0:255];
    initial begin
        rom[8'h00] = 16'h0000;
        rom[8'h01] = 16'h0000;
        rom[8'h02] = 16'h0000;
        rom[8'h03] = 16'h0000;
        rom[8'h04] = 16'h0000;
        rom[8'h05] = 16'h0000;
        rom[8'h06] = 16'h0000;
        rom[8'h07] = 16'h0000;
        rom[8'h08] = 16'h0002;
        rom[8'h09] = 16'h0018;
        rom[8'h0a] = 16'h0000;
        rom[8'h0b] = 16'h0000;
        rom[8'h0c] = 16'h0000;
        rom[8'h0d] = 16'h0000;
        rom[8'h0e] = 16'h0000;
        rom[8'h0f] = 16'h0000;
        rom[8'h10] = 16'h0007;
        rom[8'h11] = 16'h0002;
        rom[8'h12] = 16'h0018;
        rom[8'h13] = 16'h0000;
        rom[8'h14] = 16'h0000;
        rom[8'h15] = 16'h0000;
        rom[8'h16] = 16'h0000;
        rom[8'h17] = 16'h0000;
        rom[8'h18] = 16'h0047;
        rom[8'h19] = 16'h0002;
        rom[8'h1a] = 16'h0018;
        rom[8'h1b] = 16'h0000;
        rom[8'h1c] = 16'h0000;
        rom[8'h1d] = 16'h0000;
        rom[8'h1e] = 16'h0000;
        rom[8'h1f] = 16'h0000;
        rom[8'h20] = 16'h0043;
        rom[8'h21] = 16'h0003;
        rom[8'h22] = 16'h0017;
        rom[8'h23] = 16'h0002;
        rom[8'h24] = 16'h0028;
        rom[8'h25] = 16'h0000;
        rom[8'h26] = 16'h0000;
        rom[8'h27] = 16'h0000;
        rom[8'h28] = 16'h0043;
        rom[8'h29] = 16'h0003;
        rom[8'h2a] = 16'h0013;
        rom[8'h2b] = 16'h0003;
        rom[8'h2c] = 16'h0027;
        rom[8'h2d] = 16'h0002;
        rom[8'h2e] = 16'h0038;
        rom[8'h2f] = 16'h0000;
        rom[8'h30] = 16'h000d;
        rom[8'h31] = 16'h0000;
        rom[8'h32] = 16'h0000;
        rom[8'h33] = 16'h0000;
        rom[8'h34] = 16'h0000;
        rom[8'h35] = 16'h0000;
        rom[8'h36] = 16'h0000;
        rom[8'h37] = 16'h0000;
        rom[8'h38] = 16'h0481;
        rom[8'h39] = 16'h000d;
        rom[8'h3a] = 16'h0000;
        rom[8'h3b] = 16'h0000;
        rom[8'h3c] = 16'h0000;
        rom[8'h3d] = 16'h0000;
        rom[8'h3e] = 16'h0000;
        rom[8'h3f] = 16'h0000;
        rom[8'h40] = 16'h0481;
        rom[8'h41] = 16'h0005;
        rom[8'h42] = 16'h0048;
        rom[8'h43] = 16'h0000;
        rom[8'h44] = 16'h0000;
        rom[8'h45] = 16'h0000;
        rom[8'h46] = 16'h0000;
        rom[8'h47] = 16'h0000;
        rom[8'h48] = 16'h0481;
        rom[8'h49] = 16'h0181;
        rom[8'h4a] = 16'h0581;
        rom[8'h4b] = 16'h0005;
        rom[8'h4c] = 16'h0048;
        rom[8'h4d] = 16'h0000;
        rom[8'h4e] = 16'h0000;
        rom[8'h4f] = 16'h0000;
        rom[8'h50] = 16'h0481;
        rom[8'h51] = 16'h0181;
        rom[8'h52] = 16'h0581;
        rom[8'h53] = 16'h0281;
        rom[8'h54] = 16'h0681;
        rom[8'h55] = 16'h0005;
        rom[8'h56] = 16'h0048;
        rom[8'h57] = 16'h0000;
        rom[8'h58] = 16'h0000;
        rom[8'h59] = 16'h0000;
        rom[8'h5a] = 16'h0000;
        rom[8'h5b] = 16'h0000;
        rom[8'h5c] = 16'h0000;
        rom[8'h5d] = 16'h0000;
        rom[8'h5e] = 16'h0000;
        rom[8'h5f] = 16'h0000;
        rom[8'h60] = 16'h0000;
        rom[8'h61] = 16'h0000;
        rom[8'h62] = 16'h0000;
        rom[8'h63] = 16'h0000;
        rom[8'h64] = 16'h0000;
        rom[8'h65] = 16'h0000;
        rom[8'h66] = 16'h0000;
        rom[8'h67] = 16'h0000;
        rom[8'h68] = 16'h0000;
        rom[8'h69] = 16'h0000;
        rom[8'h6a] = 16'h0000;
        rom[8'h6b] = 16'h0000;
        rom[8'h6c] = 16'h0000;
        rom[8'h6d] = 16'h0000;
        rom[8'h6e] = 16'h0000;
        rom[8'h6f] = 16'h0000;
        rom[8'h70] = 16'h0000;
        rom[8'h71] = 16'h0000;
        rom[8'h72] = 16'h0000;
        rom[8'h73] = 16'h0000;
        rom[8'h74] = 16'h0000;
        rom[8'h75] = 16'h0000;
        rom[8'h76] = 16'h0000;
        rom[8'h77] = 16'h0000;
        rom[8'h78] = 16'h0000;
        rom[8'h79] = 16'h0000;
        rom[8'h7a] = 16'h0000;
        rom[8'h7b] = 16'h0000;
        rom[8'h7c] = 16'h0000;
        rom[8'h7d] = 16'h0000;
        rom[8'h7e] = 16'h0000;
        rom[8'h7f] = 16'h0000;
        rom[8'h80] = 16'h0000;
        rom[8'h81] = 16'h0000;
        rom[8'h82] = 16'h0000;
        rom[8'h83] = 16'h0000;
        rom[8'h84] = 16'h0000;
        rom[8'h85] = 16'h0000;
        rom[8'h86] = 16'h0000;
        rom[8'h87] = 16'h0000;
        rom[8'h88] = 16'h0000;
        rom[8'h89] = 16'h0000;
        rom[8'h8a] = 16'h0000;
        rom[8'h8b] = 16'h0000;
        rom[8'h8c] = 16'h0000;
        rom[8'h8d] = 16'h0000;
        rom[8'h8e] = 16'h0000;
        rom[8'h8f] = 16'h0000;
        rom[8'h90] = 16'h0000;
        rom[8'h91] = 16'h0000;
        rom[8'h92] = 16'h0000;
        rom[8'h93] = 16'h0000;
        rom[8'h94] = 16'h0000;
        rom[8'h95] = 16'h0000;
        rom[8'h96] = 16'h0000;
        rom[8'h97] = 16'h0000;
        rom[8'h98] = 16'h0000;
        rom[8'h99] = 16'h0000;
        rom[8'h9a] = 16'h0000;
        rom[8'h9b] = 16'h0000;
        rom[8'h9c] = 16'h0000;
        rom[8'h9d] = 16'h0000;
        rom[8'h9e] = 16'h0000;
        rom[8'h9f] = 16'h0000;
        rom[8'ha0] = 16'h0000;
        rom[8'ha1] = 16'h0000;
        rom[8'ha2] = 16'h0000;
        rom[8'ha3] = 16'h0000;
        rom[8'ha4] = 16'h0000;
        rom[8'ha5] = 16'h0000;
        rom[8'ha6] = 16'h0000;
        rom[8'ha7] = 16'h0000;
        rom[8'ha8] = 16'h0000;
        rom[8'ha9] = 16'h0000;
        rom[8'haa] = 16'h0000;
        rom[8'hab] = 16'h0000;
        rom[8'hac] = 16'h0000;
        rom[8'had] = 16'h0000;
        rom[8'hae] = 16'h0000;
        rom[8'haf] = 16'h0000;
        rom[8'hb0] = 16'h0000;
        rom[8'hb1] = 16'h0000;
        rom[8'hb2] = 16'h0000;
        rom[8'hb3] = 16'h0000;
        rom[8'hb4] = 16'h0000;
        rom[8'hb5] = 16'h0000;
        rom[8'hb6] = 16'h0000;
        rom[8'hb7] = 16'h0000;
        rom[8'hb8] = 16'h0000;
        rom[8'hb9] = 16'h0000;
        rom[8'hba] = 16'h0000;
        rom[8'hbb] = 16'h0000;
        rom[8'hbc] = 16'h0000;
        rom[8'hbd] = 16'h0000;
        rom[8'hbe] = 16'h0000;
        rom[8'hbf] = 16'h0000;
        rom[8'hc0] = 16'h0000;
        rom[8'hc1] = 16'h0000;
        rom[8'hc2] = 16'h0000;
        rom[8'hc3] = 16'h0000;
        rom[8'hc4] = 16'h0000;
        rom[8'hc5] = 16'h0000;
        rom[8'hc6] = 16'h0000;
        rom[8'hc7] = 16'h0000;
        rom[8'hc8] = 16'h0000;
        rom[8'hc9] = 16'h0000;
        rom[8'hca] = 16'h0000;
        rom[8'hcb] = 16'h0000;
        rom[8'hcc] = 16'h0000;
        rom[8'hcd] = 16'h0000;
        rom[8'hce] = 16'h0000;
        rom[8'hcf] = 16'h0000;
        rom[8'hd0] = 16'h0000;
        rom[8'hd1] = 16'h0000;
        rom[8'hd2] = 16'h0000;
        rom[8'hd3] = 16'h0000;
        rom[8'hd4] = 16'h0000;
        rom[8'hd5] = 16'h0000;
        rom[8'hd6] = 16'h0000;
        rom[8'hd7] = 16'h0000;
        rom[8'hd8] = 16'h0000;
        rom[8'hd9] = 16'h0000;
        rom[8'hda] = 16'h0000;
        rom[8'hdb] = 16'h0000;
        rom[8'hdc] = 16'h0000;
        rom[8'hdd] = 16'h0000;
        rom[8'hde] = 16'h0000;
        rom[8'hdf] = 16'h0000;
        rom[8'he0] = 16'h0000;
        rom[8'he1] = 16'h0000;
        rom[8'he2] = 16'h0000;
        rom[8'he3] = 16'h0000;
        rom[8'he4] = 16'h0000;
        rom[8'he5] = 16'h0000;
        rom[8'he6] = 16'h0000;
        rom[8'he7] = 16'h0000;
        rom[8'he8] = 16'h0000;
        rom[8'he9] = 16'h0000;
        rom[8'hea] = 16'h0000;
        rom[8'heb] = 16'h0000;
        rom[8'hec] = 16'h0000;
        rom[8'hed] = 16'h0000;
        rom[8'hee] = 16'h0000;
        rom[8'hef] = 16'h0000;
        rom[8'hf0] = 16'h0000;
        rom[8'hf1] = 16'h0000;
        rom[8'hf2] = 16'h0000;
        rom[8'hf3] = 16'h0000;
        rom[8'hf4] = 16'h0000;
        rom[8'hf5] = 16'h0000;
        rom[8'hf6] = 16'h0000;
        rom[8'hf7] = 16'h0000;
        rom[8'hf8] = 16'h0000;
        rom[8'hf9] = 16'h0000;
        rom[8'hfa] = 16'h0000;
        rom[8'hfb] = 16'h0000;
        rom[8'hfc] = 16'h0000;
        rom[8'hfd] = 16'h0000;
        rom[8'hfe] = 16'h0000;
        rom[8'hff] = 16'h0000;
    end

    always_ff @(posedge clk) word <= rom[addr];

endmodule
